- chrome/content/zotero/xpcom/translation/translate.js
> Fix regression from 0cd183613f5dacc85676109c3a5c6930e3632fae

- chrome/content/zotero/attachLink.xul
- chrome/content/zotero/xpcom/attachments.js
Re https://forums.zotero.org/discussion/45709/attach-link-to-url-not-working/
> Attach link from URI fix

- chrome/content/zotero/xpcom/zotero.js
> Retrieve unmangled unicode strings from preferences

- chrome/content/zotero/xpcom/translation/translate_item.js
Also, cleaner parsing messages
Currently, importing file attachments with HTTP urls goes through a bunch of parsing trying to find the local file first and then falling back to URL. This patch allows those check to be short-circuited.
> Don't try to parse path if it looks like a web URL

- chrome/content/zotero/webpagedump/common.js
- chrome/content/zotero/webpagedump/domsaver.js
Regression from 5f8b56ef86a898caf1449eeefd198ba6e0247d4b
> Fix snapshots

- chrome/content/zotero/xpcom/utilities.js
Re https://forums.zotero.org/discussion/47176/beta-item-fields-mapping-to-weird-csl-variables/
> Regression from f0bd1e77ffab6dbc7fbd600dc1acc11844aa2e02

- chrome/content/zotero/browser.js
> Add stopPropagation to menuitem of new icon

- chrome/content/zotero/zoteroPane.js
As requested at
https://github.com/zotero/zotero/pull/668#issuecomment-84090670
> No prompt for remove if no top-level items are selected

- chrome/content/zotero/xpcom/utilities.js
- test/tests/utilities.js
Fixes regression from 37921b09100cd35697173be39f272837ec7c1f95 but also this should be better overall
> Revise ZU.cleanISBN

- chrome/content/zotero/xpcom/translation/translate.js
Would make it easier to make sure that users have up-to-date translators e,g, https://forums.zotero.org/discussion/47939/import-keywords-containing-several-words/
> More verbose logging for translation

- chrome/content/zotero/preferences/preferences_firefox.xul
- chrome/content/zotero/preferences/preferences_proxies.js
> Add Edit button to proxy list

- chrome/content/zotero/xpcom/mime.js
- chrome/content/zotero/xpcom/translation/translate_item.js
Fixes #677 plus some additional cleanup
> [api_syncing] Merge 849803473a0386aacc86745466d56f0ff3463f48

- chrome/content/zotero/xpcom/connector/translator.js
- chrome/content/zotero/xpcom/translation/translator.js
Regression from 82998e986e079b932b534f97385e96238aefb1be and 9450d0797f648453288b1b59d9daa692dcba7e8a
Sorry for the oversight.
> Fix properToProxy converter functions

- chrome/content/zotero/xpcom/utilities.js
- test/content/support.js
- test/tests/data/allTypesAndFields.js
- test/tests/data/citeProcJSExport.js
- test/tests/data/itemJSON.js
- test/tests/data/translatorExport.js
- test/tests/data/translatorExportLegacy.js
Re https://forums.zotero.org/discussion/49780/beta-singlefield-authors-not-citing-properly/
CiteProc updated since @fbennett altered institutional author handling in 1.0.599 https://bitbucket.org/fbennett/citeproc-js/issue/173/fix-institutional-authors-jiggery-poker
> Fix institutional author export to CiteProc

- chrome/content/zotero/xpcom/citeproc-prereqs.js
- chrome/content/zotero/xpcom/citeproc.js
- components/zotero-service.js
And split off Zotero additions
Re https://forums.zotero.org/discussion/50512/institutional-singlefield-creator/ and follow-up from #757
> Update citeproc-js to 1.1.25

- chrome/content/zotero/xpcom/citeproc.js
Re https://github.com/zotero/zotero/pull/794#issuecomment-120564983
> Update citeproc-js to 1.1.39

- chrome/content/zotero/ingester/selectitems.js
Green-lighted by @dstillman and @aurimasv (see https://github.com/zotero/translators/issues/919#issuecomment-121369540).
Works for me. Should merge cleanly to "master".
> Check single items in selection window

- chrome/content/zotero/browser.js
- chrome/content/zotero/xpcom/translation/translate.js
I'm still not really sure what the problem was. But this seems to eliminate the leak for me.
> Fix #810, memory leak

- chrome/content/zotero/xpcom/integration.js
Re https://forums.zotero.org/discussion/50701/cant-insert-citationzotero-asks-to-modify-all-my-citations/
> Debugging code for checking manually modified citations

- chrome/content/zotero/xpcom/date.js
- chrome/content/zotero/xpcom/utilities.js
- test/tests/data/citeProcJSExport.js
- test/tests/utilities.js
Re https://forums.zotero.org/discussion/50943/error-updating-document-invalid-field-false-in-itemfieldsisbasefield/
> Fix issues with computerProgram citations

- components/zotero-protocol-handler.js
Closes #842
Also:
Changes AsyncChannel to be a coroutine. Couldn't find any tests for it, but Dan said it was okay to do it and testing on the attachment types I have seems to be fine.
> Recognizes and opens files even without extensions.

- chrome/content/zotero/preferences/preferences_sync.js
- chrome/content/zotero/preferences/preferences_sync.xul
- chrome/content/zotero/xpcom/http.js
- chrome/content/zotero/xpcom/sync/syncAPIClient.js
- chrome/content/zotero/xpcom/sync/syncLocal.js
- chrome/content/zotero/xpcom/sync/syncRunner.js
- chrome/locale/en-US/zotero/preferences.dtd
- chrome/locale/en-US/zotero/zotero.properties
- chrome/skin/default/zotero/preferences.css
- test/content/runtests.html
- test/resource/sinon-as-promised.js
- test/tests/preferences_syncTest.js
- test/tests/syncRunnerTest.js
And adds an indicator for valid sync credentials
> Restores the functionality of 4.0 for sync settings 

- chrome/content/zotero/xpcom/http.js
> Hide password in debug output of key request

- chrome/content/zotero-platform/unix/itemPane.css
- chrome/content/zotero/itemPane.js
- chrome/content/zotero/itemPane.xul
- chrome/content/zotero/preferences/preferences_advanced.xul
- chrome/content/zotero/xpcom/itemTreeView.js
- chrome/content/zotero/xpcom/utilities_internal.js
- chrome/content/zotero/zoteroPane.js
- chrome/locale/en-US/zotero/preferences.dtd
- chrome/locale/en-US/zotero/zotero.properties
- chrome/skin/default/zotero/itemPane.css
- defaults/preferences/zotero.js
- test/tests/itemPaneTest.js
Not mentioned in the issue, but also adds a button to mark selected feed items read/unread which is context aware.
> Add feed menu buttons. Close adomasven/zotero#9.

- chrome/content/zotero/xpcom/feedReader.js
> Fixes feed-import (and possibly other feed) test unhandled rejections

- chrome/content/zotero/recognizePDF.js
- chrome/content/zotero/xpcom/data/collection.js
- chrome/content/zotero/xpcom/data/item.js
This fixes an 'An unexpected error occurred.' issue when attempting to get metadata from a PDF.
> Add items from RecognizePDF in a DB transaction

- chrome/content/zotero-platform/mac/overlay.css
- chrome/content/zotero/itemPane.xul
- chrome/content/zotero/preferences/preferences_general.xul
- chrome/content/zotero/xpcom/zotero.js
- chrome/content/zotero/zoteroPane.js
- chrome/content/zotero/zoteroPane.xul
- chrome/locale/en-US/zotero/preferences.dtd
- chrome/skin/default/zotero/overlay.css
- defaults/preferences/zotero.js
See https://github.com/zotero/zotero/pull/1006 for more discussion and a screenshot!
> Add a second horizontal layout to Zotero for small screens

- chrome/content/zotero/xpcom/data/feed.js
- chrome/content/zotero/xpcom/data/feeds.js
- chrome/content/zotero/xpcom/notifier.js
- chrome/content/zotero/xpcom/sync/syncRunner.js
- chrome/content/zotero/xpcom/syncedSettings.js
- test/tests/feedTest.js
- test/tests/feedsTest.js
Adds feed syncing and makes SyncedSettings JSON for feeds more compact as discussed in #1037
> Feed syncing

- chrome/content/zotero/xpcom/translation/translate_item.js
In response to https://forums.zotero.org/discussion/60375?page=1#Item_6
> Sort items for translator

- chrome/content/zotero/xpcom/zotero.js
Accidentally ran into this today.
> Fixes a bug when zotero dir exists elsewhere and you want to select a custom one

- chrome/content/zotero/xpcom/connector/cachedTypes.js
- chrome/content/zotero/xpcom/connector/connector.js
- chrome/content/zotero/xpcom/connector/translate_item.js
- chrome/content/zotero/xpcom/connector/translator.js
- chrome/content/zotero/xpcom/translation/translate.js
- chrome/content/zotero/xpcom/translation/translator.js
These changes are essential in getting the firefox webextension as well as zotero-connector built from 5.0 to work. May as well push them out in the public beta.
All tests pass for me locally. Saving to client from existing connector works fine too.
> Adds conditions for WebExtensions in shared connector code

- chrome/content/zotero/tools/testTranslators/testTranslators.js
- chrome/content/zotero/tools/testTranslators/translatorTester.js
- chrome/content/zotero/xpcom/connector/repo.js
- chrome/content/zotero/xpcom/connector/translator.js
- chrome/content/zotero/xpcom/server_connector.js
- chrome/content/zotero/xpcom/translation/translate.js
- chrome/content/zotero/xpcom/translation/translators.js
- test/content/support.js
- test/tests/server_connectorTest.js
- test/tests/translateTest.js
Occurs when not using `with` statement, which is highly discouraged and
unsupported in strict mode.
> Fixes overriden Zotero object in connector sandboxes

- chrome/content/zotero/xpcom/translation/translate.js
- test/content/support.js
- test/tests/translateTest.js
Accidentally discovered a bug while testing connector translation functionality
> Fix nested translators that rely on child translator tags

- chrome/locale/en-US/zotero/zotero.properties
(could also write "in the .doc(x) file format")
> Clarify that fields work both with .doc and .docx

- chrome/content/zotero/xpcom/connector/translator.js
- chrome/content/zotero/xpcom/server_connector.js
- chrome/content/zotero/xpcom/translation/translators.js
Fixes Zotero for Firefox connector breakage. Adds proper support for Browser Extensions.
Might still need some tweaking for safari.
> Connector targetAll support

- chrome/content/zotero/xpcom/connector/connector.js
- chrome/content/zotero/xpcom/http.js
- chrome/content/zotero/xpcom/server.js
- chrome/content/zotero/xpcom/server_connector.js
- chrome/content/zotero/xpcom/style.js
- test/tests/server_connectorTest.js
Adds an endpoint to import styles and importable resources (BibTeX, RDF, RIS). Part of a huge upcoming update to connectors.
> Add server_connector endpoint to import styles and import translateable resources

- chrome/content/zotero/xpcom/utilities.js
- test/tests/utilitiesTest.js
Addresses https://forums.zotero.org/discussion/64352/5-0-beta-patent-rss-feeds
Not sure if this is the best way to handle it, but looking at `Utilities.cleanAuthors()`, I would question most of that code.
> Get a better last name if current guess starts with weird symbols

- chrome/content/zotero/bibliography.js
- chrome/content/zotero/xpcom/file.js
- chrome/content/zotero/xpcom/integration.js
- chrome/content/zotero/xpcom/style.js
- chrome/locale/en-US/zotero/zotero.properties
- test/tests/data/cell.csl
- test/tests/integrationTests.js
- test/tests/styleTest.js
Closes #1084
~I'm not really sure what #1162 is about, but I'd like to address it on this same branch. I could not reproduce document prefs being stored on failure.~
Edit:
Closes #1162 
Closes #685
> Fix document preferences dialog failing when styles unloaded.

- chrome/content/zotero/bibliography.js
- chrome/content/zotero/integration/integrationDocPrefs.xul
- chrome/content/zotero/xpcom/integration.js
- chrome/locale/en-US/zotero/zotero.dtd
- chrome/locale/en-US/zotero/zotero.properties
- chrome/skin/default/zotero/bibliography.css
- test/tests/integrationTest.js
Before:
<a href="https://cloud.githubusercontent.com/assets/5899315/25622282/993840d8-2f5c-11e7-9bf5-d5fdc584364e.png"><img src="https://cloud.githubusercontent.com/assets/5899315/25622282/993840d8-2f5c-11e7-9bf5-d5fdc584364e.png" width="70%"/></a>
Now: 
<a href="https://cloud.githubusercontent.com/assets/5899315/25622241/7aa352a2-2f5c-11e7-9f70-da6cb2735f48.png"><img src="https://cloud.githubusercontent.com/assets/5899315/25622241/7aa352a2-2f5c-11e7-9f70-da6cb2735f48.png" width="70%"/></a>
> Document preferences cleanup

- chrome/content/zotero/preferences/preferences_search.xul
> Return pdfMaxPages to search preferences

- .gitmodules
References the master branch of submodules so that they can easily be updated using `git submodule update --remote` as e.g. described in https://stackoverflow.com/a/18797720/873661.
> Track master branch of submodules

- chrome/content/zotero/xpcom/utilities_internal.js
- test/tests/utilities_internalTest.js
> Fix PMID and arXiv identifiers extraction

- chrome/content/zotero/fileInterface.js
The existing destination has never really been the appropriate page for this dialogue, as it has never actual listed the supported formats.
> Update link to import formats documentation

- chrome/content/zotero/xpcom/attachments.js
https://forums.zotero.org/discussion/comment/316070/#Comment_316070
> Add support for marginnoteapp:// URI protocol

- chrome/content/zotero/tools/testTranslators/translatorTester.js
- chrome/content/zotero/xpcom/file.js
- chrome/content/zotero/xpcom/schema.js
- chrome/content/zotero/xpcom/translation/translate.js
- chrome/content/zotero/xpcom/translation/translator.js
- chrome/content/zotero/xpcom/translation/translators.js
- test/tests/translateTest.js
This is a prerequisite for https://github.com/zotero/scaffold/issues/105.
We can land this after releasing 5.0.70.
> Add ability for Scaffold to provide alternative translators

- chrome/content/zotero/bindings/itembox.xml
This PR resolves the first two issue described in #1874.
> Fix an issue where when trying to remove a creator, while it is being edited, next creator is removed instead

- chrome/content/zotero/xpcom/singlefile.js
- chrome/content/zotero/xpcom/utilities_internal.js
- scripts/babel-worker.js
Fixes #1893
Also consolidate the SingleFile config/user scripts into one file for both client and connector
> Fix CORS issues in SingleFile

- chrome/content/zotero/xpcom/server.js
- test/tests/serverTest.js
An empty body is still valid. Was causing an issue for empty favicons.
https://forums.zotero.org/discussion/85600/bug-report-no-snapshot-in-zotero-beta
> Fix server not handling empty body in multi-part request. Fixes #1897 

- chrome/content/zotero/createParentDialog.js
- chrome/content/zotero/createParentDialog.xul
- chrome/content/zotero/editContextMenu.js
- chrome/content/zotero/xpcom/intl.js
> Add context menu for React textboxes to Create Parent Dialog

- chrome/content/zotero/xpcom/report.js
- components/zotero-protocol-handler.js
Fixes #2002. The report generation code is quite specific therefore it might be better to review this fix.
> Display embedded images in item reports

- chrome/content/zotero/import/mendeley/mendeleyImport.js
This PR removes the code to deal with long path shenanigans on Windows. Temporary file is stored as `m-api-${file.id}.${ext}`, actual file name is kept in memory.
> Mendeley import: Simplify filename logic #2067

- chrome/content/zotero/xpcom/utilities_translate.js
See https://github.com/zotero/translators/pull/2463#issuecomment-863564641.
> Make resolveURL available to translators

- chrome/content/zotero/import/mendeley/mendeleyImport.js
- chrome/content/zotero/xpcom/attachments.js
> Move temp downloaded files instead of copying #2149 

- chrome/content/scaffold/scaffold.js
This fixes an import error that renders the Scaffold UI nonfunctional.
> Fix Scaffold failing to initialize

- chrome/content/zotero/locateManager.xul
- chrome/locale/en-US/zotero/preferences.dtd
- chrome/locale/en-US/zotero/zotero.properties
The Locate dropdown isn't in the Info pane, and the text was a bit more verbose than it needed to be.
> Correct Lookup Engine description

- test/tests/translateTest.js
> Add tests for async web translation

- chrome/content/zotero/fileInterface.js
> Set default filename when exporting single note

- chrome/content/zotero/xpcom/data/search.js
- chrome/content/zotero/xpcom/data/searchConditions.js
- chrome/locale/en-US/zotero/zotero.properties
Author, editor, or book author.
Fixes #2346.
> Search by specific creator type

- chrome/content/zotero/itemTree.jsx
Improves item tree fast-scrolling performance when attachment column is enabled, but adds a noticeable attachment state pop-in.
I didn't want to commit this immediately since perhaps we find the pop-in not desirable, or want to tweak the delay option.
> Delay querying attachment state from DB on tree scroll

- chrome/content/zotero/components/virtualized-table.jsx
- chrome/content/zotero/itemTree.jsx
- chrome/content/zotero/itemTreeColumns.jsx
- chrome/locale/en-US/zotero/zotero.dtd
> Add Short Title item tree column

- README.md
Point visitors to our new Github Actions CI
> README.md: Update CI Badge

- chrome/content/zotero/itemTree.jsx
- chrome/content/zotero/xpcom/data/items.js
> Fix next duplicates set selection after merge

- scripts/note-editor.js
- scripts/pdf-reader.js
- scripts/pdf-worker.js
Part of a fix for zotero#2264. 
Other requires PRs:
* https://github.com/zotero/note-editor/pull/32
* https://github.com/zotero/pdf-reader/pull/81
* https://github.com/zotero/pdf-worker/pull/13
Also fix for another issue that might affect building from source on all platforms:
* https://github.com/zotero/zotero-standalone-build/pull/93
> Fix build on win

- chrome/content/zotero/zoteroPane.js
> Disable Import actions in uneditable libraries

- chrome/content/zotero/components/icons.jsx
- chrome/content/zotero/components/tabBar.jsx
- chrome/content/zotero/tabs.js
- scss/components/_tabBar.scss
- scss/mac/_tabBar.scss
> Make tab bar scrollable

- test/tests/utilities_itemTest.js
> Add tests for improved `compareCallNumbers`

- chrome/content/zotero/bindings/noteeditor.xml
- chrome/content/zotero/contextPane.js
- chrome/content/zotero/tabs.js
- chrome/content/zotero/xpcom/reader.js
Implemented as discussed. We can try this out.
Fixes #2650
> Implement smart notes switching in contextPane

- chrome/content/zotero-platform/mac/overlay.css
- chrome/content/zotero-platform/unix/overlay.css
- chrome/content/zotero-platform/win/overlay.css
- chrome/content/zotero/elements/quickSearchTextbox.js
- chrome/content/zotero/searchDialog.xhtml
- chrome/content/zotero/xpcom/utilities_internal.js
- chrome/content/zotero/xpcom/zotero.js
- chrome/content/zotero/zoteroPane.xhtml
- chrome/skin/default/zotero/overlay.css
- chrome/skin/default/zotero/zotero.css
- scss/_quickSearchTextbox.scss
- scss/components/_quickSearchTextbox.scss
- scss/linux/_quickSearchTextbox.scss
- scss/mac/_quickSearchTextbox.scss
- scss/quickSearchTextbox-mac.scss
- scss/quickSearchTextbox-unix.scss
- scss/quickSearchTextbox-win.scss
- scss/win/_quickSearchTextbox.scss
> fx-compat: Restore quick search menu and update styles

- scss/mac/_search.scss
Updated URI and moved icon a bit so it's correctly positioned. Resolves #2679
> fx-compat: Fix missing icon in tag selector #2679

- chrome/content/zotero/import/importWizard.js
- chrome/content/zotero/import/importWizard.xul
- chrome/content/zotero/import/mendeley/mendeleyAPIUtils.js
- chrome/content/zotero/import/mendeley/mendeleyImport.js
- chrome/content/zotero/import/mendeley/mendeleySchemaMap.js
- test/tests/data/mendeleyMock/items-simple.json
- test/tests/mendeleyImportTest.js
* Detect import wizard being closed and interrupt import
* Advance progress bar while fetching metadata
* Add more logging
* Fix a bug in regex extracting fields to "extra"
* Fix a bug where importer would attempt to remove Zotero tmp directory
* Some code linting
> Multiple improvements to Mendeley importer

- chrome/content/zotero/elements/itemBox.js
- chrome/content/zotero/zoteroPane.js
- chrome/content/zotero/zoteroPane.xhtml
- chrome/locale/en-US/zotero/zotero.properties
> Add Book -> Book Section and Book Section -> Book to context menu

- chrome/content/zotero/elements/itemBox.js
This PR fixes #999 in fx102 branch using similar approach as with #2826 but with few small improvements:
* When opening creator type popup, first option is automatically selected (or last option if `ArrowUp` was used to trigger this)
* No need for custom focus outline
* Slightly better text-to-speech support
> fx-compat: Make creator buttons accessible via keyboard

- chrome/content/zotero/elements/itemBox.js
- chrome/locale/en-US/zotero/zotero.dtd
> Add "Capitalize" text transform to creator context menu

- chrome/content/zotero/elements/attachmentBox.js
> Attachment box: Add ability to copy URL of snapshot/link

- chrome/content/zotero/elements/noteEditor.js
- chrome/content/zotero/note.xhtml
- chrome/content/zotero/xpcom/editorInstance.js
As well as "Undo Add to Dictionary", as in Firefox.
Fixes #1390
> Add "Add to Dictionary" to note editor context menu

- chrome/content/zotero/components/virtualized-table.jsx
> v-t: Fix freeze when type-to-find wraps and first row is selected

- chrome/content/zotero/zoteroPane.js
Not adding a test for this because it would only give meaningful results when run under Windows, which I can't currently do and which CI doesn't do. Tested manually in a Windows VM, of course.
Fixes #2960
> LABD file relinking: Process using Unix paths

- chrome/content/zotero/xpcom/http.js
- test/tests/httpTest.js
And fix debugging.
Fixes #3000
> Preserve capitalization in `Zotero.HTTP.request()` headers

- chrome/content/scaffold/scaffold.js
> Scaffold: Support the `detectedItemType` test field

- chrome/content/zotero/platformKeys.js
> fx-compat: Disable macKeyset completely on non-Mac

- scripts/config.js
> Remove multimatch from the build process

- chrome/content/zotero/fileInterface.js
- chrome/content/zotero/import/importWizard.js
- chrome/content/zotero/import/importWizard.xhtml
- chrome/content/zotero/import/mendeley/mendeleyAPIUtils.js
- chrome/content/zotero/import/mendeley/mendeleyImport.js
- chrome/content/zotero/import/mendeley/mendeleyOnlineMappings.js
- chrome/content/zotero/xpcom/integration.js
- chrome/content/zotero/xpcom/prompt.js
- chrome/locale/en-US/zotero/zotero.dtd
- chrome/locale/en-US/zotero/zotero.ftl
- chrome/locale/en-US/zotero/zotero.properties
- components/zotero-service.js
- defaults/preferences/zotero.js
- scss/components/_import-wizard.scss
- test/tests/data/mendeleyMock/items-bad-data.json
- test/tests/data/mendeleyMock/items-empty-creators.json
- test/tests/data/mendeleyMock/items-simple-no-desktop-id.json
- test/tests/data/mendeleyMock/items-simple.json
- test/tests/data/mendeleyMock/items-updated.json
- test/tests/mendeleyImportTest.js
This PR resolved #2925. It ports the following functionality: 
* #2871
* Block Mendeley import if ZotFile installed
* #2948 + related tweaks
* #3016 
* #3018
I cherry-picked and then modified relevant commits to keep git history.
> Port Mendeley Import fixes & improvements from master branch

- chrome/content/zotero/xpcom/integration.js
- chrome/content/zotero/xpcom/server_integration.js
- components/zotero-service.js
Addresses zotero/zotero-word-for-mac-integration#35
> Add support for mac word transaction initialization via http

- chrome/content/zotero/ingester/selectitems.xhtml
See https://groups.google.com/g/zotero-dev/c/OscDKuO9Rao
> Fix selectitems.xhtml persist bug

- chrome/content/zotero/elements/itemBox.js
> Item box: Add DOI menu listeners once, disable when DOI is invalid

- chrome/content/zotero/xpcom/schema.js
- chrome/locale/en-US/zotero/zotero.properties
- resource/schema/system.sql
- resource/schema/userdata.sql
> Add EPUB to Attachment File Type in Advanced Search

- chrome/content/zotero/tabs.js
> Set opened reader tab index when state is restored

- chrome/content/zotero/xpcom/reader.js
> Remove reader events when plugin is disabled

- chrome/content/zotero/zoteroPane.js
- test/tests/zoteroPaneTest.js
And rewrite to clarify the logic.
Fixes #3432
> Detect more EPUBs in viewAttachment() content type fixer

- chrome/content/zotero/preferences/preferences.js
- chrome/content/zotero/preferences/preferences_general.xhtml
> Preferences search: Match Fluent strings

- chrome/content/zotero/zoteroPane.js
1. Trigger ZoteroPane.handleBlur on focusout instead of blur to remove highlight when itemTree entries loose focus even if ctrl/alt is still being held.
2. Prevent default event on Alt click on linux to avoid moving focus to menubar
3. Avoid re-triggering focus multiple times when ctrl is being held on windows to prevent highlight from becoming stuck and not going away.
4. Clear the highlight in `handleKeyUp` regardless of where the event comes from - this prevents highlight from being stuck when on windows focus is moved from itemTree before releasing `Ctrl`.
Fixes: #3410
> fix to collections highlight bugs

- chrome/content/scaffold/scaffold.js
> Scaffold: Use standard ESLint options

- chrome/content/zotero/standalone/standalone.js
- chrome/content/zotero/zoteroPane.js
- chrome/content/zotero/zoteroPane.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
- components/zotero-service.js
Not too long to fit in the toolbar!
Closes #3558
> Rename Safe Mode to Troubleshooting Mode

- scss/components/_item-tree.scss
- scss/themes/_dark.scss
- scss/themes/_light.scss
>  Reduce contrast of alternating row colors 

- app/build.sh
> build.sh: copy additional Linux icons

- chrome/content/zotero/zoteroPane.js
On Linux, trigger collection highlighting on Control instead of Alt to not interfere with the menubar.
Addresses: #3683
> linux: collection highlight on Control instead of Alt

- test/tests/translateTest.js
> Add test for SandboxItem#setExtra()

- scss/win/_titleBar.scss
I think it's a regression by beb7b51
> Fix window titlebar background color

- chrome/content/zotero/elements/abstractBox.js
- chrome/content/zotero/elements/collapsibleSection.js
- scss/elements/_collapsibleSection.scss
> Add summary to Abstract when collapsed

- chrome/content/zotero/integration/quickFormat.js
- Backspace from the very beginning of the input will delete the previous bubble, as opposed to removing the input itself. If it makes it so that two inputs are next to each other, they are merged.
- When a new input is created via a mouse click, and the current input is empty, manually delete it right away. Waiting for the blur handler to remove it makes it so that the bubbles shift back and forth for a moment when a new input is added and the old input is not removed.
- Minor tweak to make sure that even if there's a 'br' before an input, clicking before it will not make a new input and just refocus it.
Fixes: #3749
> quick-format: post-accessibility update edits

- chrome/skin/default/zotero/integration.css
Fix regression caused by 23da0d70b0743371f8a50cd7ed3c482dbb062102 where unwanted styles were applied to inputs inserted into quick format dialog
Fixes: #3803
> qf: fix conflicts with windows input styles

- scss/elements/_collapsibleSection.scss
> Fix collapsible section summary overflow-wrap

- app/scripts/fetch_xulrunner
> Use system browser for plugin links

- chrome/content/zotero/newCollectionDialog.js
- chrome/content/zotero/newCollectionDialog.xhtml
- scss/components/_menu.scss
> Fix incorrectly colored icons in create collection dialog

- chrome/content/zotero/elements/itemBox.js
> fx115: fix the itemBox rows stretching on menu open

- chrome/content/zotero/titlebar.js
> Fix window shrinking on each launch

- chrome/content/zotero/preferences/preferences_cite.xhtml
- chrome/content/zotero/tools/cslpreview.xhtml
> Open CSL tools as chrome and use native controls

- chrome/content/zotero/import/importWizard.js
- chrome/content/zotero/import/importWizard.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
- scss/components/_import-wizard.scss
* New messages for connection/certificate problems
* Change error message color to better fit after the redesign
Not sure about the wording of the messages, especially don't like how it looks when printed at the default wizard width (below) but couldn't come up with anything better (and this should be something people very rarely see!)
> Improve error message in the importer

- chrome/content/zotero/elements/itemPane.js
- chrome/content/zotero/zoteroPane.js
- scss/elements/_itemDetails.scss
> fx115: fix element width/height persist

- chrome/content/zotero/zoteroPane.xhtml
fix: #3979
since we are widely using `document.querySelector('popupset')` to append popups, i merged all popupsets into a global one, which is never hidden
> fx115: Fix popupset display

- chrome/content/zotero/elements/attachmentsBox.js
- chrome/content/zotero/elements/itemPaneSection.js
> Fix attachments section not updated when attachments are changed

- chrome/content/zotero/HiddenBrowser.jsm
- chrome/content/zotero/RemoteTranslate.jsm
- chrome/content/zotero/actors/ActorManager.jsm
- chrome/content/zotero/actors/FeedAbstractChild.jsm
- chrome/content/zotero/actors/FeedAbstractParent.jsm
- chrome/content/zotero/elements/abstractBox.js
- chrome/content/zotero/xpcom/feedReader.js
- resource/feeds/FeedProcessor.js
- scss/elements/_abstractBox.scss
- scss/feedAbstract.scss
- test/tests/feedReaderTest.js
> Render RSS description as HTML

- chrome/content/zotero/integration/quickFormat.js
- chrome/content/zotero/integration/quickFormat.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
I think this makes it a bit clearer as to what exactly is going on in the QF and what options are available.
Fixes: #4002
> vpat 26: quickformat more detailed instructions

- app/scripts/fetch_xulrunner
- chrome/content/scaffold/load.xhtml
- chrome/content/zotero/attachLink.xhtml
- chrome/content/zotero/bibliography.xhtml
- chrome/content/zotero/createParentDialog.xhtml
- chrome/content/zotero/exportOptions.xhtml
- chrome/content/zotero/feedSettings.xhtml
- chrome/content/zotero/ingester/selectitems.xhtml
- chrome/content/zotero/longTagFixer.xhtml
- chrome/content/zotero/newCollectionDialog.xhtml
- chrome/content/zotero/searchDialog.xhtml
- chrome/content/zotero/tagColorChooser.xhtml
> Fix dialog window titlebar

- chrome/content/zotero/standalone/hiddenWindow.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
Removed by mistake in 4e912b84c003d6b38e106412358b05e137e63f18.
> fx102: Hidden window: Bring back "Zotero" menuitem in Window menu

- chrome/content/zotero/elements/contextPane.js
- chrome/content/zotero/elements/notesContext.js
> Fix notes context handling issues

- chrome/content/zotero/xpcom/data/items.js
- test/tests/itemsTest.js
And add param name to JSDoc string.
Fixes #4136
> numDistinctFileAttachmentsForLabel: Filter best attachment

- chrome/content/zotero/elements/itemBox.js
> fix itembox creator btns not hiding in view mode

- chrome/content/zotero/elements/attachmentBox.js
- chrome/content/zotero/elements/attachmentPreview.js
- chrome/content/zotero/elements/attachmentsBox.js
- test/tests/itemPaneTest.js
> Refactor AttachmentPreview render and discard

- chrome/content/zotero/integration/quickFormat.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
It could be a simple aria-label but tooltip is more functional
> vpat 56: added tooltip for quickFormat Z-menu

- chrome/content/zotero/collectionTree.jsx
- scss/components/_collection-tree.scss
> Fix collection tree renaming background color

- chrome/content/zotero/integration/quickFormat.xhtml
> Fix QF titlebar on wayland

- chrome/skin/default/zotero/report/detail.css
- chrome/skin/default/zotero/report/detail_print.css
- chrome/skin/default/zotero/report/detail_screen.css
> Reports: Support dark mode

- chrome/content/zotero/ZoteroProtocolHandler.jsm
> `zotero://select` handler: Switch to library tab

- chrome/content/zotero/elements/collapsibleSection.js
- chrome/content/zotero/elements/itemDetails.js
And correct field/getter names in `collapsible-section` CE.
Closes #4177
> Persist pinned item pane section across restarts

- chrome/content/zotero/elements/duplicatesMergePane.js
- chrome/content/zotero/elements/itemBox.js
- chrome/content/zotero/elements/itemPane.js
- scss/elements/_duplicatesMergePane.scss
> Improve merge pane

- chrome/content/zotero/preferences/preferences_advanced.xhtml
- chrome/content/zotero/xpcom/localAPI/server_localAPI.js
- chrome/locale/en-US/zotero/preferences.ftl
- defaults/preferences/zotero.js
- test/runtests.sh
And keep enabled in tests.
Temp pref label pending discussion.
Closes #4234
> Add pref to enable local API

- chrome/content/zotero/xpcom/translation/translate_item.js
Don't try to download an open-access PDF when we already have an EPUB.
> Translation: Treat EPUBs as primary attachments

- chrome/content/zotero/elements/colorPicker.js
- chrome/content/zotero/tagColorChooser.xhtml
> Fix colorpicker styling on Windows

- scss/mac/_titleBar.scss
- scss/win/_titleBar.scss
> Fix window control in RTL

- chrome/content/scaffold/load.xhtml
- chrome/content/scaffold/scaffold.xhtml
- scss/components/_listheader.scss
- scss/components/_richlistbox.scss
- scss/mac/_tabbox.scss
- scss/scaffold.scss
- scss/win/components/_tabbox.scss
> Fix scaffold window UI

- chrome/content/zotero/components/virtualized-table.jsx
- chrome/content/zotero/elements/attachmentPreview.js
- chrome/content/zotero/elements/collapsibleSection.js
- chrome/content/zotero/elements/colorPicker.js
- chrome/content/zotero/elements/mergeGroup.js
- chrome/content/zotero/integration/quickFormat.js
- chrome/content/zotero/itemTree.jsx
- chrome/content/zotero/tabs.js
- chrome/content/zotero/xpcom/intl.js
- chrome/content/zotero/zoteroPane.js
- scss/elements/_attachmentPreview.scss
- scss/elements/_collapsibleSection.scss
Fixes #4352, fixes #4355, plus various other issues (collapsible-sections, quick format, and so on). Not touching the tag selector for now because it always displays LTR.
> RTL: Add direction-aware arrow key utilities, use in lots of places

- chrome/content/zotero/xpcom/attachments.js
- chrome/content/zotero/xpcom/utilities_internal.js
> Find Available PDF: Use translator-provided title

- chrome/content/zotero/elements/contextPane.js
- chrome/content/zotero/standalone/standalone.js
- chrome/content/zotero/tabs.js
- chrome/content/zotero/xpcom/reader.js
fix: #4284
introduce a new notifier type "load", "tab", a follow up fix to #4174
> Fix context notes pane not load

- chrome/content/zotero/selectItemsDialog.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
> Select Items dialog: Change accept button label to Select

- chrome/content/zotero/xpcom/data/item.js
> Fix Zotero.Item.fileExists calling on unsaved item

- chrome/content/zotero/elements/noteEditor.js
- chrome/content/zotero/elements/tagsBox.js
- chrome/content/zotero/note.xhtml
> Fix note editor tooltip

- chrome/content/zotero/elements/attachmentAnnotationsBox.js
> Fix attachment annotation box render on non-PDF items

- chrome/content/zotero/zoteroPane.js
- test/tests/zoteroPaneTest.js
> Auto-rename file and set automatic title after Create Parent Item

- chrome/content/zotero/elements/quickSearchTextbox.js
- scss/elements/_quickSearchTextbox.scss
> Fix quick search styling

- chrome/content/zotero/actors/ExternalLinkHandlerChild.jsm
- `javascript:` links
- Same-page anchor links
- Repo CSL links
Fixes #4504
> ExternalLinkHandler actor: Open some links internally, incl. styles

- chrome/content/zotero-platform/unix/integration.css
Followup to 55017926b57f329c1bf25df150892f8be2e86c19
> quickFormat: prevent css override of background color

- scss/components/_tabBar.scss
> Fix tab bar scroll arrow button click not working

- chrome/content/zotero/elements/abstractBox.js
Prior to this change, I observed that the number of ZoteroCP Web Content processes started at 3 and oscillated around 4  plus the number of tabs (while viewing an RSS feed in the main tab). After the change, it starts at 0, goes up to 4 when viewing an RSS feed, and otherwise stays at either 3 or 0, regardless of the number of tabs (3 if the browser was ever instantiated, 0 otherwise).
Fix #4530
>  Don't create a <browser> instance for each AbstractBox 

- chrome/content/zotero/components/tagSelector/tagSelectorList.jsx
- scss/components/_tagSelector.scss
Doesn't seem to break anything!
Fixes #4520
> Apply tag text color to ellipsis

- chrome/content/scaffold/load.xhtml
- chrome/content/scaffold/scaffold.xhtml
- chrome/content/zotero/elements/styleConfigurator.js
- scss/base/_base.scss
- scss/components/_listheader.scss
- scss/components/_richlistbox.scss
- scss/components/_virtualized-table.scss
- scss/elements/_richlistCheckbox.scss
- scss/scaffold.scss
Fix richlistitem unwanted focus ring on Linux
fix: #4510
> Unify richlistitem styling rules

- chrome/content/zotero/components/tooltip.js
- hide tooltip on click and make sure it does not appear for a bit to avoid race conditions (e.g. clicking
right after mousemove stopped)
- do not display a tooltip if a mouse key is being held (e.g. during drag in itemTree)
Fixes: #4519
> Fix to Zotero_Tooltip not disappearing after click

- chrome/content/zotero/elements/notesBox.js
> Update Notes section on add

- chrome/content/zotero/collectionTree.jsx
- Reuse editing input when row and `editingName` haven't changed during refresh
- Don't return the `waitForSelect()` promise when we've already awaited a selection method
- This was causing sync to hang because the selection didn't actually change, meaning the promise returned from `notify()` never resolved until the user manually switched rows
Fixes #4486
> Collection tree: Keep editing state through refresh

- chrome/content/zotero/elements/contextPane.js
> Fix two item panes occasionally appear at same time

- chrome/content/zotero/xpcom/integration.js
- chrome/locale/en-US/zotero/zotero.ftl
- chrome/locale/en-US/zotero/zotero.properties
Links to https://www.zotero.org/support/kb/could_not_find_a_running_word_instance
> Show a different error message for WinWord when no document is found

- chrome/content/zotero/elements/attachmentBox.js
- chrome/content/zotero/elements/attachmentsBox.js
- chrome/content/zotero/elements/itemDetails.js
- test/tests/itemPaneTest.js
> Lazy load attachment preview

- chrome/content/zotero/contextPane.js
> Fix Context Pane doesn't work in stack mode

- scss/components/_item-tree.scss
Fix margins while maintaining correct order after 596703b21b892d2a673b0103bac9077e82f75942
> RTL: Small item tree tag display fixes

- chrome/content/zotero/elements/contextPane.js
> Fix context pane lazy load

- scss/mac/_menupopup.scss
> No menu background when not hovered on MacOS

- chrome/content/zotero/xpcom/reader.js
- chrome/content/zotero/xpcom/utilities_internal.js
> Strip Citeproc.js markup in window titles

- chrome/content/zotero/lookup.js
- chrome/content/zotero/zoteroPane.xhtml
- chrome/locale/en-US/zotero/zotero.ftl
And some cleanup.
Closes #3706
> Add "Paste and Go" option to lookup context menu

- chrome/content/zotero/elements/attachmentPreview.js
- scss/elements/_attachmentPreview.scss
> Use dynamic  max height for attachment preview

- chrome/content/zotero/customElements.js
No effect on keyboard navigation.
Fixes #4614
> Hide selected item background when mouse leaves menu

- scss/about.scss
> Fix padding on Close button in About window

- app/win/installer/installer.nsi
This PR extends the `UninstallOld` routine in the installer to check both the `HKLM` and `HKCU` keys for past installations.
A few notes:
* I'm using `SetShellVarContext` to switch the context to `current`. NSIS does not support using a variable argument with `EnumRegKey`.
* There is a `Wow6432Node` in `HKCU`. Since we call `SetRegView 32` combined with `SetShellVarContext current`, I expected `EnumRegKey` to iterate through the keys under `Wow6432Node`. However, it appears to use the "normal" `HKCU` instead.
To test this, I've been using the following registry files: 
* [Normal HKCU](https://tnajdek-public.s3.us-east-1.amazonaws.com/1y/facd0522c801e161ced9a913b89f66fa638a9687.reg)
* [Wow6432Node HKCU](https://tnajdek-public.s3.us-east-1.amazonaws.com/1y/2e11bead9a13334bb608a3e97601c3c851b …
> Check both HKLM and HKCU in UninstallOld

- chrome/content/zotero/xpcom/data/search.js
- test/tests/searchTest.js
> Fix quicksearch phrase search not respecting scope

- chrome/content/zotero/elements/attachmentBox.js
- chrome/locale/en-US/zotero/zotero.ftl
> Add Title to attachment box

- chrome/content/zotero/elements/styleConfigurator.js
- scss/preferences/_cite.scss
> Make manage styles link in style configurator keyboard accessible

- chrome/content/zotero/elements/itemPane.js
- chrome/locale/en-US/zotero/zotero.ftl
> Unify message in the item details pane when trash contains collections or searches

- chrome/content/zotero/locateMenu.js
And lint and remove no-op ifs.
Closes #4675
> View Online: Prioritize DOI over attachment URL

- chrome/content/zotero/elements/autocompleteTextArea.js
> autocomplete-textarea: Reposition popup on resize

- chrome/content/scaffold/scaffold.xhtml
- chrome/content/zotero/zoteroPane.xhtml
Added aria-labels for titlebar buttons to minimize/maximize/close window.
> vpat 8: aria hide titlebar buttons

- chrome/locale/en-US/zotero/reader.ftl
- chrome/locale/en-US/zotero/zotero.ftl
- js-build/config.js
Reader.ftl file with strings for aria-labels and a11y announcements.
Needed for https://github.com/zotero/reader/pull/144  per https://github.com/zotero/reader/pull/142#issuecomment-2410574199
> reader.ftl file for a11y strings in the reader

- chrome/content/zotero/zoteroPane.js
Fixes: #4788
https://github.com/user-attachments/assets/5ccc423a-75f7-421d-9eae-0ed0ed0f3684
> centerscreen "My Publications" dialog

- chrome/content/zotero/itemTree.jsx
- chrome/content/zotero/xpcom/itemTreeManager.js
https://groups.google.com/g/zotero-dev/c/4jqa8QIk6DM/m/qbq55IUbBAAJ
> Pass document to ItemTree API renderCell

- chrome/content/zotero/elements/attachmentsBox.js
- test/tests/itemPaneTest.js
> Fix child attachment shows up in item pane after being moved to trash

- chrome/content/zotero/elements/attachmentPreview.js
- chrome/content/zotero/xpcom/reader.js
- scss/elements/_attachmentPreview.scss
fix: #4147
fixes 1 and 6, 2-5 should already be fixed after #4653
> Fix attachment preview display issues

- chrome/content/zotero/elements/itemBox.js
- test/tests/pluginAPITest.js
Add test for info row render after item change
fix: #4874
> Fix item pane custom info row render after item change

- chrome/content/zotero/elements/itemDetails.js
- chrome/content/zotero/elements/itemPaneSidenav.js
- test/content/support.js
- test/tests/itemPaneTest.js
Fix wrong vertical position in the Item Pane after switching from a note
fix: #4276
Finally found an elegant solution for this issue. Replaces #4288
> Fix Item Pane unstable rendering during scrolling

- chrome/content/zotero/zoteroPane.js
We need to work with platform paths now - PathUtils isn't tolerant of incorrect path separators. Tested and working on Windows with Unix and Windows paths.
Also relink and save other items sequentially.
Fixes #4882
> Fix several automatic relinking regressions due to PathUtils

- scss/mac/components/_menupopup.scss
> fx128: Fix macOS menupopup style

- chrome/content/zotero/elements/itemDetails.js
- chrome/content/zotero/elements/itemPane.js
- chrome/content/zotero/elements/itemPaneSidenav.js
- test/content/support.js
- test/tests/itemPaneTest.js
> Item pane scroll pos fix after switching from note

- defaults/preferences/zotero.js
> Fx128: Enable -moz-context-properties for SVG context properties

- scss/components/_window.scss
> fx128: dialog window background

- chrome/content/zotero/zoteroPane.js
fix: https://groups.google.com/g/zotero-dev/c/FwfrxviKi8I
>  Fix ZoteroPane#buildFieldTransformMenu document variable

- app/scripts/fetch_xulrunner
> hide "Report" button from plugins context menu

- chrome/content/zotero/xpcom/fileHandlers.js
- chrome/content/zotero/xpcom/utilities_internal.js
- chrome/content/zotero/xpcom/zotero.js
> Unset Mozilla environment variables after launch

- chrome/content/zotero/elements/itemBox.js
- test/tests/itemPaneTest.js
And do a little related cleanup.
Fixes #5000
> Item box: Fix missing Copy/Paste menuitems on URL fields

- chrome/content/zotero/xpcom/localAPI/server_localAPI.js
- test/tests/server_localAPITest.js
> Local API: Add /fulltext endpoints

- chrome/content/zotero/locateMenu.js
- chrome/content/zotero/standalone/standalone.js
- chrome/content/zotero/zoteroPane.js
> Check editability based on tab when adding attachments

- chrome/content/zotero/collectionTree.jsx
- chrome/content/zotero/xpcom/zotero.js
- test/tests/collectionTreeTest.js
Fixes: #1943
https://github.com/user-attachments/assets/6d2a833c-fb59-4403-94d0-546c35ef4100
> Allow dragging items, collections, and searches into trash

- chrome/content/zotero/xpcom/reader.js
> Fix attachment preview background

- app/build.sh
I haven't tested on Linux, but the files are in the same place, so it should work the same way.
> Restore window controls on Windows/Linux

- chrome/content/zotero/integration/citationDialog/keyboardHandler.mjs
> Citation dialog: refocus input on cmd/ctrl-f

- chrome/content/zotero/xpcom/storage.js
- scss/components/_item-tree.scss
Improved styling and modified the update logic to trigger updates only if the percentage changes instead of using throttling.
https://github.com/user-attachments/assets/7b44fc95-c2e7-4ad2-abdb-93e8e72a5401
https://github.com/user-attachments/assets/ef412fcf-5ca6-4568-aff2-570ddebc49f4
Closes #5144 and #5145.
> Improve attachment column progress meter

- chrome/content/zotero/integration/citationDialog.js
- chrome/locale/en-US/zotero/integration.ftl
> Citation dialog: localized "Add to Citation" label

- chrome/content/scaffold/scaffold.js
- chrome/content/scaffold/scaffold.xhtml
- chrome/content/scaffold/scaffoldItemPreview.js
- chrome/content/scaffold/scaffoldItemPreviews.js
- chrome/content/zotero/elements/annotationRow.js
- chrome/content/zotero/elements/attachmentRow.js
- chrome/content/zotero/xpcom/translation/translate_item.js
- chrome/content/zotero/xpcom/utilities_internal.js
- scss/elements/_noteRow.scss
- scss/scaffold.scss
https://github.com/user-attachments/assets/5649e52a-0e40-4ac9-9aca-d8c4531f31a0
With a diff showing changes made during cleaning.
> Scaffold: Add item pane-like preview of translated items

- chrome/content/zotero/elements/attachmentRow.js
- chrome/content/zotero/elements/attachmentsBox.js
- chrome/locale/en-US/zotero/zotero.ftl
- scss/abstracts/_mixins.scss
- scss/elements/_attachmentRow.scss
- scss/elements/_librariesCollectionsBox.scss
- scss/elements/_notesBox.scss
- scss/elements/_tagsBox.scss
https://github.com/user-attachments/assets/814a1bc6-e97c-4e4c-8265-e999be3aba28
Closes #5041.
> Add ability to delete attachment from item pane

- chrome/content/zotero/integration/citationDialog.js
- chrome/content/zotero/integration/citationDialog/searchHandler.mjs
- if the search string looks like an identifier, use it as a search condition. https://forums.zotero.org/discussion/comment/489309/#Comment_489309
- have library use "All fields and tags" search mode. Followup to https://github.com/zotero/zotero/commit/b78bf8e24b1285855c9ff9ac680e6d07dfed268a
https://github.com/user-attachments/assets/3ef57f15-914d-496a-8bb4-31aa64eb4a67
> Citation dialog: search by doi, issn or isbn

- chrome/content/zotero/elements/attachmentRow.js
- chrome/content/zotero/elements/notesBox.js
- chrome/content/zotero/elements/relatedBox.js
- chrome/content/zotero/xpcom/utilities_internal.js
> Make item pane attachments/notes/related item rows draggable

- chrome/content/zotero/elements/itemPaneSidenav.js
> Fix can't move second-to-last item pane section down

- chrome/content/scaffold/scaffold.js
- js-build/babel-worker.js
- js-build/config.js
- package-lock.json
- package.json
- resource/monacopilot-core.mjs
- resource/monacopilot.mjs
It's not perfect, but it's good enough to enable as a hidden pref! `scaffold.completions.mistralAPIKey` needs to be set to an API key for [Codestral](https://console.mistral.ai/codestral), which is free (at the moment).
> Scaffold code completion

- chrome/content/zotero/preferences/preferences_advanced.js
- test/tests/preferences_advancedTest.js
> Skip invalid relative path when changing LABD

- chrome/content/zotero/itemTree.jsx
Fixes: #5257
https://github.com/user-attachments/assets/fc9b1d15-304b-4145-8eef-ed00cc8805c3
> Disable itemTree row drop between child rows

- chrome/content/zotero/elements/tagsBox.js
> Fixes for tags-box regressions

- chrome/content/zotero/zoteroPane.js
Small followup to tweak https://github.com/zotero/zotero/pull/5328/commits/572174438682b1699ab5a44601586fedcebe9871 per https://forums.zotero.org/discussion/comment/493631/#Comment_493631
> Fix web link attachment row not selected on create

- chrome/content/zotero/integration/quickFormat.js
Properly load all item data for items opened in tabs to account for the fact that they can belong to
libraries that are not yet loaded.
Similar fix as in https://github.com/zotero/zotero/commit/4421de63de709c238a5418cb9747aeb2085fcd93
> qf: fix breakage with unloaded tab

- chrome/content/zotero/contextPane.js
> Fix reader sidenav buttons wrongly disabled

- chrome/content/zotero/elements/tabsMenuPanel.js
> Fix tabs menu filtering out empty title

- chrome/content/zotero/elements/itemPaneHeader.js
Once styles are initialized. `ItemPaneHeader#init()` runs at startup because the item pane is always in the DOM, even if an item isn't being viewed, so this is sufficient to cache the Engine at startup.
Also extract prefs as constants.
Closes #5404
> Cache CSL Engine for item pane header

- scss/abstracts/_mixins.scss
- scss/components/_tabBar.scss
- scss/components/_titleBar.scss
- scss/components/_toolbar.scss
- scss/linux/_titleBar.scss
- scss/preferences.scss
> Improve linux window appearance

- scss/components/_mainWindow.scss
- scss/elements/_tabsMenuPanel.scss
- scss/linux/_menupopup.scss
> Improve linux popup appearance

- chrome/content/zotero/collectionTree.jsx
- test/tests/zoteroPaneTest.js
> Fix subcollection not being copied to library root via context menu

- app/assets/application.ini
> Set Gecko MinVersion to 140

- chrome/content/zotero/components/tabBar.jsx
When a tab is closed via clicks on "X" button, record and lock all tabs' widths. That way, the "X" button of the tab that follows the one that was just deleted will land under the mouse cursor, allowing one to
delete many tabs. In addition, preserve the scroll position of the tab bar. If it's impossible because too many tabs were deleted, add a spacer after the last tab. When the mouse leaves the tab bar, tabs go back to their natural widths.
Fixes: #5523
https://github.com/user-attachments/assets/af5480eb-b410-4e1d-8762-06a856109119
> Maintain the size of tabs as they are being closed
