zotero/zotero

chrome/content/zotero-platform/mac/overlay.css
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul
chrome/skin/default/zotero/overlay.css

This belongs to issue #509 and was asked several times in the forum.
* Add attribute `collapse="after"` to the splitter and add a grippy element.
* To remember its state after restart I copied `zotero-persist="state"` which seems to do the job.
* Update the function `updateToolbarPosition` in zotero/zoteroPane.js:
* The width of the items-toolbar is corrected if the left pane is collapsed (and all the icons are grouped on the left margin together).
* If the right pane is collapsed, then the items-toolbar is made flexible (as the item-toolbar is already). As a result the icons from the two toolbars are spreaded evenly over the place.
I tested it in Firefox. Moreover, I installed the zotero-item-history plugin on top of it (this gives new icons to the toolbars). Everything works fine for …

Right pane (item-pane) can be collapsed

---

chrome/content/zotero/recognizePDF.js

Re https://forums.zotero.org/discussion/45641/error-getting-metadata/#Item_10
I don't really see a reason not to do this. We could also consider bumping the default to 15 right away.

Allow MAX_PAGES (for retrieving metadata) to be user-adjustable

---

chrome/content/zotero/xpcom/mimeTypeHandler.js
chrome/content/zotero/xpcom/zotero.js

This addresses two bugs:
* If Zotero is set to handle BibTeX/RIS/etc. files in Firefox, pressing Cancel was dropping the whole file instead of continuing to handle it by default application. This makes it impossible to download RIS files with the preference enabled.
* Changing the said preference was requiring a Zotero restart for it to take effect
It also adds a new feature. Zotero code can register observers for arbitrary Zotero preferences via `Zotero.Prefs.registerObserver`

Content handlers

---

chrome/content/zotero/xpcom/collectionTreeView.js

Re https://forums.zotero.org/discussion/46259/report-id-295014583/ and I think some others

Disable expand/collapse shortcuts in coll. tree when in-line editing

---

chrome/content/zotero/xpcom/openurl.js

The discoverResolvers function was looking for the wrong XML tag name representing OpenURL version 0.1 in the response from the WorldCat Registry

Fix for OpenURL 0.1 resolver detection

---

chrome/content/zotero/xpcom/translation/translate.js
chrome/content/zotero/xpcom/translation/translate_item.js

In import translators, it may not always be clear whether the given URI is a URL or a local file path. I'm a little concerned that this may open up some security hole (by, hypothetically, allowing web translators and, thus, web pages to attach files located throughout the file system) since we use `attachment.url` in a lot of translators and we would pay more attention to translators using `attachment.path`, but (1) translators can already use file: protocol via URL (2) I'm not really sure how useful such attack would be since Zotero copies files and whether there is really any vulnerability here. Maybe we should limit attachment.path use to import translators called directly (not by web translators)
Regression from 849803473a0386aacc86745466d56f0ff3463f48 (that piece of code was …

Allow file paths to be specified in attachment.url

---

chrome/content/zotero/xpcom/connector/translator.js

Re https://forums.zotero.org/discussion/45778/bug-isi-web-of-knowledge-records-are-not-saved-but-refs-citing-them-are/
Proxied URIs in Firefox in connector mode  were getting double-proxied.

Don't proxify proxied hosts

---

chrome/content/zotero/xpcom/connector/connector.js
chrome/content/zotero/xpcom/connector/translate_item.js
chrome/content/zotero/xpcom/cookieSandbox.js
chrome/content/zotero/xpcom/server_connector.js

Currently we ignore any cookies set from other domains while attempting to download attachments (through connector imports) and I'm not entirely sure why.
One issue is downloading attachments when importing via Chrome from cell.com (e.g. http://www.cell.com/abstract/S0092-8674(12)01407-9) Some of their PDFs are hosted on sciencedirect.com so we pass the sciencedirect.com url as attachment url to Zotero Standalone. We don't necessarily need to pass any cookies when fetching these attachments to start with, but sciencedirect does include a redirect (or two) that does set cookies, which end up being required to download the PDF.
This patch allows cookies to be set for different domains during this transaction and it implements domain-level cookie management within the cookie sandbox. It …

Manage cookies received from other hosts.

---

chrome/content/zotero/xpcom/sync.js

If the local data is to be resotres to the zotero server,
the settings like tag colors also need to be synced again.

Restore settings (tag colors) to server

---

chrome/content/zotero/tools/testTranslators/translatorTester.js

This is necessary to have functional tests for websites that redirect where a URL-based session ID has expired. E.g. http://www.bdsl-online.de/BDSL-DB/suche/Titelaufnahme.xml?vid={D620881E-7697-40A8-BF2C-4E898FD12362}&erg=0&Anzeige=10&Sprache=de&contenttype=text/html&Skript=titelaufnahme&Publikation_ID=028514998
See zotero/translators#821

Allow meta redirects when running web translator tests

---

chrome/content/zotero/tools/testTranslators/translatorTester.js

Zotero would discard these anyway when writing to DB. So this makes for more appropriate test cases

Discard redundant tags in translator tester

---

chrome/content/zotero/xpcom/translation/translate.js

by defaulting to HTTP
This would have addressed zotero/zotero-connectors#28 if CrossRef were available over HTTPS, but it's not, so that will require a different solution. Still, it would be good to be able to use protocol-relative URLs in search translators which also have to work outside of webpage context (e.g. add by identifier).

Resolve protocol-relative URLs outside of document context

---

chrome/locale/en-US/zotero/zotero.properties

Fixes #426: this allows the localization of the Word Processors Add-in button and messages displayed in the Prefs, under the "Word Processors" tab. These strings were previously hardcoded in the integration plugins.

Localize Word Processors tab in Preferences

---

.travis.yml
chrome/content/zotero/xpcom/zotero.js
components/zotero-service.js
test/runtests.sh
test/tests/recognizePDF.js

Also makes it unnecessary to adjust Firefox version numbers for each release
Disables recognizePDF test for PDFs with no DOIs, because I think they start failing due to GS captcha. It probably clears up once there are no recent commits.

Add Firefox Beta for Travis-CI testing

---

components/zotero-service.js

This is the format that's being output on Mac already when `dump`ing Error objects
```
SyntaxError: expected expression, got '}'
chrome://zotero/content/xpcom/http.js:982
makeZoteroContext@file:///C:/Users/Aurimas/Desktop/dev/zotero/components/zotero-service.js:254:4
ZoteroService@file:///C:/Users/Aurimas/Desktop/dev/zotero/components/zotero-service.js:311:4
XPCOMUtils__getFactory/factory.createInstance@resource://gre/modules/XPCOMUtils.jsm:292:19
@chrome://zotero/content/include.js:1:14
```

More informative error messages for failed file loads

---

chrome/content/zotero/bindings/itembox.xml
chrome/content/zotero/xpcom/utilities_internal.js
chrome/locale/en-US/zotero/zotero.dtd

I tried my hand at https://github.com/zotero/zotero/issues/295.
The "Open in Browser" function works, but my attempt to add a "Copy" function failed, and I was wondering if I could get some help. I found the incantation:
```
Components.classes["@mozilla.org/widget/clipboardhelper;1"]
.getService(Components.interfaces.nsIClipboardHelper)
.copyString("testString");
```
in fileInterface.js, but using it directly via my menuitem's `oncommand` breaks the code. Anything I'm missing?

Add DOI-field context-menu

---

chrome/content/zotero/preferences/preferences_firefox.xul
chrome/content/zotero/preferences/preferences_proxies.js
chrome/content/zotero/xpcom/proxy.js
chrome/locale/en-US/zotero/preferences.dtd
chrome/locale/en-US/zotero/zotero.properties
defaults/preferences/zotero.js

I find that the notification you get when Zotero automatically redirects you through a proxy to get a little annoying, especially when I'm opening a bunch of tabs from Google Scholar or the like. 
Unfortunately, I only speak English, so locale translations are a bit lacking in variety.

Add an option to not show the proxy redirection notification

---

chrome/content/zotero/preferences/preferences_export.js
chrome/content/zotero/preferences/preferences_export_firefox.xul

Adds an Edit button to the site-specific Quick Copy settings, and adds enabling/disabling logic for the Edit button and the existing "minus"/delete button.
Similar to #715 (would also close #265).

Add Edit button for site-specific Quick Copy settings

---

test/content/support.js

I wrote this for MLZ debugging before I noticed that a `stableStringify()` function was already in place. It uses a replacer function on `JSON.stringify()` itself, and produces the same output. Upside is that it's easier to read, and guaranteed to track the behavior of the native stringifier. Downside is that it touches the object itself; but as far as I can tell, the refactored object is identical in JS terms.
(I posted a caution on this earlier, but it was a false alarm - nothing is lost in the refactored object.)

Simplification of stableStringify()

---

test/content/support.js
test/tests/data/search/foo.html
test/tests/data/search/foobar.html
test/tests/searchTest.js

- also add withImportedAttachmentFromFile support function
I finally got these basics search tests to work with async. I am trying to establish a baseline of search tests so that sqlite fts has something to compare to.

Add basic tests for fulltext search

---

test/content/runtests.js
test/tests/itemTest.js

Since we don't wrap those in `Zotero.Promise.coroutine`, which means that they never end up running. Alternatively we could wrap them, but there's no reason we should be using these (and no one uses them on purpose)
I'm thinking that there should also be a way to throw or warn if `assert` is never invoked during a test, but I haven't figured out how to do that yet.

Check if attempting to use a legacy generator function in Mocha tests

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/translation/translate.js
chrome/content/zotero/xpcom/translation/translator.js

Seems like this should have been detected much earlier. It appears that attachment downloads from proxied pages in Firefox should have been broken since 7f7fe90ad5fc21502fb1ab2e84f793628cd9892d
The second commit doesn't really have much impact, so we can remove it for now, until #578 (probably for 5.0 release)

Attachment proxy fixes

---

chrome/content/zotero/xpcom/translation/translate.js
chrome/content/zotero/xpcom/translation/translate_item.js
test/runtests.sh
test/tests/data/snapshot/index.html
test/tests/translateTest.js

Also:
- Move some canonicalization of items returned by translators to `Zotero.Translate`
- Make `Zotero.Translate#translate` return a promise
- Add tests
Fixes #735, #736
Now implemented:

Use Zotero.Item.fromJSON() for saving from attachments

---

chrome/content/zotero/webpagedump/domsaver.js
chrome/content/zotero/xpcom/attachments.js

Re https://forums.zotero.org/discussion/49897/thecreate-web-page-item-from-current-pageis-sometimes-not-working-correctly/
There is something wrong with the way `nsIScriptableUnicodeConverter` converts to gbk (maybe other formats too). The HTML of http://www.cmiw.cn/forum.php is truncated in the middle of an em tag. In general, `ConvertFromUnicode` is supposed to return an `ACString` (not `AString`), which is not something that JavaScript can handle well.

Always save snapshots in UTF-8 encoding

---

chrome/content/zotero/recognizePDF.js

Should be helpful to track down why users get locked out.
So far, I've seen that clearing all cookies presents you with a new sort of CAPTCHA, which we don't account for. That should result in "No metadata found" messages. I forgot to look at the DOM the first time I got it and I haven't been able to reproduce it since, but I'll keep playing around.

Add more debug logging for RecognizePDF

---

chrome/content/zotero/bibliography.js
chrome/content/zotero/xpcom/integration.js

Seems like we forgot to do this properly.
Also fixes some logic with remembering last-used style/locale. Should now remember all explicit user selections.

Fix saving locale in Word documents

---

chrome/content/zotero/xpcom/style.js
chrome/content/zotero/xpcom/utilities.js
test/tests/utilities.js

Currently non-dropping particle parsing is being done automatically in CiteProc. This patch disables automatic parsing and moves it to `itemToCSLJSON`, which means that names are parsed when exporting to CSL JSON.
Also fixes the non-dropping particle handling reported [here](https://forums.zotero.org/discussion/30974/1/any-idea-why-an-a-author-comes-last-in-the-bibliography/) via citeproc update

Parse author names

---

chrome/content/zotero/zoteroPane.xul

You might be reluctant to forbid the user to resize it, but in this case (a graphic column, no text), I think this is better. Each time I resize one column, this one is widened and I never want that, who does?

Forbid "Attachments" column to be resized

---

chrome/content/zotero/zoteroPane.js

It's really convenient to find an item using ZotQuery on Mac. 
But there's a minor issue is that when the original focus is not on item tree column, select item will not focus the item tree column. So I have to use my cursor to make it focused to operate on the item. 
The expected behavior is that when select item, the item tree column should always be focused. 
This is the reasoning behind this commit.

make items tree column focused when select a item by running zotero://select/items/xxx.

---

chrome/content/zotero/xpcom/cite.js

When the user selects "Create Bibliography from Item(s)" with the "Notes" option, some entries come out incorrectly, when the input items require disambiguation in the selected style.
[HTML export of Presentation items with same author a](https://forums.zotero.org/discussion/51346/html-export-of-presentation-items-with-same-author-and-title-creates-duplicates/#Item_4)
In this case, Zotero is iterating over appendCitationCluster() to build the citations list. The lack of documentation on appendCitationCluster() is the root source of the issue - what the function does is a little more complex than its name implies.
Under the hood, appendCitationCluster() invokes processCitationCluster() to generate citations to be added, and just strips off the error segment from the return. What is not …

Fix bug in Create Bibliography from Item w/Notes

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/xpcom/quickCopy.js

This is a followup to #834, which turned out to be a little less than the "straightforward bug fix" I declared it to be.
This PR addresses the duplicate-cite issue reported [on the Zotero forums](https://forums.zotero.org/discussion/52886/).
As per discussion under #834, this fix will be specific to the 4.0 branch. In 5.0, the plan will be to reduce clutter by changing the signature of `makeFormattedBibliographyOrCitationList()` to receive the locale (plus the style), and instantiate the processor in that function.

Prevent duplicate items when copying citations to clipboard

---

chrome/content/zotero/xpcom/openurl.js

Especially, allow rft.subject and rft.description in core OpenURL without Dublin Core declared as format. This fixes #851

Relax condition in parseContextObject

---

chrome/content/zotero-platform/unix/publicationsDialog.css
chrome/content/zotero/publicationsDialog.js
chrome/content/zotero/publicationsDialog.xul

Linux seems to not be happy with hiding and restoring the *finish* button, so we just change the label of the *next* button instead. Closes #738 
Also a tiny fix which closes #740

Fixes the finish button on my publication wizard on linux

---

chrome/content/zotero/bindings/tagselector.xml

Closes #852
Currently shows a *+* icon for adding a tag and
a *link* icon for removing it.
There does not appear to be any way to have a custom mouse cursor,
which makes this interaction extremely unintuitive. It might be
possible to hack this in, but the issue does not really warrant the effort.
E.g. `window.setCursor` does not respond whilst dragging.

Remove tags on shift-drag

---

chrome/content/zotero/bindings/styled-textbox.xml

This addresses #935. I haven't tested it extensively, but it round-trips quotes and high-bit characters okay. If balanced tags come up that are missed in the parse they can be added to the spec object.

HTML/RTF and RTF/HTML conversion for styled textbox

---

chrome/content/zotero/bindings/styled-textbox.xml

There were a couple of glitches in the code.
* Named entities generated by the editor were coming out corrupted. I had hacked quote-marks, but I noticed that endash also failed, and there were lots of others. It was just a matter of applying text conversions in the right sequence, so I fixed that, and removed the quote-mark hacks.
* While poking around, I noticed that `output = output.substr(5, output.length-6)` was leaving "`</div`" at the end of the string, chopping only the terminal "`>`" instead of the whole tag&mdash;apparently JS applies the leading chop to the raw variable before chopping the tail, but the string value used in the argument remains unchanged. The corrupted tag wasn't hurting anything, but I fixed it in the code to get the intended string.

Bugfixes for new styled-textbox code

---

chrome/content/zotero/xpcom/progressWindow.js

`nArcs` is undefined in `this.ItemProgress.prototype.setProgress()`. This has been the case for a long time but never came up because the progress indicator isn't used in Zotero, I believe. I think it's a nice UI element though and could be used for non-disruptive progress indicators.

Bug fix progressWindow.js: nArcs undefined

---

chrome/content/zotero/feedSettings.xul
chrome/content/zotero/preferences/preferences_advanced.xul
chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/zotero.dtd

Also addresses the comment:
> (Moreover, I would also expect to receive directly an error if I try to set it to 0.)
We may want to allow deleting articles after 0 days, but 0 hour refresh interval doesn't make any sense, so I changed the minimum value to 1 and made the label more user friendly and consistent with the rest of the dialog.

Closes #961. Fixes feed dialogue remove read articles value not saving

---

chrome/content/zotero/xpcom/sync/syncRunner.js

Sean encountered an error when syncing from a 4.0 profile on a 5.0 client, prompting to enter credentials in the preferences. However, syncing started working after simply restarting firefox. 
The API key was actually correctly generated and set from legacy credentials, but not returned properly to `Zotero.SyncRunner` and thus causing an error.

Fixes sync error when transfering credentials from legacy to API key

---

chrome/content/zotero/bindings/filesyncstatus.xml
chrome/content/zotero/bindings/itembox.xml
chrome/content/zotero/bindings/styled-textbox.xml
chrome/content/zotero/bindings/zoterosearch.xml
chrome/content/zotero/charsetMenu.js
chrome/content/zotero/downloadOverlay.js
chrome/content/zotero/integration/editBibliographyDialog.js
chrome/content/zotero/locateManager.xul
chrome/content/zotero/preferences/preferences_advanced.js
chrome/content/zotero/preferences/preferences_sync.js
chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/tools/csledit.js
chrome/content/zotero/xpcom/annotate.js
chrome/content/zotero/xpcom/cite.js
chrome/content/zotero/xpcom/collectionTreeView.js
chrome/content/zotero/xpcom/cookieSandbox.js
chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/ipc.js
chrome/content/zotero/xpcom/itemTreeView.js
chrome/content/zotero/xpcom/locateManager.js
chrome/content/zotero/xpcom/mimeTypeHandler.js
chrome/content/zotero/xpcom/schema.js
chrome/content/zotero/xpcom/server.js
chrome/content/zotero/xpcom/server_connector.js
chrome/content/zotero/xpcom/storage/storageRequest.js
chrome/content/zotero/xpcom/storage/streamListener.js
chrome/content/zotero/xpcom/sync.js
chrome/content/zotero/xpcom/translation/translate_item.js
chrome/content/zotero/xpcom/zotero.js
components/zotero-service.js

The `for-each-in` loops are deprecated and will cause some warnings in the browser console (and are only compatible by Gecko):
```
JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead
```
@dstillman I can continue here to look at more of these loop cases, if you agree.

Fix some for each ... in cases

---

chrome/content/zotero/xpcom/zotero.js

Not sure whether this is desired but it helps to reduce the use of nsIFile to a minimum. `file.launch()` and `file.reveal()` are two of the few things that are not possible with OS.File/OS.Path. When that changes, Zotero.launchFile is the only function that needs to be modified if it works with string paths.

Allow string path as argument to Zotero.launchFile()

---

chrome/content/zotero/xpcom/itemTreeView.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul

Omitted Date Added, Date Modified, Attachments and Notes. Implemented using custom treecol attributes with `zotero-persist` to retain the configuration between sessions.

Closes #1008. Omit certain item list columns in feed views

---

chrome/content/zotero/bindings/itembox.xml
chrome/content/zotero/xpcom/data/feedItem.js
chrome/content/zotero/xpcom/date.js
chrome/content/zotero/xpcom/itemTreeView.js
test/tests/dateTest.js
test/tests/feedItemTest.js

Closes #1024 
Closes #1025 
Also see [this line](https://github.com/zotero/zotero/pull/1032/files#diff-3a5e2c983420f6c7932beb3925d76976R1046) where after a decision that '.' separator for date in dmy standard may be a bit too crazy it was changed to '/'.

Changes date parsing and handling for feeds. Closes #1024, #1025

---

chrome/content/zotero/xpcom/utilities.js

In order to make these mappings also available when the
script is used with [`loadSubScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/mozIJSSubScriptLoader) from outside, we
have to use `var` instead of `const`, `let`.
See https://github.com/aurimasv/z2csl/issues/6

Change const to var in utilities

---

chrome/content/zotero/xpcom/style.js

Fixes #1039 for me.
To test, install a dependent "note" style without a "class" attribute on `<style>` like Angelaki (https://www.zotero.org/styles?q=angelaki), and test it with a Zotero word processor plugin. In the current master branch, the style is mistakenly identified as an "in-text" style, and creates "in-text" citations. With the patch, it correctly behaves like a "note" style.
The code is a little hocus-pocus for me, but I based the new code on that of `Zotero.Style.prototype.__defineGetter__("hasBibliography", ...)` (https://github.com/zotero/zotero/blob/045554dd8e58a8a02bbac2cf621790db67797944/chrome/content/zotero/xpcom/style.js#L721), and it seems to work.

Correctly inherit "class" from parent style

---

test/content/support.js
test/tests/server_connectorTest.js

server_connectorTest - alternating port prevents
exceptions not catchable in JS for httpd server when the socket
and the port remains open after httpd.stop() callback
support - changes the window on which `setTimeout()` is ran in dialogs.
If the timeout is ran on the main window the `dialog` object appears to
lose certain properties and not respond to interactions completely.

Fixes freezing occuring on linux while running tests

---

chrome/content/zotero/xpcom/collectionTreeRow.js
chrome/content/zotero/xpcom/itemTreeView.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul
test/tests/zoteroPaneTest.js

I originally attempted this with zotero-persists and column attributes,
but there is no good way to make it succint paramswise and the code was
painful to look at too. Thus different group settings are stored in
preferences.
Currently there are two view groups: "feed" and "default". Items view
columns have two new attributes:
`default-in` - a space separated list of views in which a column is
visible by default
`disabled-in` - a space separated list of views in which a column is
disabled by default (invisible + not possible to enable)
Currently the settings are stored in a pref named `itemsView.columnVisibility`, but it could probably use a better name.

Adds custom view groups for different library types.

---

chrome/content/zotero/xpcom/feedReader.js

https://forums.zotero.org/discussion/60800?page=0#Item_10
Probably no reason to not fall back on links. Must be some crazy feeds if they change that and don't provide a GUID.

Use feed item links for guid if id unavailable

---

chrome/content/zotero/xpcom/data/feedItem.js

Closes #1059
Instead of falling back to webpage translation which is less detailed and accurate, clones the feed item into the library.

Clone feed item if no translators available

---

chrome/content/zotero/xpcom/http.js
chrome/content/zotero/xpcom/utilities_translate.js

This is mainly for translators which have to work with content negotiation,
e.g. ORCID API or API calls of ISBN agencies.

Allow ZU.doGet to have requestHeaders

---

chrome/content/zotero/xpcom/syncedSettings.js
chrome/content/zotero/xpcom/zotero.js
test/tests/syncedSettingsTest.js

Reported https://forums.zotero.org/discussion/61573?page=1#Item_4
SyncedSettings.set() caches values. If an object passed to set() is
modified after the call then get() returns that modified object.

Fixes feed sync bugs after conflicts.

---

test/runtests.sh

Only enabled on Xorg environments, so checks $DISPLAY
https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#X11_options
Can be used in combination with compiz to create a window rule and make Firefox not steal focus.

Adds a way to distinguish linux windows

---

chrome/content/zotero/xpcom/utilities.js
test/tests/utilities.js

add tests. @dstillman lmk if you're still willing to take this (to avoid uglier {} syntax for forcing DOIs) and if you'd want this for master instead or in addition.

Parse DOI: prefixed DOI from Extra

---

chrome/content/zotero/xpcom/cite.js

In response to [the quick copy indent thread](https://forums.zotero.org/discussion/9846/incorrect-margins-when-dragging-reference-to-word-2007-from-zotero-1-0/p2).
I've played around and these are my results:
- MS Word and Outlook outright ignore both padding and margin, but respect text-indent.
- Libre Office appears to ignore css styling completely.
- Gdocs ignores padding, but respects margin.
- Gmail ignores text-indent and randomly respects/ignores both padding and margin.
People should be using Word Plugins anyway, which work properly and we can fix this for at least Gdocs. Email users are screwed, but then again, email layout is an engineering field of its own.
Any ideas if the change could break anything else prominently used?

Change padding-left to margin-left property for hanging indent

---

chrome/content/zotero-platform/unix/itemPane.css
chrome/content/zotero-platform/unix/overlay.css

Also reduces separator width and adds a right margin to the tabpane. 
Before:
After:

Make itemPane white on linux

---

resource/schema/dateFormats.json
test/tests/dateTest.js

The Firefox French language pack contains some mistakes regarding the short form of months. I don't know where Mozilla found this list… Anyway French month parsing didn't work (for juin, juillet, décembre).
Actually these values aren't even the correct abbreviations but only the three or four first letters of the correct abbreviations. See the <a href="https://github.com/citation-style-language/locales/blob/master/locales-fr-FR.xml#L298">French CSL locale</a> for the correct abbreviations.
There's still a small glitch: when you put your mouse over the date field, if it contains "juill." "déc.", the tooltip shows 00 for the month, even if the parsing is correct (and the parsing indicator says d m y).

Amend short form of French months (continuing #64)

---

chrome/content/zotero/xpcom/data/dataObject.js

This line just crashed on me during a sync operation in Juris-M 5.0. It looks like a typo.

Probable typo in dataObject.js

---

gulpfile.js

This should resolve problem with race condition during builds. Also should allow running builds without running clean first (in which case relevant files are simply overwritten).

Fix a problem with race condition during builds 

---

chrome/locale/en-US/zotero/zotero.properties

"Report Errors" menu item was in Actions (gear) menu, which has been
hidden in 5.0 (cf. 82292eef77701c5f6eb19ec4b65aee0e7ebdbf30). It is now accessible from the Help menu.
Adjust Report Error instructions accordingly.

Remove reference to Actions menu (Report Error instructions)

---

chrome/content/zotero/tools/csledit.js

Some users have expressed a desire to use the Abbreviation Filter plugin with Zotero. A version compatible with the Zotero 5.0 code is available, but to work with the Style Editor embedded in Zotero, it needs access to the style instantiated in the editor popup. This pull request exposes the style for that purpose.

Expose styleEngine in csledit.js, for Abbreviation Filter

---

chrome/content/zotero/bibliography.js
chrome/content/zotero/integration/addCitationDialog.js
chrome/content/zotero/integration/editBibliographyDialog.js
chrome/content/zotero/integration/integrationDocPrefs.xul
chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/xpcom/cite.js
chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/server_connector.js
chrome/content/zotero/xpcom/utilities_internal.js
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
test/tests/integrationTest.js

So integration.js needed a refactor and some tests for a long time now. There is still a lot of room to improve, as the code is still quite dirty, but it's much better and more readable now, than before. Mainly, the document and session updates are localized and not all over the place, but there are still some weird circular object dependencies and for `Zotero.Integration.execCommand()` the session and document objects are globally exposed during a transaction.
----
The PR introduces the ability to delay citation updates and closes #1241. Note that this will speed up inserts that take 10min to 2s or so. Pretty good.
When a document update takes longer than 5s, a prompt is displayed:
Clicking *Yes* or *No* opens up document preferences window with the new option highlighted:
The checkbox …

Refactor integration and delay citation updates

---

chrome/content/zotero/xpcom/data/relations.js
test/tests/itemsTest.js

This is the patch referred to in a recent [post to zotero-dev](https://groups.google.com/forum/#!topic/zotero-dev/6kFmaW5YhtY). To recap, merge of two items was failing for me in a large-ish account (10,000 items), where the "subordinate" partner in the merge had an `owl:sameAs` relation to another library that had not been opened during the session. The merge failed with an "item not loaded" error.
This change async-ifies the failing function `getByObject()`, and swaps out synchronous data object `get()` in favor of `asyncGet()`. Nothing needs to be altered up the execution chain, because the `merge()` function in `items.js` was already a generator, and its call to `getByObject()` is already `yield`-ed. One other call to `getByObject()` inside relations.js needed minor changes to work …

Asyncify Zotero.Relations.getByObject(), called only from item merge.

---

chrome/content/zotero/progressQueueDialog.js
chrome/content/zotero/progressQueueDialog.xul
chrome/content/zotero/xpcom/progressQueue.js
chrome/content/zotero/xpcom/progressQueueDialog.js
chrome/content/zotero/xpcom/recognizePDF.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
chrome/skin/default/zotero/overlay.css
components/zotero-service.js
test/content/support.js
test/tests/itemTreeViewTest.js
test/tests/recognizePDFTest.js
test/tests/server_connectorTest.js

Any number of progress queues can be created at Zotero client initialization time with `Zotero.ProgressQueues.createQueue`. Queues can only be used with items. `Zotero_ProgressQueue_Dialogs` creates a dialog for each queue  and zoteroPane adds a toolbar button for each queue too. Queues are also waiting for internet connection.

Add universal progress queues

---

chrome/skin/default/zotero/report/detail_print.css

https://forums.zotero.org/discussion/72505/color-highlights-disappear-when-i-print-a-report#latest

Print highlight colors in Reports

---

test/tests/integrationTest.js

This pull request adds a test for the behavior noted in https://github.com/zotero/zotero/issues/1631, which led to the 1.1.215 update to `citeproc-js`. The test will fail with the current 1.1.212 processor version, but will pass when https://github.com/zotero/zotero/pull/1638 is merged and the 1.1.215 version of the processor is installed.

Test for bibliography sort update on change to item

---

chrome/content/zotero/xpcom/utilities.js

Solves zotero/translation-server#88.
Although it's not very elegant to put multi platform code to Zotero client, but this is what we are doing already.

Fix unescapeHTML on node.js

---

chrome/content/zotero/xpcom/cite.js

This PR addresses an issue raised by Derek Sifford a couple of years ago that I've been slow to move on, concerning a spec violation by the processor:
* **citeproc-js issue:** https://github.com/Juris-M/citeproc-js/issues/15
* **CSL spec language:** http://docs.citationstyles.org/en/1.0.1/specification.html#whitespace

Handle handingindent return from citeproc-js as boolean

---

chrome/content/zotero/xpcom/integration.js
chrome/locale/en-US/zotero/zotero.properties

We cannot use Zotero to display prompts because those tend to not focus the Zotero window properly. We cannot display prompts with options other than Yes/No/Ok/Cancel in Word and LibreOffice, so no "More Info" buttons either. To test add 
```
throw new Error("test");
```
at https://github.com/adomasven/zotero/blob/0cb056c994ccd4fa493a60d473d36638781afe0b/chrome/content/zotero/xpcom/integration.js#L248
Closes #1666

Display a more user-friendly error for integration errors

---

chrome/content/zotero/xpcom/utilities.js
test/tests/data/citeProcJSExport.js
test/tests/utilitiesTest.js

Although we've been using it for years, the `shortTitle` variable is not part of the [CSL Specification](http://docs.citationstyles.org/en/1.0.1/specification.html#standard-variables). In a [recent discussion](https://discourse.citationstyles.org/t/title-short-vs-shorttitle/1515), a developer queried why we weren't using `title-short` in the CSL test suite, @adam3smith suggested that Zotero be aligned with the spec, and although the processor is meant to handle both, it's a bit easier to work with the canonical name in code.
This PR would read both `shortTitle` and `title-short`, but write only the latter on export.

Export CSL JSON with title-short rather than shortTitle

---

chrome/content/zotero-platform/mac/bibliography.css
chrome/content/zotero/bibliography.js
chrome/content/zotero/integration/integrationDocPrefs.xul
chrome/content/zotero/xpcom/connector/httpIntegrationClient.js
chrome/content/zotero/xpcom/connector/server_connectorIntegration.js
chrome/content/zotero/xpcom/integration.js
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
chrome/skin/default/zotero/bibliography.css
test/tests/integrationTest.js

I need ideas for what the dialogs for Export and Import should say. Export converts all citations to their field-code representations (and appends doc prefs and bibl style at the end of the doc). Import reverses this. 
Support of this feature has to be implemented for each individual docs plugin separately (and the buttons will only appear if the plugins have support).
Addresses zotero/zotero-google-docs-integration#1

Document export-import UI and integration code

---

chrome/content/zotero/integration/addCitationDialog.js
chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/xpcom/integration.js
chrome/locale/en-US/zotero/zotero.properties

See #1703
Currently `Retractions.getRetractionsFromJSON()` fails with a HTTP 403 for me.

Add a checks and prompts for retracted items within an existing doc

---

chrome/content/zotero/xpcom/cite.js

So that it can be stored in Extra as "Type:" instead of "type:"
Replaces https://github.com/zotero/zotero/pull/1688

Add 'type' to variables list for extraToCSL

---

chrome/content/zotero/xpcom/zotero.js

Currently loading any page that uses history object `window.history` triggers `NS_ERROR_FAILURE`. Many single-page apps, including the new web-library, depend on availability of `window.history` and will crash without rendering anything if unexpectedly `NS_ERROR_FAILURE` is thrown when accessing `window.history`. 
This small change ensures that page loaded in the hidden browser can access `window.history`. However I'm not familiar enough with the codebase to say how would this affect other translators and other parts of Zotero that use `Zotero.Browser`.

Allow session history in a hidden browser

---

scripts/symlinks.js

On Windows, to avoid problems with symlinks, files are copied during the build instead. However source symlinks are not currently dereferenced during the copy leading to invalid symlinks being placed in the build folder and ultimately breaking the build. This PR adds dereferencing.

Fix build on Windows 

---

scripts/babel-worker.js
scripts/utils.js

Everywhere else we use `glob` for paths which deals with forward/backward slash apart from `babel-worker.js` where paths were compared verbatim, hence file-specific fixes weren't applied during the build on windows. This PR resolves this issue by using regex check instead.

Fix babel worker file-specific fixes check on Windows

---

.gitmodules
chrome/content/zotero/about.xul
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/connector/server_connector.js
chrome/content/zotero/xpcom/http.js
chrome/content/zotero/xpcom/singlefile.js
chrome/content/zotero/xpcom/translation/translate_item.js
chrome/content/zotero/xpcom/utilities_internal.js
scripts/babel-worker.js
scripts/config.js
test/tests/attachmentsTest.js
test/tests/server_connectorTest.js

Our SingleFileZ integration would save images inside directories following the
SingleFileZ format. However, Zotero does not support syncing sub-directories of
attachments. This commit switch back to a single HTML file with base64 encoded
resources. We think that the 33% increase in resources will be offset by the
compression of HTML and removal of JavaScript and unused CSS.
This commit does not fix past snapshots that were saved using SingleFileZ.

Switch back to SingleFile from SingleFileZ

---

chrome/content/zotero/xpcom/translation/translate.js

When using `doImport` a promise is returned, but was lacking a catch a
statement to ensure completion.
This fixes #1882

Fix bug with async translate process never returning.

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/connector/server_connector.js
chrome/content/zotero/xpcom/translation/translate_item.js
chrome/content/zotero/xpcom/utilities_internal.js
scripts/babel-worker.js
scripts/config.js
test/tests/attachmentsTest.js

- Using `sandboxPrototype` properly uses window as prototype
- This commit removes the need for our patch in babel-worker.js
https://github.com/gildas-lormeau/SingleFile/commit/3d0bc4cf9fd23e4fe8f5b684a89c69521c306b60
This fixes #1908 and other similar issues like it.
@dstillman I also turned off `removeFrames` and included an extra commit that properly injects scripts to retrieve frame contents in the client. So frames should be working in both the connector and the client without the 10 second delay we saw before.
Here are two forum posts which both now work with these commits:
https://forums.zotero.org/discussion/85726/error-report-zetero-connector-failed-to-upload-webpage-snapshot
https://forums.zotero.org/discussion/85603/bug-in-zotero-beta-video-iframe-image-not-saved-in-snapshot

Update SingleFile for bug fixes

---

chrome/content/zotero/xpcom/connector/server_connector.js
test/tests/server_connectorTest.js

https://forums.zotero.org/discussion/86796/duplicated-snapshots
I was able to replicate it by adding a 5 second delay here:
https://github.com/zotero/zotero/blob/a72ae1481631dcefe603ef9ff3a1a9f7f5c747d8/chrome/content/zotero/xpcom/translation/translate_item.js#L196
This was caused from a race condition and (a72ae14) did not fully
solve the problem. Now this is tested and fixed.

Fix double saving snapshots

---

chrome/content/zotero/components/form/input.jsx

The Input component doesn't work if its autoComplete prop is set to false, as described here: https://groups.google.com/g/zotero-dev/c/vKdxvZJL8UQ/m/VLqu-3VGBQAJ
The commit proposed seems to solve the issue.

Fix Input component doesn't work if autoComplete=false

---

chrome/content/zotero/xpcom/connector/server_connector.js
test/tests/server_connectorTest.js

Fixes and tests for https://github.com/zotero/zotero-connectors/issues/343

Do not send back `saveSingleFile: true` if saving a PDF snapshot.

---

scripts/build.js
scripts/config.js
scripts/sass.js
scripts/symlinks.js
scripts/utils.js
scripts/watch.js

This PR tweaks build so that scss won't rebuild unless one of the observed .scss files has changed and fixes for a potential issue where .scss files could have been symlinked into the build folder.

Skip .scss files if build not required #1944

---

chrome/content/zotero/tabs.js

This hides the tab bar on Windows and Linux, where it currently takes up a lot of vertical space below the menu bar. On macOS, the tab bar remains always shown since we don't have the menu bar and can move tabs in the window there.
Fixes https://github.com/zotero/zotero/issues/2019

Hide tab bar for single tab case on Windows and Linux

---

chrome/content/zotero/components/tabBar.jsx

Fixes https://github.com/zotero/zotero/issues/2033

Show full tab title on hover

---

chrome/content/zotero/about.xul
scss/linux/_about.scss
scss/zotero-react-client-unix.scss

Fix for issue in Report [1517701677](https://forums.zotero.org/discussion/88473/zotero-linux-dark-theme-issues)
I was unable to change the dark theme background since since XUL doesn't support prefers-color-scheme, so I made a Linux specific fix to ensure the text was visible across themes. 
Dark Theme Before/After:
Light Theme Before/After:

Made About page text visible across default Linux themes

---

chrome/skin/default/zotero/integration.css

This is another go at issue #1842. I took your suggestion about fixing the color and found that this was a simple fix if you remove the hardcoded white color of the dropdown menu. This fixes the issue in dark theme in Linux without affecting the appearance of light mode, as shown below. There's also no noticeable difference when this change is applied to the Windows build.
Original appearance in dark theme:
Fix in dark themed Linux:
Fix in light themed Linux:

Fix background color of the dropdown menu.

---

chrome/skin/default/zotero/bindings/itembox.css

[Report: 1517701677](https://forums.zotero.org/discussion/88473/zotero-linux-dark-theme-issues)
Number 1, The item type was hard coded to black therefore it did not look well when used in dark mode. I removed the hard code so now it should look nicer when using dark mode.
Before fix:
After fix:

Fix dark theme on Item Type

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/tabs.js

This hides tooltips (such as the tab title tooltip) whenever the tab bar state changes, such as when adding or removing a tab, to ensure we don't leave any tooltips behind that no longer match reality.
Additionally, this changes to `mousemove` to start the tab title tooltip, so that the behavior matches applications like Firefox more closely: you can always get the latest tooltip back after changing state by nudging the mouse (without having to exit and re-enter anything).
Fixes https://github.com/zotero/zotero/issues/2060

Hide tab title tooltips whenever the tab bar changes

---

chrome/content/zotero/import/mendeley/mendeleyImport.js
chrome/content/zotero/xpcom/file.js
test/tests/fileTest.js

Few changes to improve handling of attachment files during import via Mendeley API:
* Sanitize filenames and shorten to 255 characters
* If temporary path length would exceed 260 characters, shorten the filename to ensure that length is not exceeded. This is designed to work around limitation present in [some (probably most?) windows systems](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd). I did not limit this behaviour to be windows only but we may do that if we think it would have significant impact on imports.
* Reduce the overall length of the temporary path by using shorter prefix (`m-api` instead of `mendeley-online-import`)

Mendeley Import: improve handling of attachment files

---

chrome/content/zotero/runJS.js

The current regex doesn't seem right. Most likely there's a typo, see "intended?" below.
Here are some variants:
```
(^|[^=([]\s*)await\s  //current
(^|[=([]\s*)await\s   //intended?
(^|[=([{!]\s*)await\s //improved
(^|\W)await\s         //simpler, suggested in this PR
```
Tests: https://regex101.com/r/eQYCIp/1

Run JavaScript: Improve `await` regex

---

chrome/content/zotero/xpcom/openurl.js

There is no `isInstitution` field, so OpenURL search was producing invalid data for items with institutional authors.

Use fieldMode for creators in OpenURL

---

chrome/content/zotero/bindings/itembox.xml

After this change `activeField` is blurred just before item is saved to preserve the value entered by the user, `switchCreatorMode()` has been converted to async to allow for this.

Blur active field in switchCreatorMode. Fix #2087

---

chrome/content/zotero/xpcom/feedReader.js
resource/feeds/FeedProcessor.js
resource/feeds/SAXXMLReader.js
resource/feeds/nsIFeed.idl
resource/feeds/nsIFeedContainer.idl
resource/feeds/nsIFeedElementBase.idl
resource/feeds/nsIFeedEntry.idl
resource/feeds/nsIFeedGenerator.idl
resource/feeds/nsIFeedListener.idl
resource/feeds/nsIFeedPerson.idl
resource/feeds/nsIFeedProcessor.idl
resource/feeds/nsIFeedResult.idl
resource/feeds/nsIFeedTextConstruct.idl
scripts/config.js
test/content/runtests.js
test/tests/data/feedCDATA.rss
test/tests/data/feedMedia.xml
test/tests/data/feedRichText.rss
test/tests/feedReaderTest.js
test/tests/feedTest.js

This imports Mozilla's feed processor (which was removed from Firefox 66) to ensure Zotero's feed processing continues to function even after upgrading the platform layer.
Along with importing the feed processor, the code style has been adapted to match Zotero conventions since it's no longer maintained upstream, and it should be easier to tweak in the future that way. It has been converted away from XPCOM APIs to a module that can be loaded in a normal web content environment. 
The feed processor *.idl files are also included for interface documentation. (The comments could perhaps be folded into the code if desired, since the *.idl files here no longer serve any interface-defining purpose.)
In addition to the feed processor itself, this also adds a SAX-like XML reader based on …

Import feed processor

---

chrome/content/scaffold/scaffold.js
chrome/content/scaffold/scaffold.xul
chrome/content/scaffold/templates/shortcuts.txt

This remaps a couple keyboard shortcuts on the testing tab: Cmd/Ctrl-R will now run selected tests and backspace will delete them.

Scaffold: Run/delete tests with the keyboard

---

chrome/content/zotero/tabs.js
chrome/content/zotero/zoteroPane.js

This adds several more tab navigation shortcuts that users commonly expect to work across any program with tabs. With this PR, we now support all of the following:
* `Ctrl-PageDown` / `PageUp`
* `Cmd-Shift-[` / `]` (macOS only)
* `Ctrl-Tab` / `Ctrl-Shift-Tab`
* `Cmd` / `Ctrl-1` through `9`
Fixes https://github.com/zotero/zotero/issues/2025

Add more tab navigation shortcuts

---

chrome/content/scaffold/scaffold.js
chrome/content/scaffold/scaffold.xul
chrome/locale/en-US/scaffold/scaffold.dtd

The dropdown in the Browser tab is fine, but I find it more natural to work from the Testing tab. This makes that an option.

Scaffold: Add action to open test URL in internal browser

---

chrome/content/zotero/import/mendeley/mendeleyImport.js
chrome/content/zotero/import/mendeley/mendeleyOnlineMappings.js

This import feature was missing for Mendeley online import. Also ensure that "★" tag is added to an existing item on re-import where appropriate.

Mendeley import: Add "★" tag for favourite items

---

chrome/content/zotero/duplicatesMerge.js

Excluding by ID obscured which types were being excluded. IDs drifted and we ended up blacklisting `artwork` and `encyclopediaArticle`.
Fixes #2136.

Exclude unmergeable types by name, not by ID

---

chrome/content/zotero/xpcom/connector/server_connector.js

The call to `done()` resulted in a 500 response and prevented the connector from fetching the list of available translators.
Fixes #2134.

Fix error when connector requests translators

---

chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
test/tests/utilities_internalTest.js

Completes zotero/translators#2529 by adding support for ADS bibcodes to the Add Item(s) by Identifier box. I suppose we should also change the label in the UI (`zotero.lookup.description` in the DTDs), but I don't know how to go about doing that (since I'm assuming it involves Transifex).

Add test for ADS Bibcode extraction

---

chrome/content/zotero/contextPane.js
chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/xpcom/session.js
chrome/content/zotero/xpcom/zotero.js
chrome/content/zotero/zoteroPane.js
components/zotero-service.js

- Saves all panes state when quit is triggered (even though it's not necessary to save multiple Zotero panes at the moment).
- Saves last Zotero pane state when closing it.
- Restores last Zotero pane when Zotero application is reopened.
- Restores state when Zotero pane is reopened on macOS.
- Fixes failed-to-initialize context pane's item pane when reopening Zotero pane on macOS.
Let's see if everything looks good.

Restore tabs state

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/locateManager.jsx
chrome/content/zotero/preferences/preferences_cite.jsx
chrome/content/zotero/preferences/preferences_export.jsx
chrome/content/zotero/preferences/preferences_sync.jsx
chrome/content/zotero/progressQueueDialog.jsx
chrome/content/zotero/rtfScan.jsx

Removes `defaultRowHeight` prop added in adb8aa39f in favor of a prop
that disables font size scaling. A non-default row height can still be
specified with `rowHeight`.
Most of our existing trees need to disable font size scaling, but the
idea is that pretty much everything _should_ scale with font size for
accessibility, and it's a limitation of the current prefs and other UIs
that they don't currently, so it's better to default to scaling and
gradually remove uses of this prop.
This fixes a bug where the HTML trees other than the collection and item
trees would have larger rows but without larger text when font size was
increased.

Add `disableFontSizeScaling` prop to HTML tree

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/locateManager.jsx
chrome/content/zotero/preferences/preferences_cite.jsx
chrome/content/zotero/preferences/preferences_export.jsx
chrome/content/zotero/preferences/preferences_sync.jsx

Closes #2168, closes #2169.
Adds find-as-you-type to locate, preference style and export
formats managers.
To enable find as you type you need to specify the getRowString(index) prop
on the VirtualizedTable. See prop comment for more info.

HTML Tree: make find as you type a virtualized table functionality

---

chrome/content/zotero/import/mendeley/mendeleyOnlineMappings.js
test/tests/data/mendeleyMock/items-simple.json
test/tests/mendeleyImport.js

This is a fix for #2236. Mendeley online schema uses "arxiv", local DB uses "arxivId" hence it was skipped. This commit adds missing mapping and a test.

Fix arXiv ID not imported. 

---

chrome/content/zotero/xpcom/data/feed.js
test/tests/feedTest.js

This prevents metadata changes from clearing the `isRead` status of feed items as long as GUIDs remain constant. Previously, feed items with randomized properties (like URLs generated dynamically each time the feed is served) would be incorrectly marked as unread on every update.
Fixes #2213.

Don't reset isRead when feed item metadata changes

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/standalone/basicViewer.xul

There are two commits: first one tweaks the URL regexp to be more precise - not really needed, just a precaution since there are arbitrary pages involved in institutional login and some of them might have URL that matched the old regex.
Second commit changes browser `type` attribute in `basicViewer`. Documentation that I've found isn't very clear on what's the difference but it seems to resolve the issue with loaded pages accessing `window.top`. I've run a sanity spot check on few places that use `basicViewer` and it seemed fine but we may want to make this configurable/copy if we're concerned?

Mendeley import institutional login fix

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/icons.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/collectionTreeRow.js
chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/zotero.properties

Addresses all points of #2261
Some notes:
> 4\. When a list is selected, it says "table" instead of "tree view".
I've set the roles for the trees where appropriate to either 'tree' or 'treegrid'. 'treegrid' is announced as table, tree, grid or others depending on screen reading software
> 6\. The item type, colored tags, and non-matching (gray) rows aren't indicated in any way. They should probably be read before or after the title. E.g., "book The Great Gatsby", "non-matching book The Great Gatsby", "book The Great Gatsby tag Class". We'll talk to some people to figure out the best approach here, but getting them into the row would be a good start.
I've added something to address this, but it's not ideal. If you have Item Type column, the item type is read twice, even though i set …

Improve tree screen reader accessibility

---

scss/components/_autosuggest.scss

Fix autosuggestion background color in dark mode

---

chrome/content/zotero/xpcom/reader.js
chrome/locale/en-US/zotero/zotero.properties

The tag and color selector can be tested now. Some issues to discuss:
1) There is no a convenient way to clear the filter. A separate button would be good, but I'm not sure where to put it. Alternatively it could be in context menu as it is in the original tag selector.
2) When filtering is active, some actions like annotation creation or selection become complicated because you no longer see it in the sidebar. Maybe a better indication that filtering is active would be useful, especially in those cases when only a color is selected, because it might be difficult to notice.
3) The final element that is necessary for this workflow is "Select all annotations" button. Or should it also be in context menu?

Add color and tag selector to annotations sidebar

---

chrome/content/zotero/components/progressQueueTable.jsx
chrome/content/zotero/progressQueueDialog.jsx
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/progressQueue.js
chrome/content/zotero/xpcom/progressQueueDialog.js

This PR decouples progress queue table into a separate React component. It also tweaks progress queue so that it supports  multiple listeners. Few places that used `removeListener` on progressQueue have been updated to specify which listener should be removed and I've added a deprecation note.
I've came up with this as part of #2311 but I think it's a good PR on it's own. Merging it now will also help avoid potential future conflicts.

Decouple progress queue table from progress window

---

chrome/content/zotero/components/icons.jsx

a1267bc fixed repeated re-appending of `'@2x'` by moving the modified URL to a local variable, but it still set `hasHiDPI` to false permanently; this meant that icons displayed repeatedly in the same window, like the tab close button, would only use their 2x versions the first time they were displayed (in the case of tabs, this is the library tab's invisible close button, so *no* tabs got visible 2x buttons).
This commit moves the HiDPI check and URL modification out of the render function and instead runs it a single time when `i()` is first called.
Before (upscaled 1x tab close button):
After:

Fix React icons only using 2x image once

---

chrome/content/zotero/xpcom/file.js

This PR should fix an issue with relative paths of linked file attachments in the latest Zotero beta.
- (These steps are for Windows, but this can be reproduced on Linux if adapted.)
- Set the Linked Attachment Base Directory: `C:\Temp`
- Add a linked file attachment: `C:\TempABC\123.pdf`
- Try to open it.
- This results in a "File Not Found" prompt:
> The attached file could not be found at the following path:
> 
> C:\Temp\BC\123.pdf
> 
> It may have been moved or deleted outside of Zotero, or a Linked Attachment Base Directory may be set incorrectly on one of your computers.
Within `Zotero.Attachments.getBaseDirectoryRelativePath(path)` ([here](https://github.com/zotero/zotero/blob/b865ee8b65c0f24eaad6d3123706b14e3dfff65e/chrome/content/zotero/xpcom/attachments.js#L2401-L2428)), the …

Improve `directoryContains()`

---

chrome/content/zotero/xpcom/editorInstance.js
chrome/locale/en-US/zotero/zotero.properties

As discussed in #2284, this is an experimental PR that allows to add/remove citations that are immediately after annotation. Citations in other places or multi-item citations are untouched.
It now also shows a title with formatted citation when hovering a highlight or image annotation.
For now the default behavior (whether to show colors or citations, or not) is not changed and it also doesn't remember the last setting yet. Firstly let's try this out and make sure actually adding/removing citations is the right way to go.
It actually feels much cleaner without citations.

Allow to add/remove citations in notes

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/data/items.js

`_renderItemTitle` attempts to follow the behavior of citeproc-js as closely as possible, including two major quirks:
1. Unmatched tags are included as text content in the rendered title. For example, `<i>x<sup>2</i>` is rendered as <i>x\<sup>2</i> and `<i>x</i></i>` is rendered as <i>x</i>\</i>.
2. When `<i>` or `<b>` is nested inside another tag of the same type, the inner tag inverts the outer. For example, `<i>Reading the <i>Odyssey</i> Today</i>` is rendered as <i>Reading the</i> Odyssey <i>Today</i>.
Closes #1396.

Render markup in item tree, strip when sorting

---

chrome/content/zotero/xpcom/reader.js

As discussed in #1986.
It took a lot of time and there were many difficulties to implement this. Each focus zone has its own nuances. Basically a virtual focus layer was implemented. I tried to keep things as simple and as maintainable as possible, but the way how it works is still not perfect and will need a partial rewrite when we migrate to a newer PDF.js, or new UI elements will be introduced.
So this is what was implemented:
- Sidebar search input is now fixed to the top.
- Toolbar navigation.
- Findbar navigation.
- Sidebar view buttons navigation.
- Page thumbnails navigation.
- Outline navigation (Enter to fold/unfold)
- Annotations navigation and selection that respects the current filter.
- Annotation widget navigation.
- Page label updating popup navigation.
- Tag and color …

Implement custom keyboard navigation

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
scss/components/_virtualized-table.scss

Closes #2373.
As a result of this after changing the collection the first row always has the pivot border. I don't think it's a big problem and that's how it always was on Window or Linux, but you may think it to be unusual or distracting, so your call on how/whether we address that.

HTML Tree: Add a dotted border to pivot rows

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx

This fixes a bug that caused the item tree to scroll to the very top if you focused it without selecting an item, e.g. by clicking on an item's twisty while focus is outside the tree.

Fix item tree jumping to top on focus without selection

---

chrome/content/zotero/xpcom/editorInstance.js
chrome/content/zotero/xpcom/reader.js

This can be tested now. Works with dragging and copying.
Although it doesn't change "Copy" to "Copy Note" in Edit menu because:
1) It's not only about notes. Copied annotations can be pasted into note-editor as active annotations.
2) Unclear when exactly "Copy" should be changed to "Copy Note". I guess it would need to track when focus switches between pdf-reader and note-editor. It might not be easy to do that.
#2289.

Allow to Quick Copy annotations

---

chrome/content/zotero/zoteroPane.js

This happens a lot during tests - `library.lastSync` is null, so `showAutoSyncReminder()` throws. It doesn't fail tests but it does spam the log.

Fix log spam when library hasn't been synced

---

chrome/content/zotero/bindings/noteeditor.xml
chrome/content/zotero/components/itemPane/notesList.jsx
chrome/content/zotero/contextPane.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul
scss/abstracts/_split-button.scss
scss/components/_notesList.scss

Let's try this out.
- Toolbar navigation is now continuous.
- Improved notes list navigation.
- Toggling Item/Notes split button focuses context pane, even when doing so with mouse (which is not necessary good).
#2379

Improve keyboard navigation in PDF reader tab

---

chrome/content/zotero/xpcom/data/items.js
test/tests/itemsTest.js

Now it:
1. Strips punctuation at the beginning, no matter what it is.
2. Strips non-dash punctuation in other positions.
3. Trims the result.
This should better prevent numerical ranges from being joined into a single number that ends up incorrectly being sorted to the very bottom.
Fixes #2427

`getSortTitle`: Strip less punctuation, trim

---

chrome/content/scaffold/scaffold.js

Addresses #1894. Not a fix since it doesn't touch tests - this only changes the way items are displayed when you run a translator manually inside Scaffold (Cmd/Ctrl-R). I'd like to make tests use the same sanitized form, but `translate` code doesn't have access to the `Zotero.Utilities.Internal` methods that are essential here, so it would break `testTranslators.html`, which would break CI translator testing.

Scaffold: Sanitize items for display more accurately

---

chrome/content/zotero/import/citavi.js
test/tests/data/citavi-test-project.ctv6
test/tests/fileInterfaceTest.js

Instead of attempting to extract `PageRange` value we now let pdf-worker always determine page label.
Also improved citavi tests and fixtures.

Citavi import: Tweak how page label is determined

---

chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/standalone/standalone.xul
chrome/content/zotero/xpcom/reader.js
chrome/locale/en-US/zotero/zotero.dtd

This is a confusing, bad option, which was already disabled in groups,
and this removes it from personal libraries as well. People seem to be
using it mainly because they think annotations are locked into Zotero if
they don't, which is causing them to ask for this to be done
automatically on every edit, which we don't do because it would result
in constant file syncing and file conflicts [1].
We provide multiple export options for exporting PDFs with annotations,
and people can use those when sharing a file with people who don't use
Zotero. Otherwise, if storing annotations in the file is a priority,
they can use an external reader that's not designed to be tightly
integrated into Zotero.
(As a rare hack, it's of course also possible to export the PDF with
annotations, replace the …

Remove "Store Annotations in File" option

---

chrome/content/zotero/standalone/standalone.xul

Hides one of the two separators above Preferences:
`menu-type-library` would automatically show the `menuseparator` in the library tab, but the `textfieldDirection-swap` menuitem below it is never shown (and currently seems to be unused).

Fix double separator in Edit menu on Win/Linux

---

chrome/content/zotero/bindings/itembox.xml

This handles all the cases that were being missed before: tabbing out of the field (`change` doesn't reliably fire anymore...), clicking on an option in the autocomplete list, and clicking on another field/out of the itembox entirely. The `ontextentered` and `onchange` handlers added in `showEditor` are still necessary; this is a fallback.
Fixes #2515.

Always autocomplete creators in `hideEditor`

---

chrome/content/zotero/components/virtualized-table.jsx
scss/components/_virtualized-table.scss
scss/mac/_virtualized-table.scss

Closes #2381, closes #2450
A slight rethinking to the way row heights are specified for the item tree. They will now be specified in multiples of lines of text we expect to render for whatever the CSS and then OS-level font-scaling expected rendered font size for the tree rows is. The default is 1 line of text per one row. This is required to deal with OS-level font-scaling. A side effect of this is that row-heights may be slightly different for different font-sizes (as chosen in the Zotero interface) when compared to before with the XUL tree. I've also set a minimum row height of 20px. Tested on all platforms and looks fine to me.

Item Tree: Attempt to fix OS font scaling

---

chrome/content/zotero/itemTree.jsx

If a call number looks like Dewey (begins with three digits, then optionally a dot and one to four digits, then optionally a slash and three letters), we split it into parts and sort each using string comparison in order to get [this ordering](https://www.mdek12.org/sites/default/files/Offices/MDE/OA/OEER/Library%20Services/Section%206/Dewey%20Decimal%20Classification%20(1).pdf).
If it doesn't, we still sort using string comparison - locale collation will treat them like cardinal numbers, which I think isn't appropriate in many cases.
Fixes #2194.

Sort call numbers alphabetically, handle Dewey specially

---

chrome/locale/en-US/zotero/zotero.properties
chrome/skin/default/zotero/report/detail.css

Currently only row/column insertion/deletion is supported. Probably no need to hurry with advanced features like merging/splitting cells, setting table header.
I took some inspiration from Google Docs for the table context menu.
You will probably see displaced table resizing handles, the first time when you open a note with table and focus the table. That's Firefox bug, and resizing handles are completely disabled from Firefox 64. That might be very time consuming to work around, therefore I'm leaving this unfixed. Maybe we could do something with prefs…
Fixes #2480

Allow creating and editing tables in note-editor

---

chrome/content/zotero/xpcom/data/items.js
test/tests/itemsTest.js

Removes:
- Any punctuation of any type at the beginning of the string besides @, #, and *, including the *same character* repeated multiple times. So `-- title` would become `title` but `-_ title` would become `_ title`.
- Any [opening punctuation](https://www.fileformat.info/info/unicode/category/Ps/list.htm) or neutral quotes immediately following it.
I think this has a better balance between removing non-meaningful characters in titles, preserving meaningful ones (like the @ example in the forum thread), and letting people use title hacks if they really, really want to.
See test cases for some examples. Includes a test which sorts the examples given in the thread.
Fixes #2535.

getSortTitle: Only strip initial punctuation clusters

---

chrome/content/zotero/itemTree.jsx
test/tests/utilities_itemTest.js

Not strictly "correctly," due to the issues mentioned [here](https://github.com/zotero/zotero/issues/2567#issuecomment-1108819863), but in a way that handles the classification field correctly.
Fixes #2567, fixes #2570.

Sort LC call numbers better, sort integers as integers

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/tabs.js
scss/components/_tabBar.scss

The only nuance is that it's getting the current collection icon in [a hacky way](https://github.com/zotero/zotero/compare/master...mrtcode:pin-library-tab?expand=1#diff-014a38101f2c50e35e6714dcee641532b66acde664b882a6ad87446cb62a6cc4R204-R208).
Fixes #2575

Pin library tab

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/itemTreeColumns.jsx
chrome/content/zotero/zoteroPane.js
scss/components/_virtualized-table.scss

A slight redesign of the column resizing code which restores previous XPCOM tree behavior:
- Previous code calculated and stored column widths based on item tree width. This meant that if you resized the item tree (or Zotero window) the column widths would get recalculated. Making the tree wider and narrower repeatedly would cause rounding errors to accumulate and all column widths to drift towards equal width. This code instead stores all column widths normalized to item tree width of 8192 and no recalculation is ever done when resizing the tree.
- Fixed column width calculation code to be more robust on macOS and not have the column separators get out of sync between the header and cells.
Would be good to see some testing before merging in case I missed something.
Closes #2587. …

Improve column resizing robustness

---

scripts/browserify.js
scripts/build.js
scripts/copy.js
scripts/js.js
scripts/sass.js
scripts/symlinks.js
scripts/utils.js
scripts/watch.js

* Fix a bug that would trigger `scss` files build on other changes
* Fix a problem with `.css` files appearing outside of `build/` folder when switching from `master` to `fx102` branch. See commit for convoluted reasons this was happening
* Run `add_omni_file` script when source change is detected (**DEPENDS ON** zotero/zotero-standalone-build/pull/98)
* Ring the bell on error.

Fx102 improve build

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/data/item.js
test/tests/itemTest.js

In the process, simplified sorting and displaying attachment states a fair amount by making `getBestAttachmentState` treat the item it's called on as the "best attachment" when called on an attachment item. That removed the need for duplicate logic to determine attachment icons for standalone attachments and even more duplicate logic to figure out sort positions.
1. Is that a reasonable change?
2. And if so, should `getBestAttachment` and `getBestAttachments` also support attachment items?
Fixes #2416.

Fix sorting by attachment

---

chrome/content/zotero/platformKeys.js
chrome/content/zotero/zoteroPane.xhtml

Not able to test on non-Mac yet, but this behavior should be right. Removes all the #ifdefs and moves the behavior into platformKeys.js.

fx-compat: More progress on platform menus

---

chrome/content/zotero/advancedSearch.js

Fixes a (longstanding?) issue that causes a search in a feed that hasn't yet been loaded (clicked on in the library tree) to fail.

Advanced Search: Make sure items are loaded

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/data/items.js
test/tests/itemTest.js
test/tests/itemTreeTest.js

- On trash empty, ItemTree was removing only the rows corresponding to items that _weren't_ deleted, not the ones that were. That led to a bunch of gray rows left in the trash after emptying.
- `Zotero.Items.emptyTrash` didn't send a refresh trash notification after the operation finished, so CollectionTree didn't know to refresh.
- Emptying the trash needs, but wasn't getting, a full CollectionTree refresh - it needs to fetch deleted items for each library and potentially add/remove the trash row if the `showTrashWhenEmpty` pref is false.

Empty Trash: Visually remove deleted items, refresh icon

---

chrome/content/zotero/import/citavi.js

This PR contains few improvements to Citavi annotations importer:
* Fixed an issue where sometimes `getXML()` would throw an error because file stream was already closed after translator has finished running
* Added few extra checks so that import continues if a single annotation cannot be imported or processed.

Improve Citavi annotations importing

---

chrome/content/zotero/zoteroPane.js
test/tests/zoteroPaneTest.js

Fixes #2796. This clears the abstract in both directions - it doesn't often seem sensible to copy the abstract from a section to the whole book either.

`duplicateAndConvertSelectedItem`: Don't copy abstracts

---

chrome/content/zotero/xpcom/attachments.js

Fixes "Find Available PDF" showing in the context menu inside feeds. Actually selecting it just shows a "cannot make changes to the selected collection" alert. The issue also occurs on master and I can cherry-pick to there if this is merged.

Hide "Find Available PDF" for feed items

---

chrome/content/zotero/import/mendeley/mendeleyImport.js
test/tests/data/mendeleyMock/annotations.json
test/tests/mendeleyImportTest.js

`rgb(255, 245, 173)` -> `#ffd400`
`rgb(255, 181, 182)` -> `#ff6666`
`rgb(186, 226, 255)` -> `#2ea8e5`
`rgb(211, 194, 255)` -> `#a28ae5`
`rgb(220, 255, 176)` -> `#5fb236`
Other colors preserved. Didn't do anything about "empty" color as this will be taken care at data layer (#2818).
Resolves #2819

Map Mendeley annotation colors to equivalent Zotero colors on import

---

chrome.manifest
chrome/content/zotero/standalone/basicViewer.js
chrome/content/zotero/standalone/basicViewer.xhtml
components/zotero-protocol-handler.js

- The protocol can no longer be marked "dangerous to load," only "UI resource" (accessible inside browsers but not by web pages).
- The protocol needs to run in the main process.
- We need to replace the XUL browser to reset its type attribute depending on whether we're loading a `zotero` protocol URI - `zotero` protocol URIs, maybe due to the protocol handler's tight coupling with the main process, cannot load in type="content" browsers. (Not sure what the exact issue is. We don't get any helpful log messages - `zotero://` URLs just get handed off to the OS.)

fx-compat: Fix `zotero://` protocol for reports

---

chrome/content/zotero-platform/mac/preferences.css
chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences.xhtml
chrome/content/zotero/xpcom/preferencePanes.js
chrome/locale/en-US/zotero/preferences.dtd
chrome/skin/default/zotero/preferences.css

Having the macOS Help button in a scrolling view feels kind of weird, but that's what Apple is doing in the Ventura System Settings app, so I guess we go with it. I like it better than Firefox's non-contextual "Firefox Support" button under the pane list in their preferences, anyway - having pane-by-pane contextual help buttons seems like good UX that there isn't a good reason for us to ditch.

Preferences: Restore Help button

---

chrome/content/zotero-platform/mac/overlay.css

Before:
After:
(Both upscaled.) The rightmost tab was pushed too far up before and this change corrects its position. Can be cherry-picked to master too.

Fix last editpane tab being misaligned vertically on macOS

---

chrome/content/zotero/xpcom/intl.js

Fixes #2837: FTL files can be included with `<link>` tags in pane XHTML fragments without manual configuration.

fx-compat: Automatically register plugin l10n sources

---

chrome/content/zotero/preferences/preferences_sync.jsx
chrome/content/zotero/zoteroPane.js
test/tests/preferences_syncTest.js

It would be nice if `preferences.js` could just send an `unload` (or `beforeunload`) event to panes like it does with `load`, but it seems that, at least on macOS, the interpreter won't dispatch events from a [`before`]`unload` handler. So for now, at least, panes need to add their own listeners to the window.
Also fixes an existing error due to an argumentless call to `Zotero.Sync.Runner.updateIcons()` in ZoteroPane.
Fixes #2785.

Clear sync error and start sync after logging in in prefs

---

chrome/content/zotero/xpcom/connector/httpIntegrationClient.js
chrome/content/zotero/xpcom/integration.js

Merges adjacent citations on document refresh. Need to use the corresponding [zotero-standalone-build branch](https://github.com/zotero/zotero-standalone-build/tree/merge-adjacent-citations) for word processor code.
The current connector master branch contains support for GDocs V2. The V1 also has support, but the apps script code has to be deployed for testing.
Closes #1825

Adds support for merging adjacent citations

---

chrome/content/zotero/elements/zoteroSearch.js
chrome/content/zotero/xpcom/data/search.js
chrome/content/zotero/xpcom/data/searchConditions.js
chrome/locale/en-US/zotero/zotero.properties

I'm not hugely enthused by how I ended up having to implement this - we didn't seem to have a good way to add compound conditions like "Any Field" that expand at query time instead of when initially being added, so I had to tack something onto the main loop in `_buildQuery()`. If there's a better way that I missed, I'll change it!
Fixes #1699

Add "Any Field" advanced search condition

---

chrome/content/zotero/tools/csledit.js

Lines that fail validation are highlighted, and hovering shows you the error:
Errors are also marked in red under the scroll bar so you can quickly scroll to the offending line.

fx-compat: Style Editor: Validate CSL inline

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/import/importWizard.js
chrome/content/zotero/import/importWizard.xul
chrome/content/zotero/import/mendeley/mendeleyAPIUtils.js
chrome/content/zotero/import/mendeley/mendeleyImport.js
chrome/content/zotero/import/mendeley/mendeleyOnlineMappings.js
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
chrome/skin/default/zotero/importWizard.css
test/tests/data/mendeleyMock/items-simple-no-desktop-id.json
test/tests/data/mendeleyMock/items-updated.json
test/tests/mendeleyImportTest.js

As discussed, this approach pretends to be Mendeley Desktop and performs login directly using username and password obtained from the user via form. Signing in this way ensures that Mendeley servers include extra key for documents (`client_data`) which contains Mendeley Desktop UUID. Storing this UUID makes #2622 possible.

Mendeley Import: Switch to direct login/password auth in order to obtain Mendeley Desktop item id

---

chrome/content/zotero/advancedSearch.js
chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/containers/tagSelectorContainer.jsx
chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/itemTreeColumns.jsx
chrome/content/zotero/xpcom/collectionTreeRow.js
chrome/content/zotero/xpcom/data/feeds.js
chrome/content/zotero/xpcom/data/itemFields.js
chrome/content/zotero/xpcom/data/search.js
chrome/content/zotero/xpcom/data/searchConditions.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
test/tests/collectionTreeTest.js

Feeds row appears bold when any feed has unread items, and it can be collapsed like a library (partially for users who don't want to see their feed list all the time and prefer just using the new global view, and partially as a visual clue that something has changed).
Closes #2786.

Make Feeds row into a selectable global view of feed items

---

chrome/content/zotero/locateMenu.js
chrome/content/zotero/preferences/preferences_general.js
chrome/content/zotero/preferences/preferences_general.xhtml
chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/preferences.dtd
chrome/locale/en-US/zotero/zotero.properties
defaults/preferences/zotero.js

When enabled:
- Double-clicking a PDF or choosing "Open PDF" opens a new window
- Shift-double-clicking opens a new tab
- "Open in New Window" locate option becomes "Open in New Tab" and has the reverse behavior
Fixes #2680

Add "Open PDF reader in new window" preference

---

chrome/content/zotero/bindings/itembox.xml

I don't think this piece of code does what it says in this [14 years old comment](https://github.com/zotero/zotero/blame/13ab3de1a180424eb1614326c94feefc90ddb645/chrome/content/zotero/bindings/itembox.xml#L619). I believe that instead it is re-focusing on the `lastTabIndex` on every item box refresh. We don't want that because that's what's triggering #2885.
We do however want to re-focus after item box has been refreshed due to field change, I believe that relevant code for that is instead [this](https://github.com/zotero/zotero/blame/13ab3de1a180424eb1614326c94feefc90ddb645/chrome/content/zotero/bindings/itembox.xml#L1511-L1519).
Unless there is some use case I'm not aware of, I think we can just remove these few lines and that should resolve #2855.

Fix focus stealing in item box #2885

---

chrome/content/zotero-platform/mac/overlay.css
chrome/content/zotero/elements/menuToolbarbutton.js

- Don't rely on `Zotero.hiDPISuffix` being initialized in `menuToolbarbutton.js` -- it probably hasn't been at the time that the code that creates the dropmarker is running. This fixes toolbar buttons never using the hiDPI dropmarker icon on fx102.
- Fix merge mistake that created a duplicate block of CSS.
I think we'd benefit from eventually replacing most of the code that checks `hiDPI`[`Suffix`] with CSS so that images update automatically when moving the window between displays with varying pixel densities, but that's another PR.

fx-compat: Toolbar fixes

---

chrome/content/zotero/import/importWizard.js
chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/prompt.js
chrome/locale/en-US/zotero/zotero.properties
components/zotero-service.js
defaults/preferences/zotero.js

- Adds a `Zotero.Prompt` interface and simplifies `Services.prompt.confirmEx()`. It's a pain having to work with `confirmEx()` since there's no in-code documentation and the old Firefox documentation isn't even available on MDN, and the function signature is complicated by flags and such. This PR fixes that. `Zotero.Prompt` can be further extended as needed and existing calls to `Services.prompt.confirmEx()` can be replaced gradually.
- Adds a prompt when performing an integration operation and an unlinked Mendeley citation is detected, suggesting the user to (re)import their Mendeley db.
* If user clicks skip, the prompt is skipped until Zotero is restarted for that document (but occurs for other docs)
* If user checks "Don't ask again" checkbox, the prompt is disabled forever
* If user …

Prompt to import mendeley

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/import/importWizard.js
chrome/content/zotero/import/importWizard.xul
chrome/content/zotero/import/mendeley/mendeleyImport.js
chrome/content/zotero/xpcom/integration.js
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.properties
chrome/skin/default/zotero/importWizard.css
test/tests/mendeleyImportTest.js

New option only appears if importer version is < 1 or not present. It will:
- Skip fetching collections and attachments
- Skip adding any new items
- Update relations on existing imported items so that `mendeleyDB:documentUUID` stores Mendeley Desktop ID and thus can be recognized in a word processor document.

Add option to Mendeley importer to only relink items

---

chrome/content/zotero/bindings/attachmentbox.xml

This is an unexpected behavior. Although the control cannot provide context menu, I don't want it to be opening the url.

stop opening while right click on attachment's url

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/annotation.jsx
chrome/content/zotero/components/button.jsx
chrome/content/zotero/components/createParent/createParent.jsx
chrome/content/zotero/components/progressQueueTable.jsx
chrome/content/zotero/components/tagSelector/tagSelectorList.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/containers/tagSelectorContainer.jsx
chrome/content/zotero/contextPane.js
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/locateManager.jsx
chrome/content/zotero/preferences/preferences_cite.jsx
chrome/content/zotero/preferences/preferences_export.jsx
chrome/content/zotero/preferences/preferences_sync.jsx
chrome/content/zotero/preferences/preferences_sync.xul
chrome/content/zotero/rtfScan.jsx
chrome/content/zotero/xpcom/intl.js
chrome/locale/en-US/zotero/preferences.dtd
test/tests/intlTest.js

Strings from .dtd files are now accessible from Zotero.getMessage as the eventual move to Fluent would remove their distinction.
Throws if there are duplicate string ids between .dtd and .properties files

Refactor l10n code. Remove use of react-intl.

---

chrome/content/zotero/xpcom/reader.js
defaults/preferences/zotero.js

- Added `zotero.tabs.title` pref (just like Firefox has), but if we don't expect to have more prefs under `zotero.tabs` group, we could have a different name.
- The pref is not only for PDF tabs, but for all future tab types as well. At least for what the reader provides. Maybe except note tab, if we'll ever do it.
- The pref supports two options: `title`, `creatorYearTitle`.
- The pref will only have an effect if the current PDF file is the "best" attachment, otherwise tab title will be an attachment filename.
- The default option now is 'title' (previously we were displaying `Title - Creator - Year`).
- After changing the pref, unloaded tabs won't be updated until selected, because of technical limitations. If we think this is too annoying we can try to work around that.

Add a hidden pref for tab title with support for Creator-Year-Title option

---

chrome/content/zotero-platform/unix/overlay.css
chrome/content/zotero/bindings/itembox.xml
chrome/content/zotero/bindings/relatedbox.xml
chrome/content/zotero/components/itemPane/tagsBox.jsx
chrome/content/zotero/lookup.js
chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/xpcom/sync/syncRunner.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xul
chrome/skin/default/zotero/overlay.css

I made the toolbar accessible to the keyboard. There are two sections, one before and one after the search bar. When you tab into a section you can move around with the arrow keys to select an appropriate button. The code listenes on two toolbarbuttons per section, one at the start and end, to determine from which direction the user's focus originates.
The sync button does not have a meaningful label for screen readers, but the other toolbarbuttons do.

Made toolbar accessible to keyboard

---

chrome/content/zotero-platform/mac/zotero.css
chrome/content/zotero/feedSettings.xhtml
chrome/skin/default/zotero/zotero.css

The dropmarker had to be replaced - the built-in `<dropmarker>` tag (which is now a custom element) now uses CSS `appearance:` and overflows its bounds, so getting text to align along its middle in a cross-platform way isn't straightforward. We should either copy the dropmarker image used in older Firefox or find something new (which could be the menu dropmarker image this is using now - at least on Mac that appearance is consistent with "disclosure triangles" in Cocoa apps).
Includes a new `.form-grid` utility to replace our most common use of the now-nonfunctional `<grid>` tag: a two-column form layout with a left column for labels (fits content width) and a right column for fields (takes as much width as possible).

fx-compat: Fix adding/editing feeds

---

chrome/content/zotero-platform/unix/standalone/menuOverlay.xul
chrome/content/zotero-platform/win/standalone/menuOverlay.xul

The default keyset on unix and windows does not include the keybinding for exiting the application. On macos this works as expected because the keybinding is included in the macos keyset. This pull request adds the appropriate keybinding for the other platforms as well.

modified standalone keyset to include the quitApplication keybinding

---

chrome/content/zotero/import/mendeley/mendeleyImport.js
test/tests/data/mendeleyMock/items-empty-creators.json
test/tests/mendeleyImportTest.js

It does not appear to be possible to create a creator with no values in Mendeley, however we got reports of these causing the imports to fail. This tweak makes the importer more resilient by discarding empty/invalid creators.
I believe this is a fix for https://forums.zotero.org/discussion/comment/429834/#Comment_429834 (though I was only able to reproduce that using mocked data)

Mendeley importer: Fix issue with empty creators

---

chrome/content/zotero/import/mendeley/mendeleyImport.js
test/tests/data/mendeleyMock/items-bad-data.json
test/tests/data/mendeleyMock/items-simple.json
test/tests/mendeleyImportTest.js

This is a fix for a problem with Mendeley API returning empty string tags (https://forums.zotero.org/discussion/comment/430106/#Comment_430106)

Mendeley importer: Fix issue with empty tags

---

chrome/content/zotero/integration/quickFormat.js

Closes #3024
I'm submitting this as a PR because I feel like maybe this might break some other search? We're only matching by author, title and date and the combinations I've tried to test all returned what I expected, so maybe it's just fine.

Sorts first-author last name matches first when year present.

---

chrome/content/zotero-platform/win/overlay.css

Before:
After:
See gray border to the left of the New Collection button and to the right of the Sync button in the Before screenshot. It doesn't look right, and the commit message (61684d88992ea95f38f96fb971a53d201a6d3bf9) implies that it wasn't intentional.

Don't add border to the top/sides of the toolbar on Windows

---

scss/win/elements/_itemBox.scss

Active:
Inactive:
We can't make this only affect >= 11, unfortunately - see comment in the SCSS.
Fixes #3050

fx-compat: Item box: Use custom text field styles on Windows

---

scss/components/_tabBar.scss
scss/mac/_tabBar.scss

This isn't an fx102 regression, but it keeps bothering me and now seems like an alright time to try an idea for a fix.
Before:
No dark border on the left.
Dark border until halfway through the Sync button.
After:
Dark border throughout.

Tab bar: Make bottom border span the whole window

---

chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences.xhtml
chrome/content/zotero/preferences/preferences_advanced.js
chrome/content/zotero/preferences/preferences_advanced.xhtml
chrome/content/zotero/preferences/preferences_export.xhtml
chrome/skin/default/zotero/preferences.css

- Replace the XUL-based root preferences layout elements with `display: flex` equivalents. Reasoning:
- Access to more CSS properties allowing control over resizing behavior (like `flex-shrink`)
- More predictable layout behavior: `-moz-box` descendants of `flex` elements behave better than `flex` descendants of `-moz-box` elements
- Allow panes to shrink when the window is too small
- A few long control rows in the Advanced pane required markup changes so their labels could wrap
- Fixes #3070
This shouldn't break existing panes - they can continue to use `-moz-box`-based layouts, as all of our panes do, at least until the XUL box model is removed in a future Firefox version. Panes that use the `virtualized-table-container` utility class **will**, however, have to set a `height` or …

fx-compat: Lay out preferences window with flexbox

---

chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences_advanced.xhtml
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/standalone/basicViewer.js
chrome/content/zotero/xpcom/zotero.js

This focuses but does not reload the existing viewer if it finds a match; it seems likely, for instance, that you don't want to lose your place in the Config Editor window if you left it open in the background. If you actually want to reset the window, you can close it before performing the action that opens it again.

Basic viewer: Open separate windows per URI

---

chrome/content/scaffold/scaffold.xhtml
chrome/content/zotero/advancedSearch.xhtml
chrome/content/zotero/customElements.js
chrome/content/zotero/elements/guidancePanel.js
chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/elements/zoteroSearch.js
chrome/content/zotero/feedSettings.xhtml
chrome/content/zotero/ingester/selectitems.xhtml
chrome/content/zotero/note.xhtml
chrome/content/zotero/preferences/preferences.xhtml
chrome/content/zotero/reader.xhtml
chrome/content/zotero/searchDialog.xhtml
chrome/content/zotero/selectItemsDialog.xhtml
chrome/content/zotero/zoteroPane.xhtml

Having a single `customElements.js` file that we import everywhere we need it helps with organization, and it gives us a single place to put things like the `<tab>` fix.
We could switch to using `setElementCreationCallback()` like Firefox if the number of imports gets out of hand, but the overhead right now should be small.

fx-compat: Fix <tab> keyboard nav, move CE imports to single file

---

chrome/content/zotero/preferences/preferences_cite.jsx
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/reportInterface.js
chrome/content/zotero/standalone/basicViewer.js
chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/xpcom/zotero.js
chrome/content/zotero/zoteroPane.xhtml

And:
- Prevent JavaScript inside notes from executing in reports
- Update calls to `openInViewer()` to pass an options object

Allow disabling JavaScript in basic viewer

---

chrome/content/zotero/about.xhtml

Showing a titleless window and hiding it in the Window menu is in line with the behavior of Mail, TextEdit, and Firefox, but not Finder (which sets a title and shows it in the Window menu).
Fixes #3103.

Hide About window in Window menu (Mac)

---

chrome/content/zotero-platform/mac/itemPane.css
chrome/content/zotero-platform/unix/itemPane.css
chrome/content/zotero/elements/splitMenuButton.js
chrome/content/zotero/itemPane.js
chrome/content/zotero/xpcom/utilities_internal.js
chrome/content/zotero/zoteroPane.xhtml
chrome/skin/default/zotero/itemPane.css
chrome/skin/default/zotero/overlay.css
test/tests/itemPaneTest.js

Just a whole series of weird issues, mainly with XUL, to work around here:
1. XUL button text can't wrap or be ellipsized, and overflows the button unless `overflow: hidden` is set
2. Setting `overflow: hidden` apparently breaks clicking
3. flexbox might work better, but all attempts to use flexbox inside a XUL button are doomed to fail because of native UI control rendering magic
So we replace the XUL button with an HTML button-based CE that uses flexbox, but
4. XUL menus directly within a flex container (like our HTML button-based CE) can't be shown
5. Adding a wrapper element to serve as the flex container around the icon, text, etc., creates even more layout issues
So we add support for a `popup` attribute to `showNativeElementPopup()` and move the popup outside of the button, keeping …

fx-compat: Fix feed button appearance/overflow behavior

---

chrome.manifest

By using the `@mozilla.org/browser/clh;1` contract. Our `@mozilla.org/commandlinehandler/general-startup;1?type=zotero` handler was still getting called, but seemingly only after all the arguments had already been eaten by other handlers.
Fixes #2737

fx-compat: Handle files opened via OS

---

chrome/content/zotero/xpcom/zotero.js
chrome/locale/en-US/zotero/zotero.properties

Zotero for Firefox is no longer relevant, since even someone still using it couldn't be using it with the same database as Z7, and "Firefox with the Zotero extension" reads like it's talking about the current Zotero browser extension.

Remove outdated startup error messages

---

chrome/locale/en-US/zotero/zotero.ftl
js-build/config.js
js-build/ftl-to-json.mjs
js-build/localize-ftl.mjs
js-build/utils.js
package-lock.json
package.json

This PR adds a pair of scripts to generate JSON that Transifex can understand from `chrome/locale/en-US/zotero/zotero.ftl`.
* Runing `npm run ftl-to-json` produces `tmp/tx/zotero_en_US.json` which is recognized by Transifex
* `Structured JSON` is the format in Transfiex I've used for testing. I believe `key-value JSON` also works because we're not using nested messages feature of structured JSON
* Running `npm run json-to-ftl` collects files from `tmp/tx` using regex `/(zotero_)([a-z]{2}([_-][A-Z]{2})?).json/` and creates translated `zotero.ftl` in locale-named folders in `chrome/locale/`. `en-US` is ignored because it is a source file.
* Some extra data is embedded in JSON to assist translating back to ftl. I've tested and Transifex does include it in the output file so this shouldn't be …

Add scripts to convert ftl to/from Transifex JSON

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/xpcom/fulltext.js
test/tests/HiddenBrowserTest.js
test/tests/data/test-hidden.html

We add an `http-on-modify-request` observer that blocks any request to a non-file: URL in browsers created with the `blockRemoteResources` option set to true. The observer is added on demand and removed when all browsers with remote content blocked have been destroyed. You'd think there'd be an easier way, but this is the best I could find.
Fixes #2721

Block remote content when indexing HTML file

---

chrome/content/zotero/searchDialog.xhtml
chrome/skin/default/zotero/zotero.css
scss/components/_clicky.scss

- Remove defunct `.zotero-clicky-*` styles from 2x block in zotero.css
- Include zotero-platform/content/zotero.css in searchDialog.xhtml
- It seems only the defunct 2x styles from zotero.css were being applied, so the buttons would have been unstyled on a non-hiDPI display
Fixes #3172

Fix clicky sizing and appearance

---

chrome/content/zotero/elements/colorPicker.js
chrome/content/zotero/tagColorChooser.js
chrome/locale/en-US/zotero/zotero.properties
scss/elements/_colorPicker.scss

Replaces `<div>`s with semantically-correct `<button>`s, adds labels to the color swatches, and enables keyboard navigation inside the color picker.
Arrow key behavior approximates but doesn't quite stick to that of VoiceOver - I added support for wrapping. Left arrow on the top-left square goes to the bottom-right square, up arrow on the top row goes to the same column in the bottom row, and so on.
The color names I chose are a bit subjective.
Fixes #2927

fx-compat: Make color picker CE accessible via keyboard and VoiceOver

---

chrome/content/zotero/xpcom/integration.js

Fix indentation in bibliography when a new item is added and therefore the recalculation of indents are needed.
https://forums.zotero.org/discussion/23689/bibliography-indentation
Before:
After:

Fix indentation in bibliography

---

chrome/content/zotero-platform/unix/overlay.css
chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/elements/relatedBox.js
chrome/content/zotero/elements/tagsBox.js
chrome/content/zotero/lookup.js
chrome/content/zotero/xpcom/sync/syncRunner.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/skin/default/zotero/overlay.css

Initial work on converting [this commit](https://github.com/zotero/zotero/commit/d866a10a2b56e96631a1563572d3f2918f1f006a#diff-e82e5d43de73ef85cfc03f6402d5afb5c18a629850d689b1d764516b5cab98f3) for Zotero 7.
Addresses #3001
Here's the issue: I can't seem to find what this commit is initially supposed to do ...
As the name suggests, I assumed it makes it possible to get to `advanced search`, `new note`,` add attachment`, `new item` buttons via Tab. That commit was part of Zotero 6.0.26, so I expected it would be possible there but not in Zotero 7 without this change. 
However, the navigation via tab works for me the same exact way in Zotero 6.0.26 as it does in Zotero 7 beta - the toolbar buttons cannot be reached via Tab.  [This screenshot …

making toolbar accessible to the keyboard - initial conversion

---

chrome/content/zotero/preferences/preferences_sync.jsx
chrome/content/zotero/preferences/preferences_sync.xhtml

Failing to login does not update the username in prefs.
Fixes #2901

only save username to prefs on successful login

---

chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/server_integration.js
components/zotero-service.js

A complimentary PR to https://github.com/zotero/zotero/pull/3168 for Zotero 6.0. To be merged after this feature is tested in the 7.0 Beta. Also the submodule in zotero-standalone for mac word needs to be updated to tag 6.0.7.

Add support for mac word transaction initialization via http for Zotero 6.0

---

chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/reader.js

When a new tab is added, record _prevSelectedID only if the previous tab was zotero-pane.
Fixes: #3152

jumpback only to library tab

---

chrome/content/zotero/tabs.js

When there are multiple tabs opened, menuitem File > Close is disabled for the library tab.
Fixes: #3198

disable file > close for library if 1+ tabs open

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/prefs.js
chrome/content/zotero/xpcom/utilities_internal.js
defaults/preferences/zotero.js
test/tests/attachmentsTest.js
test/tests/utilities_internalTest.js

This PR includes multiple changes to extend capabilities of `getFileBaseNameFromItem` ~~but keeps it backwards-compatible~~ using template engine. See #1413.
(Removed details of previous implementation, current in comment below)

Customizable renaming rules #1413

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/data/items.js
chrome/content/zotero/xpcom/file.js
chrome/content/zotero/xpcom/reader.js
test/tests/attachmentsTest.js
test/tests/itemTest.js

Passing unformatted = true to `Item#getField()` now returns a bidi control character-less result, and we use that in `Reader#updateTitle()` and `getFileBaseNameFromItem()` to prevent bidi control characters from showing up in filenames and window titles (the former everywhere, the latter on Windows only).
We also strip bidi control characters in `getValidFileName()` to be extra safe.
Fixes #3207

Strip bidi control characters in filenames and elsewhere

---

chrome/content/zotero/xpcom/plugins.js
chrome/content/zotero/xpcom/preferencePanes.js

Adds a utility to Zotero.Plugins to make this easier if we want to implement it in more places.
Fixes #3225

Resolve plugin-provided URIs relative to rootURI

---

chrome/content/zotero/xpcom/preferencePanes.js

When registering the preferences pane, `options.helpurl` should be `string` instead of `string[]`.

Fix type of `options.helpurl` in preferences pane

---

chrome/content/zotero/preferences/preferences_file_renaming.js

Addresses #3340
The new logic is:
* Take selected item (or first selected item, if more than one is selected)
* If it's a regular, top-level item, use that item, assume default extension (`.pdf`)
* Otherwise, if it's an attachment that has a parent and is either imported or a linked file, use parent item and this attachment's extension
* Otherwise fall back to the mock item and default extension

Improve file renaming preview in preferences

---

chrome/content/zotero/components/progressQueueTable.jsx

Crazy stuff going on here. When `require()` is invoked from a non-window context, `require.js` creates a fake window global. The fake window is window-y enough to make library code work, but nodes created under it end up with a null `ownerGlobal`, because it isn't _actually_ a window. And when a node's `ownerGlobal` is null, appending children or setting its `innerHTML` causes a segfault in the XUL process. Because `ProgressQueueTable`'s `rowToTreeItem` sometimes gets called by an event that's triggered in a non-window context, it ends up creating `ownerGlobal`-less nodes and triggering the segfault.
I tried creating the nodes under another window (like `Zotero.getMainWindow()`). This does not change anything. What matters is that the `ProgressQueueTable` code is being called by something …

Fix progress queue segfault

---

chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/preferences/preferences_export.jsx
chrome/content/zotero/preferences/preferences_export.xhtml
test/content/support.js

- Prevent flashes of unlocalized labels and controls without values set
- Preload panes on hover so there's usually no delay when switching
- Allow panes to delay visibility until a promise/promises resolve, and use that in Cite and Export to prevent flashes of empty tables
- Eliminate some race conditions
I thought there was an issue for the flashes of uninitialized content but can't find it now.

Make preferences less janky, preload panes on hover, allow panes to delay visibility until promise resolves

---

app/config.sh
package.json

fix: 
```
mktemp: too few X's in template ‘tmp’
```
fix: 
```
symlink has no referent: "/Users/jzl/code/zotero/build/resource/pako.js"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1356) [sender=3.2.7]
Traceback (most recent call last):
File "/Users/jzl/code/zotero/app/scripts/prepare_build", line 75, in main
subprocess.check_call([
File "/Users/jzl/miniforge3/lib/python3.9/subprocess.py", line 373, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rsync', '-aL', '--exclude', '.*', '--exclude', '#*', '--exclude', 'package.json', '--exclude', 'package-lock.json', './', '/Users/jzl/code/zotero/app/tmp/zotero/']' returned non-zero exit status 23.
```

[TAS-37] Bugfix: mktemp error when building on macOS and pako package lost problem.

---

app/build.sh
test/content/hyphenationTest.xhtml
test/content/hyphenationTestContent.html
test/tests/hyphenationTest.js

This will let us enable hyphenation in EPUBs again (and not disable it in snapshots).
https://forums.zotero.org/discussion/107328/report-id-1522731840-zotero-7-beta

Fix segfault when hyphenating text in main process

---

chrome/content/zotero/zoteroPane.js

For example, in a public group files are not editable, so this menu item should be disabled.
Fixes: #3428

disable "Find available PDF" if files are not editable in a library

---

chrome/content/zotero/collectionTree.jsx

Prevents being able to have multiple rows stuck in editing mode.
Fixes: #3426

Activate collection tree row only if it's focused

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/components/windowed-list.js

- The underlying changes are in windowed-list, which the item tree and all virtualized tables are based on, so if there are bugs they might show up outside of the collection tree.
- The expensive operation is adding/removing rows, since row offsets have to be recalculated (this includes collapsing/expanding rows).
- The cost on further drawing while scrolling is constant and shouldn't affect performance much.
Includes collection tree separators that are 8px high instead of the usual 20px.

Allow the collection tree rows to have custom row heights

---

chrome/content/zotero/zoteroPane.js

Allow ESC event propagating when reader is opened
This is needed to let itemBox, tagBox, etc. to handle ESC events to revent any edits made to textfields. Only applied if the currently focused element is input or textarea.
Fixes: #3246

Fix inconsistent ESC behavior on text edit when reader is opened

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/standalone/basicViewer.js
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/browserDownload.js
chrome/content/zotero/xpcom/connector/server_connector.js
chrome/content/zotero/xpcom/cookieSandbox.js
chrome/content/zotero/xpcom/data/feedItem.js
chrome/content/zotero/xpcom/fulltext.js
chrome/content/zotero/xpcom/zotero.js
components/zotero-service.js
test/tests/HiddenBrowserTest.js
test/tests/RemoteTranslateTest.js
test/tests/attachmentsTest.js
test/tests/browserDownloadTest.js
test/tests/server_connectorTest.js
test/tests/translateTest.js

- Currently enabled only for ScienceDirect. Can be enabled via a whitelist
- Matches the HiddenBrowser loaded HTML page for a captcha element. If the captcha element class changes, this will break (but the alternative is potentially displaying a captcha clearing window when something else that is not a captcha guard is loaded).
- User has 60s to clear the captcha, otherwise we timeout and fail the save.
- Doesn't automatically switch focus back to the browser which intiated the item save via the Connector.
- Stores the cookies used to clear the captcha for future saves from the same domain. Discards Connector supplied User Agent, since CF bot detector checks UA header against actual UA behavior like TLS handshake and if the UA acts different to what it's supposed to, the bot challenge is …

Displays a browser window to clear captcha when saving attachments.

---

chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/tabs.js
chrome/locale/en-US/zotero/zotero.properties

Adds an "Open Documents" section to the citation dialog that displays and searches currently opened document tabs in Zotero, which is displayed at the top, above other sections.

Add an "Open Documents" section to the citation dialog. Closes #3332

---

scss/elements/_editableText.scss

Simpler than I thought it would be! @abaevbog, see if this works for you?
(We should put together some sort of `editable-text` test suite/document with fields in various configurations, weird text that's likely to trigger wrapping edge cases, and so on.)

Fix `editable-text` expansion with non-overlay scrollbars on macOS

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/itemTreeColumns.jsx
scss/components/_item-tree.scss
scss/components/_virtualized-table.scss

This PR addresses issues #3582 and #3595.
The solution implemented here is functional, but there may be room for a more elegant approach. Given number of reports we had for the first column bug, we could opt to merge this as a quick fix and refine it later.
Changes include:
* A new handler `onSetOrder` in the virtualized table.
* Virtualized table now invokes onResize after the order of columns changes.
* The Items table uses `onSetOrder` to adjust the width of fixed/static width columns when they become the first columns.
* Similarly, when a column is toggled between visible and hidden states, and it becomes the first fixed/static column, its width needs adjustment.
* The exception for attachment column to use a different box-sizing has been removed. The fixed width has been adjusted to …

Fix a bug where first column is clipped if it has fixed or static width

---

chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences_file_renaming.js
chrome/content/zotero/preferences/preferences_file_renaming.xhtml

This PR extends Preferences API to trigger "unload" on all panes when window unloads. This new event is used in file renaming pane to unregister item tree observer to avoid a memory leak.
@AbeJellinek I couldn't find any good place to register `uninit` to do the cleanup so I've introduced one. Any suggestions, please let me know.
Fix #3574

Fix a memory leak in file renaming preferences pane

---

scss/elements/_editableText.scss

Something that was discussed during the redesign. Tabbing into a field still selects all text so that you could copy it.

no focus-ring for readonly editable-text

---

scss/elements/_zoteroSearch.scss

Added a bit more padding because 8px looked too tight when positioned at the start of the input.
Fixes #3617

Put the Advanced Search mode dropmarker back on the left

---

chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/itemBox.js
scss/abstracts/_mixins.scss
scss/elements/_editableText.scss

- min/max-lines attribute on editable-text determines how tall the field can/has to be
- if max-lines is not specified (or is below 1), the `textarea` will expand as much as needed without overflow
- removed hardcoded height and variables from css, substituted them with usage of these attributes for consistency
- No fields have any `max-lines` at this point, so all fields will expand as needed
Addresses: #3646

editable-text has no max-height unless specified

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/zoteroPane.js

When a saved search, collection or feed is renamed, update the `zotero-pane` tab so that it has the new title.
Fixes: #3664

update tab when collection row is updated

---

test/tests/tagsboxTest.js

Do not wait for the activate promise on linux. Passing `should update tag when pressing Enter in textbox` test during CI run.
Fixes: #3575

Fix to tagsbox test timeout in CI

---

chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/itemBox.js

- Instead of adding/removing the default names to the fields of empty creator names, set them as placeholders - that way they appear only when the actual creator name field is empty, and it requires no additional logic to add/remove them.
- Re-do of `capitalizeCreatorName` so that it works when the creator name field is focused. https://forums.zotero.org/discussion/111304/zotero-7-beta-fix-case-on-author-field-is-not-working-from-the-right-click-menu
- Fix to get the creator name contextmenu to appear for un-saved creators. That way one can switch the `fieldMode` before saving the creator. https://forums.zotero.org/discussion/111297/impossible-to-select-single-field-before-entering-an-author-7-0-0-beta-56-9edfcba9a
- Fix to tab/Shift-tab focusing wrong element right after a new creator …

fixes to itemBox creator functionality

---

chrome/content/zotero/contextPane.js
chrome/content/zotero/itemPane.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
scss/elements/_paneHeader.scss

- Space/Enter open the menus of "add note" and "add attachment" buttons
- Enter triggers the "New Collection" button for consistency
- Added locate button accessibility via tab from itemPane header or via shift-tab from the scrollable area of itemPane.
Fixes: #3593

additions to keyboard nav for toolbar buttons and reader

---

chrome/content/zotero/zoteroPane.js
scss/components/_virtualized-table.scss
scss/themes/_dark.scss
scss/themes/_light.scss

- Substituted previous yellow highlight color for `--accent-yellow`
- On windows, do not trigger collection highlighting when input is focused so that copy-paste Ctrl-C/Ctrl-V do not trigger highlighting
Addresses:  #3643

collection highlight tweaks

---

chrome/content/zotero-platform/win/overlay.css
chrome/content/zotero/zoteroPane.xhtml
scss/components/_mainWindow.scss
scss/linux/_menu.scss
scss/linux/_menupopup.scss
scss/linux/_tabBar.scss
scss/linux/_titleBar.scss
scss/mac/_tabBar.scss
scss/mac/_titleBar.scss
scss/win/_tabBar.scss
scss/win/_titleBar.scss
scss/zotero-mac.scss
scss/zotero-unix.scss

- Titlebar buttons now appear in the correct position based on the DE preferences
- Removed the Z in the titlebar for Linux
- Tabs aligned with the left margin on Linux and Windows
- Restored popupmenu styling to GTK widget-defined styling
- Fixed some rendering issues on Unity DE
Before:
| Gnome/KDE | Pantheon | Cinnamon | Unity |
|-------------------|--------------|---------------| --------|
| ![image](https://github.com/zotero/zotero/assets/5899315/71154d91-56be-4351-97bf-bb347ab9f7d4) | ![image](https://github.com/zotero/zotero/assets/5899315/fefb27d2-44dc-4191-8bd2-ee32ac59eb96) | ![image](https://github.com/zotero/zotero/assets/5899315/0b8bdd2e-c029-4a2b-b982-a10c8cd55e91) | ![image](https://github.com/zotero/zotero/assets/5899315/0fb3dc55-bf15-4051-b2c8-3ee44e6c8628) |
After:
| …

Fixes for Linux appearance for various DEs

---

chrome/content/zotero/xpcom/attachments.js
test/tests/attachmentsTest.js

Not sure if we only want to trim only the truncated value or any value. I opted for the latter but happy to change it.
I'll update the documentation once this is merged.
Related: [#3701 ](https://github.com/zotero/zotero/issues/3701#issuecomment-1948140718)

Trim spaces from values in getFileBaseNameFromItem

---

chrome/content/zotero/components/tagSelector.jsx
chrome/content/zotero/components/tagSelector/tagSelectorList.jsx
chrome/content/zotero/containers/tagSelectorContainer.jsx
chrome/content/zotero/zoteroPane.js
scss/components/_tagSelector.scss

- Tab from the tags list or shift-tab from the tags filter field focuses the first non-disabled tag. If there are none, the tags are skipped and the focus moves directly to the input field or the tags list.
- Arrow Right/Left move focus between tags skipping over disabled tags
- Space/Enter clicks on the selected tag
- Space/Enter click on the search button when focused
Fixes: #3603

Keyboard navigation for tag selector

---

chrome/content/zotero/xpcom/data/item.js

This PR is a fix for a visual glitch where attachments column flickers when being selected for some items:
https://github.com/zotero/zotero/assets/214628/b50a8a32-0fdb-495f-8083-439ed33b39c6
This is a regression related to the attachment preview generation which calls [`fileExists`](https://github.com/zotero/zotero/blob/872e7b24278a2f00d7558aa9055d7f641c1a768a/chrome/content/zotero/elements/attachmentPreview.js#L208) which results in `bestAttachmentState` cache being cleared for this particular item before being checked again in `itemTree` on a 150ms timeout (hence the flicker).
While this is a very small change, I'd appreciate feedback if this is the right approach to fix the issue.

Fix attachment column icon flickering upon selection

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/xpcom/fulltext.js
test/tests/data/test.sh
test/tests/fulltextTest.js

This fixes indexing of things like shell scripts (`text/x-shellscript`), which Firefox will try to save instead of displaying unless we override the content type.
As an aside, `isTypeSupported()` may be the answer to [this](https://github.com/AbeJellinek/zotero/blob/3b9afcc500a1e0537deb6398a4f8d23e3b3320ab/chrome/content/zotero/xpcom/mime.js#L101)! But that code is old enough that maybe we're better off just not touching it at this point...
Fixes #3704

Fix indexing files with text content types that Firefox won't display

---

chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences_export.jsx

The issue before was that setting the `menulist`'s value would remove and re-add its internal label child, which would trigger our mutation observer, which would set its value, ...
This PR re-applies the empty label fix and uses a more robust approach for syncing when a menuitem is added:
- Only sync when a menuitem child is added with a value matching the current preference value, so we don't sync on internal changes like the label replacement that was causing the infinite loop above
- Don't fire `syncfrompreference` when doing one of these MutationObserver-triggered syncs - the element's value was already correct, we're just updating its visual properties, and firing `syncfrompreference` could cause infinite loops in cases where a listener on that event adds a menuitem (although that's …

Fix empty Quick Copy locale dropdown (without a freeze)

---

chrome/content/zotero/actors/SingleFileChild.jsm
test/tests/HiddenBrowserTest.js

Without this, snapshotting a page like https://developers.google.com/youtube/youtube_player_demo that contains a cross-origin iframe causes an error, and the snapshot won't be saved.
If we wanted to, we could actually _fix_ cross-origin iframes instead, but we don't save iframes at all in the Connector and it would make things a lot messier here.

SingleFile actor: Skip cross-origin frames to fix error

---

chrome/content/zotero/contextPane.js

When contextPane is toggled open, keep the focused element unaffected.
Fixes: #3716

do not focus contextPane after it's toggled open

---

chrome/content/zotero/BlockingObserver.jsm
chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/xpcom/reader.js

So it's still not completely clear to me what was going on here.
When using the reader in Firefox/Chrome/Safari, everything is fine. Remote requests are fully and immediately blocked due to CSP. No data goes out and no data comes in.
In the client, though, things are weird. When a snapshot includes a remote resource - `<iframe>`, `<img>`, etc. - it's as if the CSP kicks in late. The request goes out, the server starts sending a response and the response headers get read, *then* Firefox remembers that it was supposed to be paying attention to the CSP, and it cuts off the response. Future resources added after the page is done loading (e.g. you go into the console and programmatically append an `https://example.com/` iframe) are fully blocked - no requests at all.
I'm not sure why that's …

Fully block all HTTP requests in the reader

---

chrome/content/zotero/zoteroPane.js

- ZoteroPane.handleKeyDown does not capture events. It is not strictly necessary now but it helps to avoid future issues such as one solved in b15fb36f1b546d51b3908081f1fd2e71b73739f4. One benefit from this now is if one tabs onto a toolbarbutton that opens a menu in contextPane (e.g. an options button in itemBox), clicks space to open the menu and then escape to close it, this will keep focus where it was, while the capturing listener would immediately shift the focus to the reader.
- Removed shift-tab specific case from the handler. It looks like it was handling the shift-tab in the following scenarios: from notes search bar (can just be handled by Tab), from "Return to notes list button" in note editor toolbar (it's no longer there), from a child of zotero-view-item e.g. itembox. (does …

make shortcuts keypress listener non-capturing

---

scss/elements/_noteEditor.scss

Have to set an explicit `max-height` because of some weird `-moz-box`/`flex` interactions, as usual. Maybe we'll be able to do something better (e.g. `flex-grow: 2` on the note editor and `flex-grow: 1` on the Tags/Related container) once everything is flexbox!
Fixes #3686

Set max-height on note-editor Tags/Related and allow to scroll

---

chrome/content/zotero/locateMenu.js
chrome/content/zotero/zoteroPane.js

Not sure if there's a reason we stuck with http:// for this in the past (site didn't support HTTPS?), but it seems to work fine now.

Use HTTPS when opening DOIs via Locate menu and double-click

---

chrome/content/zotero/locateMenu.js
chrome/locale/en-US/zotero/zotero.ftl

- Run label update logic once instead of repeating on every item
- Show plural attachment type when multiple attachments of same type are selected (instead of "Attachments")
- Fix incorrect icon and label showing when `openReaderInNewWindow` = true
- Fix alternate-behavior item hiding for all item types when PDFs are set to open externally (and never hiding when other types are set to open externally)
Fixes #3741

Locate menu: Don't show "New Tab" when external, fix bugs

---

chrome/content/zotero/newCollectionDialog.xhtml

Just about as wide as it can be without looking weird IMO:
Fixes #3717

New Collection dialog: Widen

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/zoteroPane.js
test/tests/itemsTest.js

Replace calls to keepParents() with keepTopLevel()

---

chrome/content/zotero/xpcom/fileHandlers.js
components/zotero-protocol-handler.js
test/tests/fileHandlersTest.js

- PDF view wants `pageIndex` directly under the location object passed to `navigate()`, not under `location.position`
- Fix reader not navigating when only an annotation ID is passed
- Add test to make sure that the navigation works
- Pass multiple properties if multiple query params are provided
@mrtcode, let me know if the logic here looks right.
Fixes #3759

Fix zotero://open/ and FileHandlers regressions

---

chrome/content/zotero/elements/itemBox.js
scss/elements/_itemBox.scss

When contextmenu closes, it clears visibility style from all components. It is added temporarily so that the options buttons do not disappear if the mouse leaves the row. The visibility setting for the grippy for items with only one author should be in a separate class so that grippy is not displayed by accident.
Fixes: #3732

itemBox: ensure the grippy is hidden if <2 authors

---

chrome.manifest
chrome/content/zotero/xpcom/zotero.js
chrome/content/zotero/zotero-autocomplete.js

- autocomplete registration removed from chrome.manifest
- static registration happening in zotero.js
- tweaks to autocomplete methods to implement nsIAutoCompleteSearch based on https://searchfox.org/mozilla-central/source/toolkit/components/autocomplete/tests/unit/test_378079.js#154

fx115: working autocomplete

---

chrome/content/zotero/preferences/preferences.js

Very unlikely that you'd want the prefs to reopen to Reset Sync, for example. With this change, they'll reopen to the last non-subpane that you viewed.

Preferences: Don't reopen to subpane

---

js-build/.eslintrc
js-build/utils.js
js-build/watch.js

- Fix #3758
- Add watching for new files (no idea why we didn't do this before!)
- Add debounce and batching to reduce verbosity and avoid needless cleanup and "add to omni" steps when entire directories are affected.
https://github.com/zotero/zotero/assets/214628/2c7f4430-8e03-4ec4-a8e2-63794c447786

Improve build process

---

scss/win/elements/_editableText.scss

Fix editable-text height on Windows

---

chrome/content/zotero/integration/quickFormat.xhtml

Use <checkbox> instead of <html:input type="checkbox"> for the suppress author checkbox. <html:input> on mousedown on the actual box looses focus, so the popover is immediately closed by focusout listener. Fixes: #3830

qf: fix suppress author checkbox click

---

chrome/content/zotero/elements/abstractBox.js
chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/paneHeader.js

Previously, dropping text on an unfocused item box field would make the text appear for a second at the drop position, then the field would focus and the added text would disappear. If you dragged the text from another item box field, it would disappear from _both_ fields. Pretty broken.
Now, dropping text works like Paste:
- If the field is focused when you drag text into it, e.g. when you drag text from another application, switch to Zotero, and drop into the focused field, it'll be added at the cursor position like normal.
- If the field is unfocused when you drag text into it, e.g. when you drag text from the focused field onto an unfocused field, or another application onto a field in the unfocused Zotero window, it'll replace the entire value of the field. We set the Copy cursor to …

editable-text: Make dropping text work when field is unfocused

---

chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/editorInstance.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/zoteroPane.js

- handle additional zpRefocusID options value in Zotero_Tabs.select to focus a node with the specified ID, instead of what was recorded as last focused element
- use that parameter in ZoteroPane.selectItems to make sure that itemTree is focused after the tab is switched to zotero-pane
- removed redundant calls to Zotero_Tabs.select('zotero-pane') after Zotero_Pane.selectItems
Fixes: #3783

fix to "show in library" not focusing the itemTree

---

chrome/content/zotero/itemTree.jsx
scss/components/_item-tree.scss

This brings back order from before the redesign (tags before title). To get the current behavior (tags after title), one can set pref `extensions.zotero.ui.tagsAfterTitle` to `true`.
Resolve #3781

Move tags back to beginning of item rows

---

chrome/content/zotero/zoteroPane.js

On windows, if the cross icon from the collection filter search-textbox is clicked, the 'blur' event fires before the input is cleared, and the filter is never hidden. To make sure that the search field ends up going away, hide it if the field is empty and not focused in input handler.
Fixes: #3840

Fix collections filter not hiding on windows

---

chrome/content/zotero/integration/quickFormat.js

- use dialog as the anchor, not the document element
- after the window is resized, the panel will remain where it was, so if it's far away from the dialog, if gets closed and re-opened to reposition it.
Fixes: #3847

QuickFormat dialog: fix wrong references panel position on windows

---

chrome/content/zotero-platform/mac/integration.css
chrome/content/zotero-platform/unix/integration.css
chrome/content/zotero-platform/win/integration.css
chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/integration/quickFormat.xhtml
chrome/locale/en-US/zotero/zotero.ftl
chrome/skin/default/zotero/integration.css

- Reference panel remains opened while the focus is on an input
- The first item from the reference panel is no longer selected by default to avoid unwanted items being added as a bubble
- The first item from the reference panel is selected only when the dialog has no bubbles or when a search for a non-empty input just ran
- Shift-Enter from input or reference panel will accept the dialog's state instead of creating a bubble
- Ensure that the reference panel reloads when a bubble is deleted
Addresses: #3811, #3671

Quick-format: do not hide reference panel

---

app/scripts/prepare_build

Python 3.12 includes [this change](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes):
> A backslash-character pair that is not a valid escape sequence now generates a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning), instead of [DeprecationWarning](https://docs.python.org/dev/library/exceptions.html#DeprecationWarning). For example, re.compile("\d+\.\d+") now emits a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning) ("\d" is an invalid escape sequence, use raw strings for regular expression: re.compile(r"\d+\.\d+")). In a future Python version, [SyntaxError](https://docs.python.org/dev/library/exceptions.html#SyntaxError) will eventually be raised, instead of …

Update `prepare_build` for Python 3.12

---

.github/workflows/ci.yml

This fixes the current build annotations caused by deprecated versions:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/setup-node@v3, actions/cache@v3.
For more information see
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Update used GitHub actions

---

chrome/content/zotero/tools/cslpreview.js
chrome/content/zotero/tools/cslpreview.xhtml

This PR fixes dark mode in "Zotero Style Preview" window. We've previously re-styled "Style Editor" but missed this one.

Fix styles in CSL Preview window

---

chrome/content/zotero/elements/editableText.js

Things were getting a bit out of hand with the anonymous listeners, and this should be clearer and more maintainable in the future.
Event handlers extracted with no code changes. Moved one line in `render()` to make the conditions that set `focused` to true clearer.

editable-text: Clean up `render()`

---

chrome/content/zotero/integration/insertNoteDialog.js
chrome/content/zotero/integration/insertNoteDialog.xhtml
chrome/content/zotero/integration/quickFormat.js
chrome/skin/default/zotero/integration.css

Fix breakage in insert note dialog caused by missing icon container after 1eaff81
Since `insertNote` dialog uses the same exact code as `quickFormat` dialog, any DOM-related changes need to account for both of them, and I think I missed it last time. 
This simply adds a wrapper container to the spinner, same as in `quickformat`, and does not break if the spinner does not have the "Accept" button sibling.

qf: fix insertNote dialog breakage

---

chrome/content/zotero/elements/tagsBox.js
chrome/content/zotero/zoteroPane.xhtml

With fx115, changes from 49fe2b98d97523174889ec86b9925e4e795ca034 made the autocomplete popup appear blank when the reader tab is opened. Not re-creating the PopupAutoComplete in tagsBox makes the items from autocomplete popup visible again. But it makes the autocomplete appear below the "Add tags" popup for annotations (what 49fe2b98d97523174889ec86b9925e4e795ca034 originally fixed), and it also creates a duplicate `popupset` with a new autocomplete panel at the bottom of the DOM every time autocomplete runs. The duplicate `panel`s do not have an id.
Manually adding a `popupset` with a `panel` whose id="PopupAutoComplete" does not create any duplicates and properly positions the popup.
Fixes: #3881

fx115: fix tagsbox autocomplete breakage

---

chrome/content/zotero/xpcom/http.js

Fix #3892 
This is the simplest solution with no additional messages. I think it works well enough, given that previously error message also included the raw string error code.
Before:
After:

Fix error when dealing with invalid certificates

---

chrome/content/scaffold/scaffold.xhtml
chrome/content/zotero/reader.xhtml
chrome/content/zotero/standalone/basicViewer.xhtml
chrome/content/zotero/standalone/hiddenWindow.xhtml
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/standalone.dtd

- Prevent an error when opening/closing Window menu
- Remove dead WindowMediator-related markup
- Use Mozilla strings

fx-compat: Copy over fx115 Window menu changes

---

chrome/content/zotero/xpcom/utilities_internal.js

We only call this from one codepath that only runs on macOS right now, but it would break when passed an absolute path on Windows.

`subprocess()`: Use `isAbsolute` instead of checking for slash

---

chrome/content/zotero/preferences/preferences_sync.jsx
chrome/content/zotero/xpcom/http.js
chrome/content/zotero/xpcom/sync/syncRunner.js
chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/zotero.properties

It seems in fx115 this no longer works:
https://github.com/zotero/zotero/blob/751457268bd84e6c49d29044ca86d804db75cb13/chrome/content/zotero/xpcom/http.js#L1269C9-L1269C31
I'm getting generic "Error connecting to server. Check your Internet connection." for expired/revoked certificate. From what I can see `secInfo.securityState` is always 0, even though `errorCodeString` might actually be populated.
Looking for a solution I've found [`SecurityInfo` utility](https://searchfox.org/comm-central/source/mozilla/toolkit/components/extensions/webrequest/SecurityInfo.sys.mjs#27) which seems to contain the logic we need, although it doesn't seem to return value for `errorMessage` contradictory to what the comment says so we still need to use `errorCodeString`.
Any suggestions welcome.

fx115: Fix detecting insecure connection no longer works

---

chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/xpcom/sync/syncRunner.js
chrome/content/zotero/xpcom/zotero.js
chrome/content/zotero/zoteroPane.xhtml

`ZoteroStandalone.checkForUpdates()` and `Zotero.openCheckForUpdatesWindow()` were essentially the same, except that the latter opened it as a modal. Unified and added bring-to-front behavior.
Fixes #3104

Bring Check for Updates to front if re-triggered, unify functions

---

chrome/content/zotero/preferences/preferences_advanced.xhtml
resource/word-processor-plugin-installer.js

These explicit widths aren't necessary to make descriptions wrap anymore, and they were causing overflow.

Preferences: Fix overflow at small window sizes

---

chrome/skin/default/zotero/bibliography.css

Create Bibliography: Fix "Language:" label alignment

---

chrome/content/zotero/progressWindow.xhtml
chrome/content/zotero/titlebar.js

Before:
Windows:
Linux:
After:
Windows:
Linux:

Fix progress window title bar on win and linux

---

app/scripts/fetch_xulrunner

DOMInputPasswordAdded event is triggered on autocomplete submission which causes an error in LoginManager.
The error gets logged in the console, though the autocomplete does work. This just removes the event from ActorManagerParent.
Fixes: #3883

do not trigger event causing autocomplete error

---

chrome/content/scaffold/load.js
chrome/content/scaffold/load.xhtml
chrome/content/scaffold/scaffold.js
chrome/locale/en-US/scaffold/scaffold.dtd
scss/scaffold.scss

And remove Creator column from the load dialog - it was of questionable value when opening a translator, caused weird fx115 layout issues, and takes up space that's better used for displaying translator labels.
https://forums.zotero.org/discussion/113602/zotero-7b72-translator-editor-scaffold-broken

fx115: Fix Scaffold richlistboxes and load dialog sizing

---

chrome/content/zotero/BlockingObserver.jsm
test/tests/HiddenBrowserTest.js

When a browser isn't initialized (added to the DOM), its `browserId` is 0. When a channel isn't associated with a browser, its `browserId` is also zero. So passing an un-initialized browser to `register()` would block all requests that didn't come from a browser! Now `register()` will throw and `observe()` will ignore `browserId` 0.
(I don't know what conditions were causing an un-initialized browser to be passed to `BlockingObserver`, if that was even the issue at all, but this should help us figure that out.)
Fixes #3962, I hope - will see once CI runs

BlockingObserver: Don't block when browserId is 0

---

chrome/content/zotero/elements/attachmentBox.js
chrome/content/zotero/elements/attachmentPreviewBox.js
chrome/content/zotero/elements/attachmentRow.js
chrome/content/zotero/elements/attachmentsBox.js
chrome/content/zotero/elements/collapsibleSection.js
chrome/content/zotero/elements/librariesCollectionsBox.js
chrome/content/zotero/elements/notesBox.js
chrome/content/zotero/elements/relatedBox.js
chrome/locale/en-US/zotero/zotero.ftl

Added aria labels and button roles for buttons in the item/Collection pane. This includes buttons in the header as well as rows from notes, related, collections, and attachments section that act as buttons. Also added missing `aria-labelledby` for mini-itembox rows below attachment preview to have filename, dateModified and etc. properly labelled.
This also covers most of vpat 16.
This does not affect how tags/header/itemBox entries are announced. There is a separate issue with NVDA and JAWS sometimes struggling with announcing text inside of `editable-text` component, so this will be handled separately.
This also does not affect annotations since those are not keyboard accessible yet.

vpat 6: aria labels for buttons in item/context panes

---

chrome/content/zotero/components/tagSelector/tagSelectorList.jsx
chrome/content/zotero/zoteroPane.xhtml

- set each tag's role as "checkbox"
- set "aria-checked" status depending on if the tag is selected
- added aria-label to tag selector so it does not default to "grid"
That way, each tag is announced together with it's "checked" state.

vpat_11: add roles and states to tags in tag selector

---

chrome/content/zotero/tabs.js
chrome/content/zotero/zoteroPane.js

On last tab in the itemPane/contextPane, focus will wrap around to the selected tab to complete the loop. It ensures that the focus order is consistent regardless of the directions.
Also, minor tweaks to focusWrapAround in Zotero_Tabs to properly move focus to the last focusable entry in the contextPane.

vpat 3: consistent focus order in all directions

---

chrome/content/zotero/zoteroPane.js

From the sync button, tabbing will move focus in the following manner: collections toolbar -> collections -> tags selector -> itemTree toolbar -> actual itemTree -> itemPane.
It better reflects the the structure of the library pane. No changes are made to the focus sequence in the reader tabs, since the scrollable area and the sidebar share the toolbar.

vpat: 4 change focus sequence in zotero pane

---

app/assets/commandLineHandler.js
chrome/content/zotero/xpcom/commandLineHandler.js
chrome/content/zotero/xpcom/zotero.js

- Set `cmdLine.preventDefault` in all cases. Some internal handler is opening the main window when it's already open. I don't know where that's happening! It's not in `nsDefaultCLH`, because that checks for an existing window. In any case, `preventDefault` prevents it.
- Update `Zotero.openMainWindow()` to work on fx115: Import `AppConstants`, which is no longer available globally in ES modules
Fixes #3964

Prevent duplicate main window

---

chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/skin/default/zotero/overlay.css
scss/abstracts/_variables.scss
scss/components/_contextPane.scss
scss/components/_item-tree.scss
scss/components/_mainWindow.scss
scss/components/_toolbar.scss

Now the window size constraints depend on the current sizes of the sidebars. So if the item pane is collapsed, you can make the window very narrow; if the item pane is very wide, the window can't be made very narrow. Adjusts automatically for Stacked mode.
Fixes #3607

Set main window min-width/height dynamically

---

chrome/content/zotero/components/search.jsx
chrome/content/zotero/zoteroPane.js
test/tests/zoteroPaneTest.js

- edits to zoteroPaneTest.js focus tests to expect the updated focus sequence: selected tab -> tabs menu -> sync button -> collectionTree toolbar -> collectionTree -> tags selector -> itemTree toolbar
- updated tags selector keydown handling to explicitly handle all tab/shift-tab events using moveFocus. It is more readable and explicit focus handling for all components is required for programmic tab/shiftTab events dispatched in tests to actually move focus
Fixes: https://github.com/zotero/zotero/issues/3975

fix to focus test breakage in zoteroPaneTest

---

chrome/content/zotero/zoteroPane.js

Set the aria-label on the sync button. On focus, register the sync status and set the aria-description to be the last sync status.

vpat 9: set aria properties on the sync button

---

chrome/content/zotero/integration/quickFormat.js

Screen readers announce the index of the selected item from the list of citations in the panel. This removes the separators from the count, since they are not focusable and should be skipped.

vpat 5: do not include separator in qf list count

---

chrome/content/zotero/components/tagSelector/tagSelectorList.jsx
chrome/content/zotero/containers/tagSelectorContainer.jsx
chrome/content/zotero/zoteroPane.js
test/tests/zoteroPaneTest.js

- no tabstop on the tag selector scrollable area
- change tag selector's role from default "grid" to "group". "grid" is not quite correct semantically and leads to voiceover suggesting irrelevant commands.
- move all keyboard handling logic to tagSelectorList.jsx. Tabbing through tag selector is now handled in ZoteroPane, so the only logic left there is arrow navigation
between tags, and there's no reason to not have it together with the tags list.
- a workaround to deal with focused tags when windowing kicks in. When a tag is focused, record its index. Each time tags are re-rendered, if the saved index is not among rendered tags, refocus it, otherwise, move focus to the tags list. So if the tag is focused, you scroll away and then back, the tag will get re-focused and it will look like …

tag selector focus edits, fix windowing breakage

---

chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
scss/elements/_itemDetails.scss

Transpose `width`/`height` to CSS for fx115, and ignore persisted attributes that are no longer persisted

Fixes for restoring of persisted attributes

---

app/build.sh
app/config.sh
app/mac/build-and-unify
app/mac/mozilla-115.patch
app/scripts/fetch_xulrunner

Backports the following Mozilla fixes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1858409
(AutoFill/Services menus; fixes https://github.com/zotero/zotero/issues/3927)
https://bugzilla.mozilla.org/show_bug.cgi?id=1884631
(sheets → dialogs; fixes https://github.com/zotero/zotero/issues/3936)
https://bugzilla.mozilla.org/show_bug.cgi?id=148624
(ghost tooltips, because why not)

Use custom XUL binary on macOS

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/standalone.dtd

ItemTree now exposes `toggleSort` (with a convenience `countVisible` parameter so ZP doesn't need to know anything about which columns are visible) and a couple menu builders.
Fixes #2273.

Add sorting options and column picker to View menu

---

chrome/content/zotero/integration/addCitationDialog.xhtml
chrome/locale/en-US/zotero/zotero.ftl

- vpat 57: remove tabindex values, set `tabindex=0` on all focusable fields. It allows mozilla to determine the best focus sequence for keyboard navigation and fixes wrong order where some inputs would go before the "Ok" and "Cancel" buttons and some - after
- vpat 58: added labels to all inputs to be announced when focused. Added separate labels for locator menulist and for the locator input so that the locator type has a proper label. It is also better to have visible explicit labels when possible

vpat 57/58: classic citation editor aria fixes

---

chrome/content/zotero/integration/addCitationDialog.xhtml
chrome/locale/en-US/zotero/zotero.ftl

To address the immediate VPAT issues, the locator dropdown has aria-label "Locator type". The locator input is labelled by a hidden label with "Locator input" string, as well as the locator type. That way both the locator type and the "Locator input" string are announced when it is focused.
Fixes: #4039

post vpat 57: revert layout changes to locator

---

chrome/content/zotero/xpcom/cookieSandbox.js

XHRs still [implement](https://searchfox.org/mozilla-central/rev/1f5e1875cbfd5d4b1bfa27ca54832f62dd19589e/dom/webidl/XMLHttpRequest.webidl#131-132) `getInterface()`, but they no longer support `QueryInterface`.
Fixes #4042

CookieSandbox: Fix attachToInterfaceRequestor() for XHRs

---

chrome/content/zotero/progressQueueDialog.xhtml
chrome/content/zotero/xpcom/progressQueueDialog.js
chrome/skin/default/zotero/zotero.css
scss/progressQueueDialog.scss

- Change root element ID - `#zotero-progress-box` corresponded to some outdated and unused styles in `zotero.css` that we don't want to apply here
- Remove those unused styles
- Add `progressQueueDialog.scss` and move styles there
Fixes #4026

Fix progress queue dialog overflow

---

chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml

They don't work when created in JS for some reason.
(The use of `createElement` instead of `createXULElement` wasn't the issue, although that was a mistake.)
Fixes #4056

Fix column-sorting shortcuts on Windows

---

chrome/content/zotero/actors/FeedAbstractChild.jsm
chrome/content/zotero/elements/abstractBox.js
chrome/content/zotero/xpcom/feedReader.js
scss/feedAbstract.scss
test/tests/data/feedRichText.rss
test/tests/feedReaderTest.js

Fixes all issues reported [here](https://forums.zotero.org/discussion/113989/zotero-7-beta-graphical-abstract-in-rss-feeds):
- Black on black text
- Broken relative/protocol-relative images
- Reader ignoring rich-text content in favor of plain-text summary

Feed & feed abstract fixes

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/progressWindow.xhtml
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/data/cachedTypes.js
chrome/content/zotero/xpcom/data/feedItem.js
chrome/content/zotero/xpcom/progressWindow.js
chrome/skin/default/zotero/zotero.css
scss/progressWindow.scss

Font size has increased because we're pulling in `_base.scss`. Can override that if we don't want it.
I fixed up `getImageSrc()`, since it was returning incorrect paths for types containing multiple consecutive capital letters ("PDF"), but I also removed all remaining uses of it. Progress windows now use SVG icon names.
I also removed seemingly unused `attachmentProgressHandler`.
Before:
After:
Fixes #4046

Update progress window to use SVG icons

---

chrome/content/zotero/elements/quickSearchTextbox.js
chrome/locale/en-US/zotero/zotero.ftl

Fluent seems to clear out label/placeholders attributes set directly (not via .ftl file). So quicksearch placeholder added directly ends up being emptied out.
This is the cleanest workaround found so far: add the placeholder as the fluent argument
Fixes: #4073

set quicksearch placeholder as fluent argument

---

chrome/content/zotero/integration/addCitationDialog.xhtml
chrome/locale/en-US/zotero/zotero.ftl

"Locator input" -> "Locator"
Fixes: #4066
Per comment from https://github.com/zotero/zotero/commit/0077c3f07a2f0fa1fb0e2568f25aa8b598b9074a:
> "input" strikes me as a fairly technical term.
Doesn't the screen reader already tell you that it's a text box? So "input" seems a bit redundant anyway. Seems like it could just be "Locator"?
Yeah, "input" is fairly technical... Screen readers do announce that it's an input field in this way or another (e.g. voiceover will say "edit text"). With `aria-labelledBy` pointing at the locator type dropdown and the input's label, screen readers announce both (e.g. "Locator type page. Locator input 6"). So the only reason why I added "input" initially is to make a clearer distinction from "Locator type" which indeed might not be helpful. I suppose we can …

post vpat-57: qf locator string tweak

---

chrome/content/zotero/tabs.js
chrome/content/zotero/zoteroPane.xhtml
scss/components/_tabsMenu.scss

- if there are too many tabs opened to fit into the available space on the screen, set the menu's list height so that it becomes scrollable. As a cutoff for the necessary height, use 75% of `screen.height -  window.screenTop`:  this seems to give enough space to avoid overlap with the toolbar (dock) at the bottom. 
- this cutoff will become the menu's height if there are too many entries, so the menu will be shorter if the main window is dragged down closer to the bottom of the screen and longer if the window is at the very top.
- when tabs menu is refreshed, scroll to the selected tab.
- use margins instead of padding to that the scrollbar does not overlap with the cross button.
Fixes: #3822

make opened tabs menu scrollable

---

chrome/content/zotero/components/tabBar.jsx

After clicking on a reader tab, the reader will get focused but the default mousedown event handler can then shift focus onto the actual tab. It looks like the focus gets "lost", and breaks reader keyboard shortcuts so we want to avoid it. Mainly happens on windows.
Fixes: #4077

prevent focus from sticking to tab after click

---

chrome/content/zotero/zoteroPane.js

Fixes item tree sorting and tab switching shortcuts so they work in the French AZERTY layout.
**Sort shortcuts:** Use Alt as the modifier on Windows. For some reason, Alt is the only modifier (besides Ctrl, which is taken) that works with the French layout. Replacing `key="[1-9]"` with `keycode="VK_[1-9]"` stops it from working at all, in any layout (I guess because that's only for unprintable keys).
**Tab shortcuts:** Use a routine similar to the one that we use in the item tree for tag shortcuts. Although `<key>` elements work with Ctrl as the modifier, key *events* report the printable value of the pressed key instead of the number (`&é"` and so on). So we compare `event.code` instead of `event.key`.
(I get stressed every time I remember that keyboard layouts are something we need to …

Update numeric keyboard shortcuts for keyboard layout compat

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/actors/ActorManager.jsm
chrome/content/zotero/actors/ZoteroPrintChild.jsm
chrome/content/zotero/actors/ZoteroPrintParent.jsm
chrome/content/zotero/fileInterface.js
chrome/content/zotero/xpcom/reader.js

And extract the reader's `zoteroPrint()` function and use it in HiddenBrowser.
Printing doesn't work on any browser that's within a `HiddenFrame`, the `hiddenDOMWindow`, etc. It needs to be under an actual visible chrome window. There's no error message, just a silent failure, so I'm not sure what the issue is. In any case, added a new `useHiddenFrame` option to `HiddenBrowser`. When set to false, we use the main window instead of a `HiddenFrame`.
Reader will need zotero/reader#123 after this.
Fixes #3190

 Create Bibliography: Use HiddenBrowser to fix printing 

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/actors/PageDataChild.jsm

The key is to set `docShell.allowContentRetargeting` to false. But that doesn't have any effect on remote loads when set in the parent process, so we do it in the `PageData` actor and actually initiate the load from there. This new approach is based on `BackgroundThumbnailsChild`, which is a little more robust than `HeadlessShell` since it runs during normal use (as opposed to only when you invoke Firefox with a special command-line option).
I wasn't able to figure out how to unit-test this, unfortunately.
Fixes #3835 (which might be happening [during indexing?](https://forums.zotero.org/discussion/comment/462257/#Comment_462257))
(Also fix `channelInfo` throwing when called on a non-HTTP channel.)

HiddenBrowser: Block all downloads

---

scss/elements/_colorPicker.scss
scss/win/components/_button.scss

- Prevent Windows button defaults from overriding other styles by setting specificity to 0
- Fix color picker swatch appearing too small and grid buttons overlapping/overflowing
Fixes #4079

Fix color picker (and other) button styles

---

test/tests/concurrentCallerTest.js

As far as I can tell, what's happening here is that random event loop lag sometimes causes the delay between `caller.start(funcs1)` and `caller.start(funcs2)` to be long enough that function 3 actually _has_ finished before 4 and 5 do. This change makes 3 take longer. Maybe that'll help!

Try to prevent ConcurrentCaller from failing CI

---

chrome/content/zotero/elements/itemPaneSection.js
chrome/content/zotero/zoteroPane.js

If the info section is collapsed, do not try to focus and open the itemType menu after item creation via Cmd-Shift-N as it can lead to an empty dropdown. Just focus the header title in that case.

Prevent empty item type menu from appearing after Cmd-Shift-N when info section is collapsed

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/tabs.js

- revert debcb9944d19862565435fe0b8768c95c3dc633f since it breaks drag-drop reordering of tabs
- when reader is being refocused by contextPane, add a small delay so that the focus settles on the tab before focusing the reader
- also explicitly refocus the reader tab after drag, since then focus also lands on the tab and finds itself outside of the reader
This should take care of focus sticking to the tab after clicking between them or drag/drop (which I assumed is not desired as well).
There are some other instances where focus may not do exactly what we want, though. Since reader is a separate browser, if any element outside of it receives focus, clicking back into the reader won't necessarily transfer focus back into it. For example, if I click on an `editable-text` in the context pane …

redone fix of focus sticking to tab after click

---

chrome/content/zotero/customElements.js
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/elements/notesContext.js
chrome/content/zotero/xpcom/reader.js

Since we have a lot of them now and don't need them all on startup. Should speed things up!
Notes:
- Calls of the form `new (customElements.get('ce-name'))` should just be replaced with `document.create[XUL]Element('ce-name')`.
- Calls to `customElements.get('ce-name')` for the purpose of extending one of our CEs will need to be preceded by
```js
if (!customElements.get('ce-name')) {
delete document.createXULElement('ce-name'); // Or createElement
}
```
like we're already doing for Mozilla CEs. (We don't extend any of our own CEs in that way at the moment, though.)

Lazy load CEs

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/components/virtualized-table.jsx

Fixes the issue where long press would not open up context menu in a virtualized table and tab bar because it was handled in mousedown events that longpress on a touchscreen does not dispatch.
This behavior is still observed in the scrollable area of the reader and the note editor.
Addresses: #4094

touchscreen longpress displays context menu

---

scss/components/_tabsMenu.scss

Make sure the vertical scrollbar does not occupy space on mac when the menu is not scrollable even if the "Show scroll bar" setting is "Always"
Fixes: #4121

remove unnecessarry scrollbar in tabs menu on mac

---

chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/itemBox.js

- minor refactoring of blurOpenField to call blur directly on the input of `editable-text`. That is to avoid having multiple 'blur' events triggering `hideEditor` which may cause multiple re-renderings and potentially an infinite loop. It can also interfere with cases when we want to add a new creator row on shift-enter after the first refresh - second unwanted re-render would remove the newly added empty creator row.
- remove call to blurOpenField where it is not necessary and make it non-async. With `editable-text`, the fields blur and the item gets saved whenever you click outside of it, so that's no more necessary and confusing.
- on focusin of the empty unsaved creator row, use its future unsaved id that reflects its positioning instead of its real id (which technically is the very …

Fixes to itembox creator row bugs

---

chrome/content/zotero/xpcom/feedReader.js
resource/feeds/FeedProcessor.js
test/tests/data/feedArticleMetadata.rss
test/tests/feedReaderTest.js

`FeedProcessor` has mappings between namespaced tags and metadata fields, but we were mostly ignoring them and doing the same work in `FeedReader` ([previously noted](https://github.com/zotero/zotero/commit/676ab7852b3d92525137e93ea53ff934bf22f4d9)). This moves the extraction to `FeedProcessor` and adds support for more PRISM fields (under so, so many namespaces) in the process.
Dates fields are no longer parsed in `FeedProcessor`. We didn't seem to use the parse output anyway, and it used the not-great `toUTCString()` function.
A further improvement would be to remove the distinction between maybe-HTML tags, which are stored on the Feed or Entry object as `TextConstruct` instances, and text-only tags, which are stored as plain strings, with no differentiation in property names. Right …

Feeds: Refactor to move field extraction to FeedProcessor

---

chrome/content/zotero/elements/editableText.js
test/tests/tagsboxTest.js

The 'blur' event needs to be dispatched by editable-text before its state is reset (not after) because tagsbox uses .initialValue in the 'blur' handler.
followup to 101e6d55d507723c4d59e79dc304bdba03721953
Fixes: #3575

fix tagsbox enter glitch

---

chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/elements/itemPaneSection.js
chrome/content/zotero/elements/librariesCollectionsBox.js

- By default, rerender is only necessary when tab or item ID changes
- Libraries and Collections box additionally depends on the collection tree row
- Pass `collectionTreeRow` down to item pane sections
Fixes #4154

Allow item pane sections to declare dependencies for rerender, fix Libraries and Collections not updating

---

chrome/content/zotero/elements/itemBox.js
chrome/locale/en-US/zotero/zotero.ftl

Added the field name for the label to be more descriptive. The new announced label is e.g. "Select version of title field".
Followup to https://github.com/zotero/zotero/pull/4096#issuecomment-2121894422

vpat 23: better aria label for itembox merge button

---

test/tests/zoteroPaneTest.js

Make sure that more than one tab is opened before tab navigation tests are run so that the tabs menu is always focusable.
Fixes: #4180

zp tab focus tests pass if run on their own

---

chrome/content/zotero/dateOverrides.js
chrome/content/zotero/zotero.mjs

Behaviour of `toLocaleString` and `toLocaleDateString` seems to have changed between Firefox 68 and 102. Below is the same code running on my system configured to `en-GB` with Zotero configured to `en-US`.
Zotero 6:
Zotero 7:
From what I can observe `toLocaleString` no longer respects locale configured in Zotero and instead uses system's locale. I've also checked current Firefox/Chromium and it seems to exhibit the same behavior.
To fix this, I've tweaked our code to explicitly call `toLocaleString` with `window.navigator.language` as the first argument. A similar treatment might be needed in zotero/utilities.
Resolves #3559

Fix dates not following Zotero's locale.

---

chrome/content/zotero/actors/ActorManager.jsm
chrome/content/zotero/actors/ExternalLinkHandlerChild.jsm
chrome/content/zotero/actors/ExternalLinkHandlerParent.jsm
chrome/content/zotero/preferences/preferences_cite.jsx
chrome/content/zotero/standalone/basicViewer.js
chrome/content/zotero/standalone/basicViewer.xhtml

Generalizes some code from the `FeedAbstract` actor to apply to viewers as well.
Also:
- Remove nonfunctional code that tries to modify CSS on https://www.zotero.org/styles/ - no longer works because the browser is remote (and was no longer necessary anyway).
Fixes #4197

basicViewer: Open links externally

---

chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/integration/quickFormat.xhtml

- reference panel supports multiselect
- Shift/Cmd-ArrowDown/Up from the selected reference panel row will toggle the next item's selected status and focus it
- Cmd-MouseClick on an item from the reference panel will toggle the item's selected status
- Zotero_QuickFormat._bubbleizeSelected adds all selected items before sorting and clearing input
Fixes: #3763

QuickFormat: adding multiple items with shift-arrow

---

chrome/content/zotero/elements/guidancePanel.js
chrome/content/zotero/integration/quickFormat.js
chrome/locale/en-US/zotero/zotero.ftl
chrome/locale/en-US/zotero/zotero.properties
scss/elements/_guidancePanel.scss

- added 8px padding around text on linux. Mac and win already have some padding around text through --panel-padding. Fixes: https://github.com/zotero/zotero/issues/4187
- guidancePanel.js fetches text from .ftl file instead of zotero.properties
- added first-run-guidance-quickFormat to zotero.ftl with updated text to better reflect current functionality. Fixes: https://github.com/zotero/zotero/issues/4191
- removed unnecessary special treatment for qf guidance panel on mac
- moved guidance panel text for itemBox creator menu into zotero.ftl

quickFormat guidance panel fixes

---

chrome/content/zotero/components/tagSelector/tagSelectorList.jsx

If one explicitly selected to "Display all tags in this library", do not jump over disabled tags during arrow navigation. Followup to #3967.
Comment after initial changes this addresses:
The issue is partially resolved. The tags now have the checkbox role, which is sufficient, and they have their state announced when focused and activated. However, when all tags are set to be viewed, the disabled tags are not able to be selected on Windows. This makes it functionally no different from having 'Display All Tags in This Library' off; reasonably, one could expect the user wants to be able to see all of the tags if that option is on. It is fine for the disabled tags to not be in the focus order (navigating by Tab key), but they should still be able to be selected by screen reader cursors …

vpat 11: do not skip over disabled tags during arrow navigation

---

chrome/content/zotero/elements/tagsBox.js
scss/elements/_librariesCollectionsBox.scss
scss/elements/_notesBox.scss
scss/elements/_tagsBox.scss

In itemPane, do not hide the actual "-" toolbarbutton, hide the `<image>`  inside of it. Visually, it looks the same but the button can be focused via tab without having to expicitly make it visible. It means that shift-tab from the section header will not skip the `-` button.
This does not apply to the itemBox, since there is a bit more logic in it and itemBox does not cause vpat issues.
Also, make "remove" toolbarbutton from tagsbox focusable like all others for consistency.
This is a followup to #3953. For reference, this is an example of how the `-` next to the note row gets skipped on shift-tab from "Collection and libraries" section header that this addresses.
https://github.com/zotero/zotero/assets/36271954/17a1aeed-9ab9-4a57-8323-2a09016e2143

vpat 3: make "remove" btn in itemPane focusable even when hidden

---

chrome/content/zotero/rtfScan.js
chrome/content/zotero/rtfScan.xhtml
chrome/locale/en-US/zotero/zotero.ftl

- linked input/output file labels to the input fields so they have a descriptive name
- "Choose file" for both buttons is not context specific. Added separate .ftl entries to have "Choose input file" and "Choose output file" labels.
Note: there are readonly fields that voiceover does not announce as "readonly" - it seems to be a general firefox issue, so this is not addressed here. This is discussed in more details here: #3997

vpat 27: rtfscan - link labels to inputs

---

chrome/content/zotero/elements/editableText.js
scss/elements/_editableText.scss

Unbelievably, this fixes #4208. Really seems like a layout engine bug to me.

`editable-text` CE: Don't modify the DOM in `sizeToContent()`

---

chrome/content/zotero/preferences/preferences_export.jsx
chrome/content/zotero/preferences/preferences_export.xhtml
scss/preferences/_export.scss

"Note format" section in "Export" tab is technically a table and is announced as such by screen readers, which is misleading. It also opens a menulist when a checkbox is clicked, which is not an expected behavior and can shift focus.
This refactors the "Note format" section to be a vbox container with `<checkbox>`es and labels, which is more correct semantically and does not confuse screen readers. In addition, when a chekbox is clicked, dispatch a "change" event instead of unnecessarily open up a menu.

vpat 49: refactor note format preference section

---

chrome/content/zotero/integration/quickFormat.js

- `richlistbox` shift-click selects a range starting with [_selectionStart](https://searchfox.org/mozilla-central/source/toolkit/content/widgets/richlistbox.js#469). After a few cmd/ctrl clicks, `_selectionStart` ends up not being correct - it can even point at an unselected item. To help `richlistbox` properly select a range, before each click is processed, reset `_selectionStart` to be either the first or last selected item, depending on where shift-click landed.
- also, fixed a small glitch where inputs would be created if you click on the red border outside of the actual editor.
Fixes: #4206

qf: improved multiselect range selection

---

chrome/content/zotero/elements/contextPane.js

Instead of trying to focus `editable-text` of the header (which may not be possible), just focus the next node after the header.

Fix focus not moving from reader into contextPane if the header is in bibliography entry mode

---

chrome/content/zotero/bibliography.js
chrome/content/zotero/locateMenu.js
chrome/content/zotero/preferences/preferences.js
chrome/content/zotero/preferences/preferences_general.xhtml
chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/utilities_internal.js
chrome/content/zotero/zoteroPane.js

And:
- Refactor `openPreferences()` for clarity
- Throw when "action" string is passed as second argument
- Use `scrollTo` option in appropriate places
Closes #4215

Preferences: Replace legacy options with single `scrollTo` option

---

js-build/ftl-to-json.mjs
js-build/localize-ftl.mjs
js-build/utils.js
package-lock.json
package.json

This PR:
1. Fixes how messages that reference other messages are handled
2. Messages that only reference other messages are now omitted from produced JSON. This required a tweak to `localize-ftl` so that it now also parses en-US `.ftl` file to re-introduce these into localized `.ftl`. (I hoped that fluent would fallback for `en-US` for a missing string, find that it references something and take the reference again from a localized file, bit unfortunately it does not). Fix #3700. 
3. Removes shenanigans with maintaining list of terms/variables etc. Previously I've tried to keep track of what is a term, what a variable etc. without actually storing that information in the produced JSON. That introduced overhead and complexity. Instead now we just keep the prefix in JSON (i.e. where …

Few fixes to `ftl-to-json` and `localize-ftl` scripts

---

chrome/content/zotero/elements/attachmentsBox.js
test/tests/itemPaneTest.js

`refresh` event comes before `add` when an attachment is added to an item (not sure why), so we end up with a duplicate row. Fix by always removing any existing row before adding a new one.
Fixes #4249

Fix duplicate attachment row from attachments-box `notify()`

---

chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/elements/itemPane.js

Fix pinnedPane set to ItemDetails before tabType is assigned not stored to pref
fix: #4260

Assign ItemPane#_itemDetails default tabType

---

chrome/content/zotero/elements/itemBox.js

To preserve behavior from zotero 6. We likely want to make the creator type menu a proper menulist in the future.
Addresses: #4248

open itembox creator type menu on arrowUp/down

---

chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/reader.js

- if an unloaded tab is being opened, do not close the tab and have reader re-open a fresh tab. Instead, keep the tab as is, have reader use the tab as a container and just change the tab's type. It should fix a glitch on windows when if you click on a tab during initial loading, it will disappear until reader re-adds it. A few tweaks to allow unloaded tabs be generally "selectable".
Fixes: #4149
- during startup loading, select the yet-unloaded tab right away. That way, a tab is almost immediately selected, instead of being stuck on the library tab until the reader is ready.
- if the items are not loaded yet, use a placeholder icon for tabs. Fixes: #4150
- updated handling for reader loading message. When an unloaded tab is selected during initial load, the loading message needs to be …

tabs startup loading optimization

---

chrome/content/zotero/preferences/preferences_advanced.xhtml
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/preferences/preferences_export.xhtml
chrome/content/zotero/preferences/preferences_general.xhtml
chrome/locale/en-US/zotero/preferences.ftl

Hopefully, this is the last of aria edits for the preferences window. 
- linked color scheme radio buttons to their label. Using aria-describedby on individual radio buttons instead of linking color scheme label to radiogroup because voiceover does not announce the label in that case.
- linked item pane header dropdown to its label
- linked markdown and richtext note format checkboxes to their labels.
- added aria description to linked attachments base directory so the input and "choose" button
- linked virtualized tables to their labels
Data directory location setting needs some more labeling as well but it's mechanics should be generally reworked per vpat 50 and it should be all addressed in #4048 
For reference, the latest VPAT feedback:
---
Still affected on Mac and windows (meaning …

vpat 46 followup: more aria for preferences inputs

---

chrome/content/zotero/elements/itemBox.js

- remove unsaved creator row on escape and on blur. The blur part is a bit tricky, since we want to remove the empty unsaved creator row on blur only sometimes. For example, the focus leaves the `editable-text` when you click on the options menu or open the creator type dropdown but the row should not be deleted. So I went with the following logic: delete unsaved creator row if the focus lands outside of the itemPane (e.g. you click on the item tree) or if the focus lands on an input outside of the row. Correct me if this sounds off.
- add switch creator mode button to unsaved creator row instead of the always disabled `+` button.
- fix unsaved creator focus glitch on save. If you add a new row, type something and then click on the creator row below it, the focus will jump to the row …

Tweaks to itembox unsaved creator row

---

chrome/content/zotero/xpcom/reader.js

Fix to breakage after 3f45def that would not open a duplicate tab but instead create another reader instance in the same tab. Instead of finding a tab for a specific item, use tabID that is passed when reader should be loaded in an unloaded tab. That allows us to know if the tab is being duplicated or not.
Fixes: #4272
https://github.com/zotero/zotero/assets/36271954/63fbc4dc-852e-49ea-8b3c-841577226cdd

Fix tab duplication breakage

---

chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/zoteroPane.js

- only have enabled "Permanently delete" and "Restore to library" options in the context menu for trashed collections and searches
- display the custom header with buttons to delete or restore in the itemPane when a trashed collection or search is selected
Fixes: #4295
https://forums.zotero.org/discussion/comment/466736/#Comment_466736

Show correct context menu and itemPane header for trashed collections

---

chrome/content/zotero/elements/itemBox.js

`this._addCreatorRow` needs to be properly initialized to `false` (as opposed to being undefined) because `false` is the value we check against to decide if an empty row should be added and focused after rendering.
Fixes: #4268
"More creator rows" click would always add an empty row. If there are not enough creators, the empty row would sometimes appear, I believe, depending on if itemBox is rendered only once or not.
https://github.com/zotero/zotero/assets/36271954/0002b6f6-0187-4225-b800-915c3f71ed1f

Fix unwanted empty creator row in itemBox

---

chrome/content/zotero/elements/itemBox.js

- always render options and link buttons - just do not display them if their respective field is empty. That allows us to easily handle focus after refresh because otherwise, the node may does not exist.
If we try to restore focus to such hidden component, simulate a "tab" from it to focus the next possible node. This fixes the issue of focus being lost on tab after all content of editable-text is cleared.
- add tabindex=0 to itemType menulist, otherwise it was not perceived as a candidate to return focus to.
- somewhat special treatment for restoring focus to creator rows. If the desired node is not found, we'll try to focus the respective node in the last creator row. It prevents focus from being lost on tab after clearing the very last creator.
Fixes: #4241 …

Prevent focus from being lost in itemBox

---

scss/win/_menupopup.scss

Only set display: none on the icon element when we actually don't have an icon to show.
Fixes #4273

Fix missing icons in menulists on Windows

---

scss/components/_search.scss

With minor tweaks to positioning.
Fixes: #4299
Positioning tweaks added to not have the button pushed so far into the input.
Before:
After:

Fix X button not appearing in tag selector

---

chrome/content/zotero/elements/attachmentsBox.js
chrome/content/zotero/zoteroPane.xhtml

And remove a duplicate ID.
Fixes #4298

Attachments box: Build Add menu locally instead of cloning

---

chrome/content/zotero/elements/collapsibleSection.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.ftl

- added role=button to the itemPane header
- twisty button's tooltip will include the section's name, e.g. "Expand info section".
Post: #3957 (vpat 15 and vpat 6 are duplicates)
Vpat comment after the initial edits this should address:
The issue is partially resolved. The various sections of the 'Item Pane' now have names. They are missing button roles, however; they can be activated to expand/collapse the section. The dedicated expand/collapse buttons should include the section in their names. Right now, they are all 'Expand section'/'Collapse section.
Initial issue description:
There is a pane of items with what seem to be "related", "tags", Libraries and collection", "notes", and possibly more. These buttons may expand or collapse more sections, and all of these buttons, and mentioned …

vpat 15: more detailed labels for itemPane

---

chrome/content/zotero/elements/editableText.js

Canvas text measurement apparently isn't 1:1 with DOM text rendering on all displays, so we need to do _something_ to put the text in the DOM and measure it. But anything that triggers a relayout after modifying the DOM (`getBoundingClientRect()`, `offsetWidth`, `scrollWidth`, ...) causes the overlap bug that was fixed in #4214. So we use the `hiddenDOMWindow`, where we can safely do whatever we want to the DOM without causing quantum tunneling issues.
Fixes #4315

Use span in `hiddenDOMWindow` to measure text width

---

chrome/content/zotero/elements/duplicatesMergePane.js

Since the header of the collapsible section is not visible, there is no way to expand the itemBox if it was collapsed before dulicate items are selected. With this, itembox is always opened when a new set of duplicate items is selected.
Fixes: #4318

always open duplicatesPane itembox

---

chrome/content/zotero/elements/librariesCollectionsBox.js
chrome/content/zotero/xpcom/data/collection.js
chrome/content/zotero/xpcom/data/items.js
test/tests/collectionTest.js
test/tests/itemPaneTest.js

- listen to `collection` notifier events and re-render  the section if a relevant collection is trashed or modified. That way, a trashed collection will be removed, restored collection will be added back and renaming a collection will update the name in the librariesCollectionsBox.
- fixed a bug where a restored collection would not be added into `item._collections` cache. Fixed false-positive test for it.
- do not add trashed collections into `item. _collections` cache in `Zotero.Items._loadCollections`. Otherwise, trashed collections will appear in librariesCollectionsBox after the app is restarted.
Fixes: #4307

 Fix to stale or incorrect trashed collections data appearing in librariesCollectionsBox

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/tabs.js
scss/components/_tabBar.scss

This update implements a check for overflowing tabs and applies the fading edge effect only when necessary. This check happens whenever tabs change as well as on window resize. I've reused the `onResize` handler and added throttling to reduce CPU burden when resizing.
Furthermore, I have optimized the tab bar to reduce the number of re-renders. Although the overflow detection introduces some overhead, the overall performance impact of this pull request should be positive.
Fix #4330

Don't fade right edge of a tab if text doesn't overflow + optimizations

---

chrome/content/zotero/rtfScan.js

When porting RTF Scan, I've kept the logic unchanged. However, I've now noticed that unmapped citations are always classified as ambiguous due to an invalid check (`Zotero.Search` returns an empty array if no results are found, and that is truthy, so we need to check for length instead).
I've tracked this back to the [original code](https://github.com/zotero/zotero/blame/f274323478bbc0fb26aa876a832197add76891d8/chrome/content/zotero/rtfScan.js#L233), so perhaps `Zotero.Search` has changed in the meantime or maybe it has never worked - or maybe I'm missing something?

Fix RTF Scan never marks citations as unmapped

---

chrome/content/zotero/xpcom/data/collection.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/data/items.js
chrome/content/zotero/xpcom/data/search.js
test/tests/collectionTest.js
test/tests/itemTest.js
test/tests/searchTest.js

- revert change from 2401a34031799fd7c28efe75b6c4a3036fad3987 that only loads un-trashed collections in `_loadCollections`. If an item only belongs to deleted collections, `item._loaded.collections = true` from `_loadCollections` will never run, so an exception will be thrown in `item.toJSON()` when syncing happens. Instead, to address the problem of `item.getCollections()` having stale data #4307, add 'includeTrashed' parameter to `item.getCollections()` based on which `item._collections` will be filtered. Fixes: #4346
- revert earlier, no more necessary, changes from a532cfb4759eb37bbf4952331ab20c43c65e6918 to not alter `item._collections` cache when collections are being trashed or restored. Collection is removed from `item._collections` only when it is permanently erased.
- removed …

Revised logic of trashed collections in item cache

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/recognizeDocument.js
chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/zotero.properties
test/tests/itemTreeTest.js
test/tests/recognizeDocumentTest.js
test/tests/zoteroPaneTest.js

And tweak `addAttachmentFromDialog()`:
- Accept a `files` argument for tests (`FilePicker#show()` can't be mocked)
- Return the added attachments
`setFirstAttachmentTitle()` is a kind of awkward method, but it encapsulates logic that we need in a few different places. The alternative would be to expose `_getDefaultTitleForAttachmentContentType()`, pass whatever it returns into `setField()`, and only run the `isFirstOfType` check in places where there could actually be other attachments (manually adding attachments to existing items, basically). Not sure that's that much better.
Needs #3860 (though I think any conflicts with that would be pretty minor; current conflict with `main` is from there). Addresses #4211 for Create Parent Item, Retrieve Metadata, and manually added attachments.

Set automatic title on first child attachment of each type

---

chrome/content/zotero/tabs.js

So that after reload, we can display the correct icon sooner
Fixes: #4342

Cache tabs' icons in data field

---

scss/base/_base.scss

`-moz-accent-color` variable doesn't seem to exist on linux. Use `--color-accent` as the focus border, same as what is already done in the reader.
Fixes: #4340

fix focusring not appearing on linux

---

chrome/content/zotero/customElements.js
chrome/content/zotero/elements/autocompleteTextArea.js
chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/xpcom/data/itemFields.js

- Add `autocomplete-textarea` CE
- Use it to enable autocomplete on `editable-text`s that wrap
- Enable autocomplete on all `isAutocompleteField()` fields in `item-box`
- Optimize `isAutocompleteField()` by caching and storing in a Set
- Optimize various field name checks in item box - `includes` -> `startsWith` (future-proofs them too, I guess, since we might someday have a field with the string `creator` somewhere in its name that isn't actually a creator)
Fixes #4360

Enable autocomplete on long fields, optimize some code

---

chrome/skin/default/zotero/integration.css
scss/base/_base.scss
scss/components/_richlistbox.scss
scss/components/_virtualized-table.scss
scss/elements/_richlistCheckbox.scss

I can't test on Linux, unfortunately, but this should fix #4349 (assuming the system color scheme's colors don't clash).

Use `SelectedItemText` color on `SelectedItem` backgrounds

---

js-build/babel-worker.js

React 18 introduced automatic batching which tries to avoid unnecessary re-rendering (https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching). In some components based on `react-virtualized` (e.g. tag selector), it leads to visible lagginess on scroll via keypress or mouse wheel (not trackpad). This patch wraps setState of the scroll handler of `react-virtualized` with `ReactDOM.flushSync`, which opts out of automatic batching.
Fixes: #4368
Make sure to run `npm run clean` before `./app/scripts/build_and_run -rd` to have `babel-worker.js` rerun.

Patch react-virtualized to fix react 18 scroll lag

---

chrome/content/zotero/integration/quickFormat.js
chrome/skin/default/zotero/integration.css

- properly determine between which two bubbles a click landed
- set input direction
- delete the bubble on the left of the cursor
- in rtl, use selectionStart as the expected end of the input and selectionEnd as the start. It fixes the issue of the cursor getting stuck at the end of the input, as well as fixes the Home/End not working from the right end.
- fix spacing issues for item descriptions in both layouts
Fixes: #4371
https://github.com/zotero/zotero/assets/36271954/32155a36-d1cf-47ab-8a9f-52eb48790c1d

quickFormat rtl layout fixes

---

js-build/babel-worker.js

Followup to #4370, per https://github.com/zotero/zotero/pull/4370#discussion_r1674336402

Remove unneeded .trim from react-virtualized patch

---

chrome/content/zotero/searchDialog.xhtml
scss/elements/_zoteroSearch.scss

- remove padding between the `<dialog>` and the window edges
- explicit width for all zoterosearch fields because otherwise a menulist with a long content (e.g. longer collection name) name can push the + and - buttons outside of the window
Fixes: #4374
Before:
After:

fixes to saved search dialog layout

---

scss/merge.scss

fix: #4138
Before: https://github.com/zotero/zotero/pull/4130#issuecomment-2117465957
Current:

No focus ring and background in CR readonly fields

---

chrome/content/zotero/tabs.js

When tabs' state is updated, refresh library tab's icon. Do not skip it if the icon already exists (as for reader tabs). Otherwise, when selected row from collectionTree changes, the icons in the library tab will not update.
Fixes: #4385
https://github.com/user-attachments/assets/2c7c0416-adb7-4a08-8133-1232eeaa9557

Refresh library tab's icon cache on update

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/zoteroPane.js
test/content/support.js
test/tests/annotationsTest.js
test/tests/attachmentsTest.js
test/tests/translateTest.js
test/tests/zoteroPaneTest.js

By moving the `setAutoAttachmentTitle()` calls to `importFromFile()` / `_addToDB()`. I think this is better because it eliminates the extra save (which sometimes meant briefly displaying the "wrong" title, and generated an error in `attachment-box` due to the attachment changing during render).
Also:
- Chop off file extension when setting the parent's title based on the filename in Create Parent Item -> Manual Entry.
- Fix Manual Entry not renaming the attachment correctly by awaiting `createEmptyParent()`.
Further addresses #4211 (Manual Entry, collection tree drops).

Set automatic titles in more or less all cases

---

chrome/content/zotero/elements/abstractBox.js
chrome/content/zotero/elements/itemPaneHeader.js

As opposed to `change` event.
Because if the field is editted and another window is focused while the cursor is in the field, the change event will be swallowed and when the field finally looses focus, it will not be saved.
This may address the reported [issue](https://forums.zotero.org/discussion/comment/468039/#Comment_468039) of edits not being saved in title and abstract fields.
Addresses: #4388

save itemPane title/abstract fields on blur

---

chrome/content/zotero/xpcom/attachments.js
test/tests/attachmentsTest.js

This PR improves automatic file renaming logic so that prefix/suffix is suppressed if it would result in repeated prefix/suffix character in the final file name.
Resolve #3317

File renaming: suppress duplicate suffixes #3317

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTree.jsx

- set `aria-activedescendant` in `_onSelection` handler of virtualized table. For simpler virtualized tables (e.g. style manager in Zotero_Preferences.Cite), the table does not get re-rendered when selection changes, so `aria-activedescendant` does not get updated in `render()`, which means the screen reader is just quiet.
- construct and set aria-label for rows build via `makeRowRenderer` of VirtualizedTable so that is is announced when the row is selected

vpat 48: announce selection for default virtualized table

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/tabs.js
scss/components/_tabBar.scss

After react 18 update, the tab node may not yet be rendered by tabBar.jsx when we try to scroll it into view in Zotero_Tabs.select.
- To make sure scrolling happens when rendering is done, move scroll-related logic into a `useEffect` of tabBar.jsx. It also makes sure that we'll scroll to a selected tab if it is moved via context menu to the very beginning or the end.
- Added a small scroll-padding to tabs' container to make sure the border does not get cutoff after the tab is scrolled into view. This is instead of JS code accounting for the border.
- Fixed a glitch where the pinned library tab would not get selected on shift-tab from opened tabs menu.
Fixes: #4382

Fix tab not scrolling into view

---

chrome/content/zotero/actors/ActorManager.jsm
scss/components/_mainWindow.scss
scss/win/_menupopup.scss

- Mozilla's `ActorManagerParent` was only being imported when devtools were initialized (either by opening the Error Console or by connecting via remote debugging). Import it in our `ActorManager` so Mozilla actors, including `AutoScroll`, are always registered.
- This may have other effects! I'm assuming most of us test with the error console visible, though, so we would've had Mozilla actors, while users running without devtools wouldn't have. We definitely want those actors. (Most of them, at least.)
- Don't override autoscroller styles with our panel customizations.
Fixes #4384

Restore autoscroll support in reader

---

chrome/content/zotero/xpcom/reader.js

`<panel>` takes over Escape handling by just closing the popup via what looks like a capturing listener on `document`, since Escape keydown events never even reach the popup itself. When the popup is just closed like that, tagsBox is blurred so all unwanted edits get saved.
To properly handle Escape, attach our own capturing listener that will reset all edits before the popup is closed.
Followup to https://github.com/zotero/zotero/commit/a73035c848668d2c03a7e81a7897e2a67e5b7b2d
Fixes: #4398

do not save edits on Escape in reader tags popup

---

chrome/content/zotero/advancedSearch.js
chrome/content/zotero/elements/zoteroSearch.js
chrome/content/zotero/searchDialog.js
chrome/content/zotero/searchDialog.xhtml

Instead of focusing the first condition, which ends up placing focus in the middle of the new window or modal. It is best to focus the first node, which is the general convention, per https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/, and what many screen reader users expect. When we focus a field in the middle of the window/dialog, it makes it seem for some users that this is the first node, which will make them miss all the fields above it.
Also, linked search name input to its label in searchDialog.xhtml.
For reference, comment from the vpat issue:
"Impact Statement: When focus is placed in the middle of a modal, verses being placed at the beginning of the content, it is likely that fields may be overlooked. Additionally, this may cause frustration as the user must backtrack to …

vpat 80: focus first field in search window/dialog

---

chrome/content/zotero/selectItemsDialog.js
chrome/content/zotero/selectItemsDialog.xhtml
scss/components/_selectItemsDialog.scss

Looks neat!
I didn't touch the other dialogs that use the same infrastructure (classic Add Citation, Edit Bibliography). The latter, at least, could do with a touch-up, but I don't think we have a mockup for that yet.
Closes #4320

Implement Select Items dialog redesign

---

chrome/content/zotero/selectItemsDialog.js

After redesign, tab order became: quickSearch -> itemTree -> cancel and accept buttons -> collectionTree.
This restores original tab sequence: quickSearch -> collectionTree -> itemsTree -> cancel and accept buttons.

Select Items Dialog: restore tab order

---

chrome/content/zotero/elements/zoteroSearch.js
chrome/content/zotero/preferences/preferences_general.js
chrome/content/zotero/preferences/preferences_general.xhtml
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/data/feed.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/editorInstance.js
chrome/content/zotero/xpcom/intl.js
chrome/content/zotero/xpcom/reader.js
chrome/locale/en-US/zotero/preferences.ftl
chrome/locale/en-US/zotero/zotero.ftl
chrome/locale/en-US/zotero/zotero.properties
test/tests/attachmentsTest.js
test/tests/itemTreeTest.js
test/tests/recognizeDocumentTest.js
test/tests/translateTest.js
test/tests/zoteroPaneTest.js

Closes #4429, except I kept matching on MIME types only and just expanded it to accept prefixes. We don't always have a reliable file extension at the point where we decide whether to rename (`importFromURL()` - we just guess from the MIME type a lot of the time there).
The UI looks awful right now:
Suggestions would be appreciated! (Changing the label to just "Rename:" looked worse, removing the indent looked way worse...)

File renaming: Match content type prefixes, add UI

---

chrome/content/zotero/components/virtualized-table.jsx

Tweak to the conditional to check if something is focused via `selection.count` (instead of `selection.focused` which defaults to 0 and fails on the very first item).
Post: 40fd5efe05bc2f0cf3abaf6b47b44408d39d0d38.
Fixes: #4444

Fix first row of itemTree not getting announced

---

chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/zoteroPane.js
test/content/support.js
test/tests/attachmentsTest.js
test/tests/zoteroPaneTest.js

Except from Rename File from Parent Metadata.
Fixes #4445

Don't set default attachment title if not renaming file

---

chrome/content/zotero/components/createParent/createParent.jsx

And normalize some code style.
I think the focus broke because the XUL window focuses on the first focusable element on load, but async rendering causes the input field not to exist in the DOM until slightly later. Probably better to be explicit about autofocus anyway.
Fixes #4469

Autofocus input in Create Parent Item dialog

---

chrome/content/zotero/components/annotation.jsx
chrome/content/zotero/components/createParent/createParent.jsx
chrome/content/zotero/createParentDialog.js
chrome/content/zotero/elements/mergeGroup.js

I don't know if this will address the hang in #4471, but calling `ReactDOM.createRoot()` multiple times on the same node [is invalid](https://stackoverflow.com/questions/71792005/react-18-you-are-calling-reactdomclient-createroot-on-a-container-that-has-a) and would throw an error rather than actually rerendering. This also eliminates the global state in `Zotero.CreateParent` and `Zotero.AnnotationBox`.

Create Parent Item (& `Zotero.AnnotationBox`): Only call `ReactDOM.createRoot()` once

---

chrome/content/zotero/lookup.js
chrome/skin/default/zotero/overlay.css

Before:
After:
That 16px offset is no longer necessary on macOS or Windows, and the 10px CSS padding added in the redesign was just moving it further away (because the padding actually works as a margin on `<panel>` elements - it doesn't pad the content inside the panel widget, but instead adds empty space around it).
Also linted.

Add by Identifier: Fix popup positioning

---

.babelrc
js-build/babel-worker.js
js-build/config.js
resource/react-dom-server.js
resource/react-dom.js
resource/react-intl.js
resource/react.js

Also, I removed the patching for `react` and `react-dom`, as it doesn't seem to be required anymore. These can now be linked instead of being babel-processed.
I only had a brief look, but it doesn't seem to break anything.
If we want to, we could use development versions outside of production (to include extra warning messages in that version). However, we would need to have two different processes, e.g., `npm start` for development and `npm build` for production.
Fix #4481

Use production builds of react libraries

---

chrome/content/zotero/preferences/preferences_advanced.xhtml

The settings was writing to the wrong preference key, code tested on macOS

Setting - Feeds fix misaligned unread/read cleanup option

---

chrome/content/zotero/preferences/preferences_general.js
chrome/content/zotero/preferences/preferences_general.xhtml

IMO this also just looks better:
(Keeping the checkboxes below "Rename linked files" looked wrong, and arguably the checkboxes controlling which file types to rename in *all* cases are more immediately relevant to the parent "Automatically rename locally added files" pref than the linked files checkbox is.)
Addresses #4485

File Renaming: Rearrange prefs

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/recognizeDocument.js
chrome/content/zotero/zoteroPane.js
test/tests/recognizeDocumentTest.js
test/tests/zoteroPaneTest.js

Don't change the filename or title unless auto-renaming is enabled for the attachment link mode and content type.
Closes #4484

Retrieve Metadata & Create Parent: Use `autoRenameFiles.fileTypes`

---

chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/zoteroPane.js

Do not use specific `#item-tree-main-default` selector to find the itemTree node to focus since a different id can be set for the table, e.g for the list of feeds.
Use a more general `#zotero-items-tree .virtualized-table` selector to focus the itemTree on tab from quickSearch and on Escape keypress from an `editable-text` of itemPane.
Fixes: #4494

Fix keyboard focus not landing on feeds itemTree

---

chrome/content/zotero/elements/tagsBox.js
test/tests/tagsboxTest.js

On shift-Enter from any tag, add a new empty tag at the bottom and focus it. Alternative to tabbing to + button and clicking it.
Fixes: #4394

Tagsbox: focus new tag row on shift-enter

---

scss/win/components/_button.scss

Fix button selector specificity on Windows

---

chrome/content/zotero/feedSettings.xhtml
chrome/skin/default/zotero/zotero.css
scss/_zotero.scss
scss/components/_feedSettings.scss

- `<hbox>` -> `<button>`, `<toolbarbutton>` -> `<dropmarker>`
- Extract styles to SCSS and use `focus-ring` mixin
Needs [this fix](https://github.com/zotero/zotero/pull/4466/files#r1705740392) in order to have correct padding on Windows.
Fixes #4512

Feed settings: Make disclosure triangle focusable, extract SCSS

---

chrome/content/zotero/elements/textLink.js
scss/components/_textLink.scss

Fix regression after 117197e11d1e92e9d5eea5c4a3369c61fd5e65cc where space or enter would not trigger a click on a link outside of the main window.
`.keyboard-clickable` is handled by listener in `ZoteroPane`, so links outside of it (e.g. in preferences) are not affected by it. For now, just explicitly handle `keypress` event by the zotero-text-link component.
Also, added a focus-ring around the link so it is visible when it is focused.
Fixes: #4521

prefs: fix text-link not clicking on space/enter

---

scss/win/abstracts/_mixins.scss

Fix tab bar button hover effect on Windows
A follow up fix of #4518

Remove form element rule !important suffix on Windows

---

chrome/content/zotero/integration/quickFormat.js
chrome/skin/default/zotero/integration.css
scss/themes/_light.scss

So that on windows, the separator text on white background has a high enough contrast ratio for accessibility.
Old `gray` color (`rgb(128, 128, 128)` or `#808080`) for separator text has a contrast ratio with the white background of reference box of ~3.94, which is below all minimum requirements.
This makes separator text a bit darker `rgb(87, 87, 87)` or `#575757` to make sure there is more contrast.
Tested via: https://webaim.org/resources/contrastchecker/
Before:
After:

vpat 59: make quickFormat reference box separator text darker

---

chrome/content/zotero/standalone/standalone.js

- vpat 31: mark which menuitems' button is checked, otherwise selected options (e.g. Update plugins automatically) are not announced as such
- vpat 33: when plugin details pane appears, remove a misleading role="tabpanel" from its section because it is not structured as a collection of tabs
---
Vpat issues for reference:
- 31: Description: In the Zotero desktop app's 'Add-ons Manager' modal, activating a link for an add-on opens more details about that add-on. The content following the initial section containing the add-on name is incorrectly announced as a tab panel by screen readers. However, the content is not structured as a tab panel and should not have this role.
- 33: Description: Throughout the Zotero desktop app, some menu items can be activated or deactivated, such as the …

vpat 31 and 33 - aria tweaks for Tools > Plugins

---

chrome/content/zotero/components/tabBar.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/utilities_internal.js
test/tests/itemTreeTest.js
test/tests/tabsTest.js

- Extract `renderItemTitle` to ZUI
- Render citeproc.js markup in `<Tab>` component
- Make a couple `.tab` selectors more specific
Fixes #4592

Render citeproc.js markup in tab titles

---

chrome/content/zotero/zoteroPane.xhtml
scss/components/_mainWindow.scss

Tweaked colors, removed shadows, and added rounded borders. I've also moved some styles to `.scss`.
MacOS:
Windows:
Resolve #4589

Fix progress bar ignores color scheme.

---

chrome/content/zotero/standalone/standalone.js

Add non-localized labels to the X button next to the input filter and the actual console textarea.
While these issues are not likely to affect anyone, they are still part of the VPAT review and we do want them marked as "done"... 
Because this really is a window not meant for the end user, I assumed we don't need to add localization (same way it's done in for the developer menus in `zoteroPane.xhtml`), so I just hard-coded english strings. Correct me if that's wrong.

vpat 34-5: aria labels for the error console

---

chrome/content/zotero-platform/win/integration.css
chrome/content/zotero/integration/insertNoteDialog.xhtml
chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/integration/quickFormat.xhtml
chrome/skin/default/zotero/integration.css

I could not reproduce this issue https://forums.zotero.org/discussion/117023/disappearing-add-citation-bar, however in the past I ran into `background: transparent` causing problems on windows, so that is likely the culprit https://github.com/zotero/zotero/pull/3889#issuecomment-2035228247. Last time, we went with very specific chromemargin values that I [stumbled upon ](https://github.com/zotero/zotero/pull/3889#discussion_r1547869959) which seemed to have helped. It looks like it helped in some but not all cases, so maybe we try to get rid of `background: transparent` now?
This gets rid of  `background: transparent` and `chromemargins` on windows. We also have to remove `border-radius` on windows because otherwise the corners of the actual window are now visible around the QF dialog. …

Qf: potential fix to the dialog becoming invisible

---

chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/integration/quickFormat.xhtml

And remove no longer needed JS logic hiding and displaying the panel to keep it next to the dialog.
Per: https://github.com/zotero/zotero/pull/4603#issuecomment-2311632716

qf: remove some post-fx115  reference panel positioning complexity with type="arrow"

---

chrome/content/zotero/customElements.js
chrome/content/zotero/newCollectionDialog.js
scss/components/_menu.scss
scss/xulElementPatches/menulist.scss

Switched to a more generic approach to fix missing dark mode icons in popup menus in a few places (two?) on macOS. This resolves issue #4654.
Additionally, on macOS, we use `currentColor` for these icons, while on other operating systems, we use a slightly dimmed `--fill-secondary`. Some of macOS-specific styles leaked, causing a subtle inconsistency in some places, which should now be corrected. See example below.
Before:
After:

Fix a couple of issues related to dark mode icons

---

chrome/content/zotero/customElements.js

- vpat_7: when a popup is showing, mark menuseparators with role="presentation" to clear whatever semantics a separator has. It prevents the screen readers from counting it as an interactable element while announcing the index of a menuitem within the popup. It also makes the screen readers count items across all sections, instead of stopping at the first separator.
- vpat_14: when the popup is hiding, delete the popup and immediately re-insert it into the DOM. It forces voiceover to move cursor back to the focused element. Otherwise, it is not aware that the popup went away, the cursor gets stuck on the invisible element, and if it happens, no elements will be announced until the screen readers is reloaded.

vpat 7,14: popups count and cursor fixes

---

chrome/content/zotero/preferences/preferences.xhtml
chrome/content/zotero/preferences/preferences_advanced.xhtml
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/preferences/preferences_export.xhtml
chrome/content/zotero/preferences/preferences_general.xhtml
chrome/content/zotero/preferences/preferences_sync.xhtml

- explicitly add aria-labels to groupbox and vbox sections of the settings. It's required for voiceover to announce that label when focus enters the group.  It's not needed for NVDA and JAWS as they recognize most h2 labels as labels of grouppings.
- add all relevant additionl text for the section as aria-description/aria-describedby so it is announced after the section's name when focus enters it
- add role="group" to vbox sections, since vbox does not have any semantics
- skip tabstop on scrollable "#prefs-content" container since it is not required
Essentially a different (likely better per https://github.com/zotero/zotero/issues/3930#issuecomment-2251045406) approach to #4414. The main problem here is JAWS as it does not want to activate the virtual cursor inside of dialog. An …

vpat 25: make all relevant text and section headers in preferences announceable

---

chrome/content/zotero/elements/attachmentBox.js
chrome/content/zotero/elements/attachmentsBox.js

resolve: #4611
Try to avoid race condition in dense render calls.
We used to notify the preview to update
after all other renders are done,
which can cause unexpected race condition.
fix: #4659
This bug is mainly from the misaligned flag variable name in attachment box implementation while the early-return of the render function also contributes to it. Should be fixed now.

Fix attachment box preview discard and try to avoid race condition

---

chrome/content/zotero/contextPane.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/skin/default/zotero/overlay.css
scss/abstracts/_variables.scss
scss/components/_collection-tree.scss
scss/components/_contextPane.scss
scss/components/_item-tree.scss
scss/components/_mainWindow.scss
scss/components/_toolbar.scss
scss/elements/_itemPane.scss

fix: #4669
Replace flex attribute with flex-shrink and flex-grow style
to allow elements to be resized by splitter and window resizing.
Set the max-width on collections pane
to prevent it from pushing other panes outside window border
Set the min-width on window according to
the size of both library and reader tabs

Fix main window layout and window resizing

---

chrome/content/zotero/preferences/preferences_general.xhtml
chrome/locale/en-US/zotero/preferences.ftl

A number of small tweaks after the last review.
- it was marked that `+/-` buttons below the cite manager table should have "Add" and "Remove" aria labels because "+" and "-" are not descriptive enough. There is a tooltip that is also announced so I don't think there is much room for confusion here. But `+/-` below export settings do have "Add" and "Remove" so it's worth adding them even just for consistency.
- the "Color scheme" radiogroup had its radio buttons linked to the label via `aria-describedby`. It was indicated that it's not a good thing because semantically it's not quite correct and  it also requires a setting to be checked in JAWS to be heard. Wrapping it into a groupbox will have screen readers announce the "Color scheme" when focus lands on a radiobuton. It feels more …

VPAT: minor settings tweaks 

---

chrome/content/zotero/xpcom/utilities_internal.js

Tweak to `Zotero.Utilities.Internal.activate` to make it more likely that dialogs receive focus when opened on win. Addresses the issue of QF not becoming focusable after the first opening from microsoft word and makes it clearer if the dialog appeared but could not be pulled to the foreground.
`getAttention()` is meant to flash the icon in the app bar if the window could not be focused and pulled into foreground, for example with google docs. During testing, it actually pulled the window forward with this setup, so in google docs, the QF is always focused for me now.
`focus()` fixes the issue of QF not getting focused with word on the first opening. Also, without it, a call to `getAttention()` interferes with focus landing on the dialog during subsequent opening in gdocs.
So a …

QF: increase likeliness of dialogs receiving focus

---

chrome/content/zotero/elements/itemBox.js
test/tests/itemPaneTest.js

- shift enter on a creator row will add a new empty creator row after focused row. If shift-Enter is on the last creator before "More creators", all creators will be rendered.
- fixed encountered glitch where switching the mode of creator would not always update the pref, so next time a new creator row is added, it would not be of correct mode.
- fixed encountered bug where a newly added creator row could receive an index of an existing creator that is not rendered (when "More creators" label is displayed). In that case, saving such creator would override an existing creator and erasing that creator would remove invisble creators.
- added a few tests for these edge cases
Fixes: #4393
Fixes: #4710

itembox: shift-enter adds new creator + bug fixes

---

app/assets/prefs.js

Holding Ctrl and scrolling does not dispatch a scroll event as it is used for zooming in/out. To allow one to scroll through collectionTree while holding Ctrl, listen to `wheel` event and scroll manually based on that. I'm using `e.deltaY * 10` to determine how far scroll, and it works OK though a bit different from proper scrolling. On some platforms, it's just a bit faster and on others - just a bit slower. I assume there is a lot of variation here, so not sure if there is a way to get a perfect value by how much to scroll.
Addresses: #4722

Allow to scroll collectionTree during highlighting via control

---

chrome/content/scaffold/scaffold.js
chrome/content/zotero/xpcom/translation/translators.js

This should be a big usability improvement, since error highlights could previously fall out of sync with the text between saves, which was confusing.
- Includes API changes in `Zotero.Translators` in order to support in-memory translator serialization.
- Type changes in docstrings are corrections, not code changes.

Scaffold: Run ESLint continuously, not just after save

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/selectItemsDialog.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.ftl
scss/components/_selectItemsDialog.scss
test/tests/zoteroPaneTest.js

- added "Change Parent Item" context menu option to itemTree as a non-drag-drop alternative to changing the parent of attachments or notes
- context menu option appears only when all selected items are non-regular items
- upon activation, a dialog to select the new parent will appear. Added a tweak to the dialog to disable the "accept" button if a selected item is not top level
- minor edit to itemTree to set the multiselect property based on a prop, since we do not want to have multiselect enabled in this instance
- when the new top-level item is picked, set that new item as a parent of the selected items
Addresses part of https://github.com/zotero/zotero/issues/3970

vpat 16: context menu as a drag-drop alternative to change parent item of attachment/note

---

chrome/content/scaffold/scaffold.js
chrome/content/scaffold/scaffold.xhtml
scss/scaffold.scss

Do not move focus from the tab onto the editor/input, during keyboard navigation to not change context per https://www.w3.org/WAI/WCAG21/Understanding/on-input. 
Based on the success criteria above, it seems like it is desired to avoid context (specifically focus in our case) changes during tab navigation in general. Avoiding it completely would be detrimental to overall functionality, since it's way better for the input to be focused after you click on a tab. So I thought this could be a reasonable compromise that's also somewhat close to what firefox does: if you switch tabs via clicking, the focus will move into the selected tab panel but if you select a tab with keyboard, focus remains on it?
---
VPAT 44 description for reference:
In the Zotero desktop app's 'Translator'/'Scaffold' …

vpat 44: scaffold keyboard tab selection focus

---

app/win/installer/installer.nsi

This PR adds a check for whether the user is an admin in the `UninstallOld` routine. If not, and the directory still exists at the end of the routine, it displays an error message and exits.
However, we don’t check if the user selected an empty directory for installation, so just re-running the installer will work. That makes me wonder if removing old Zotero should be a "best effort" approach. We could remove `/REBOOTOK` from that section, and if some files are left over, we could just ignore them and proceed with the installation.
This solution should address the most common issue causing the reboot loop, but we should also consider other cases, especially for users who have already run the previous version of the installer and are now stuck in the loop. I'll look into these other cases …

Check for admin privleges in UninstallOld installer routine

---

chrome/locale/en-US/zotero/reader.ftl
chrome/locale/en-US/zotero/zotero.ftl

Remove logic constructing a11y announcements from reader.ftl. Instead, reader will fetch and put together sentences as needed on the fly.
Followup to https://github.com/zotero/zotero/commit/cde21ac9f2407856d000ea2038ea49cee7e8dd7c per https://github.com/zotero/zotero/pull/4752#discussion_r1800481917
Also, add `{ command-or-alt }` to zotero.ftl and use it for textual annotations instructions. On mac, the end of highlight and underline annotations is resized via Shift+Command+arrows, which is different from the Options modifier used in all other instances (per https://github.com/zotero/reader/pull/138#issuecomment-2373775068). I must have missed that the modifier is different earlier.
Finally, tweak aria-description of "Find in document" as it sounded as if Control+Option/Alt+1 would create …

simplify reader.ftl

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.ftl
test/tests/zoteroPaneTest.js

- added context menu to move a collection into another collection. Since one can drag a collection into another library, the top-level entries of the contextmenu are libraries and not collections as with itemTree (shouldn't the same be true for itemTree in fact? You can drag an item to a collection in another group but I don't think it's possible to do it with the context menu).
- refactoring of collectionTree to pull out `copyCollections()` and `copyItems()` from out of the scope of `CollectionTree.onDrop`. If a collection is moved into another library, the functionality of copying over a collection needed to be exposed to ZoteroPane without the actual drag-drop happening. `copyCollection` and `copyItems` are unchanged except for the added parameters. We could avoid the refactoring by …

vpat 16: context menu as a drag-drop alternative to move collections

---

chrome/content/zotero/preferences/preferences_file_renaming.js
chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/file.js
chrome/content/zotero/xpcom/recognizeDocument.js
chrome/content/zotero/zoteroPane.js
test/tests/recognizeDocumentTest.js
test/tests/zoteroPaneTest.js

Added a check to see if the current extension matches the `/^\w{1,10}$/i` regex. If it doesn't, it's considered invalid and discarded. For missing or invalid extensions, Zotero will attempt to guess the correct extension based on the mime type.
This is updated for "Rename File from Parent Metadata", when recognizing a file and for the preview in preferences.
I took the regex from here (it's used when editing a file name manually): https://github.com/zotero/zotero/blob/237a2e5b86edab2d09166d3368054be0c3f4239b/chrome/content/zotero/elements/attachmentBox.js#L579
Resolve #4739

Fix renaming behavior for attachment without extension

---

chrome/content/zotero/actors/ActorManager.jsm
chrome/content/zotero/actors/SequoiaContextMenuChild.jsm
chrome/content/zotero/actors/SequoiaContextMenuParent.jsm
chrome/content/zotero/contextMenuUtils.sys.mjs
chrome/content/zotero/platformKeys.js
chrome/content/zotero/xpcom/utilities_internal.js

Tested and working in Scaffold, note-editor, and basicViewer. EPUB and snapshot readers work as well. PDF needs https://github.com/zotero/reader/pull/141.
Fixes #4724

Implement Ctrl-Enter handler in child frames

---

scss/mac/_tabbox.scss
scss/scaffold.scss
scss/win/components/_tabbox.scss

Set focusring on the child `hbox`, instead of the actual tab. The `hbox` is the element with visibly rounded corners, so this way the focus-ring will have the right shape.
Fixes: #4744

Special handling for tabbox focus-ring

---

chrome/content/zotero/xpcom/utilities_internal.js

Filter out ascii control characters in renderItemTitle, since an errow is thrown if those characters are present when the innerHTML of a tab name in tab bar is set via `dangerouslySetInnerHTML`.
Fixes: #4758

Remove ascii control chars from rendered item title

---

chrome/content/zotero/zoteroPane.js
chrome/locale/en-US/zotero/zotero.ftl

More specific labels for the button to turn selected item(s) into standalone:
- "Convert to Standalone Sttachment(s)" when only attachments are selected
- "Convert to Standalone Note(s)" when only notes are selected
- "Convert to Standalone" otherwise (e.g. if a note and an attachment are selected together)
Fixes: #4766

Better label to make item standalone in change parent item dialog

---

js-build/localize-ftl.mjs
package-lock.json
package.json

* Tweak the script to use `en-us` `.ftl` files as the only source of truth.
* Update `ftl-tx` to a version that can handle referencing terms with arguments.
@dstillman **With this change, previous messages in localized `.ftl` files are assumed to be outdated and will be discarded by the `localize-ftl` script. This means that if no localized `zotero.json` is present to provide the up-to-date strings, these messages will revert to `en-us` strings.**
I assume that the latest localized `zotero.json` is always available for every locale when calling `npm run localize-ftl`. If that’s not the case, please let me know!
Fix #4773

Fix `localize-ftl` exiting with an error in certain cases

---

scss/preferences/_advanced.scss

- no margin-top on windows
- explicitly hide background and border, since they remain on windows otherwise
followup to: https://github.com/zotero/zotero/commit/28f3a29f3569f0e86e75406ad306afef4e1db786
Before:
After:

Tweak default data directory location stylesheet for windows

---

chrome/content/zotero/elements/librariesCollectionsBox.js

So that they do not disappear after Libraries and Collections section is collapsed and expanded.
Fixes: #4784

Fix group libraries disappearing from Libraries and Collections section

---

chrome/content/zotero/elements/itemBox.js
chrome/content/zotero/xpcom/data/itemFields.js

Everything works like Title now besides creator name fields, since those don't have room to wrap in the layout.
We lose a little horizontal space on fields with three-dot menu and URL launcher buttons that weren't previously "long" - I think that's Series Title, Short Title, URL, and DOI - but the vertical space gain should make up for that.
`Zotero.ItemFields.isLong()` just logs a warning and returns true. I doubt that anyone else is using it, but still.
Closes #4801

Item box: Wrap all fields

---

chrome/content/zotero/integration/quickFormat.js

Fixes: #4771
https://github.com/user-attachments/assets/17c2eb7c-e970-49e3-91ac-3047e0ba27c3

qf: show recently modified notes when input is empty and no notes are selected

---

app/build.sh

[LightweightThemeConsumer](https://searchfox.org/mozilla-central/source/toolkit/modules/LightweightThemeConsumer.sys.mjs) interacts with the color scheme, so removing it prevents the color scheme from changing whenever `zoteroPrint` runs.
Fixes: #4782

fix color scheme getting reset during printing

---

chrome/content/zotero/xpcom/reader.js

Only move focus out of the reader iframe on tab/shift-tab if the reader instance is opened within a tab, meaning the sync button and the contextPane exist. If the reader is opened in a standalone window, do nothing.
Fixes: #4823

Do not handle tabbing out of reader iframe in standalone window

---

chrome/content/zotero/itemTree.jsx

When items are selected, `itemTree` scrolls to them. Depending on the arrangement of items, it will often default to scrolling to the top-most item in the selection, which is not the focused row in case of duplicates view. To scroll to focused row without unnecessary scrolling or items visibly jumping to one row and then another, added option to skip scrolling in `itemTree.selectItems`.
Fixes: #4821
https://github.com/user-attachments/assets/fde6f1e7-c248-49b3-bbe6-663312776aa0

scroll to pivot row on arrowUp/Down in duplicates

---

chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
scss/elements/_quickSearchTextbox.scss

Per https://forums.zotero.org/discussion/119312/search-window-in-zotero-7-is-too-small. I suppose, when the middle pane is wide, we do have plenty of space between toolbar buttons and the quickSearch, so allowing it to stretch a bit does not hurt? Maybe the exact width values need to be tweaked - I started with max-width of `300px`.
https://github.com/user-attachments/assets/8033b74d-7613-41d3-9985-da92de3258c2
Also, have spinner always occupy space, so that it does not push quickSearch out of the bounds of the middle pane when it is very narrow. Respectively, make min-width of quicksearch a bit smaller. This resolves the issue that is present currently on `main`, without these quicksearch stretching tweaks. This is the current behavior I am referring to: …

Allow quicksearch to stretch when there is space in the middle pane

---

chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/xpcom/utilities_internal.js

Move handling of tabs' renaming when an item is modified from `Reader` into `Zotero_Tabs`, so that the titles of unloaded tabs can get properly renamed.
Have the `Reader` and `Zotero_Tabs` share `Zotero.Utilities.Internal.constructItemTitle` to handle title updates in both tabs and standalone reader windows.
Fixes: #4646

Update tab titles independently of the reader

---

chrome/content/zotero/actors/ActorManager.jsm
chrome/content/zotero/actors/MendeleyAuthChild.jsm
chrome/content/zotero/actors/MendeleyAuthParent.jsm
chrome/content/zotero/import/mendeley/mendeleyAPIUtils.js
chrome/content/zotero/import/mendeley/mendeleyImport.js
test/tests/data/mendeleyMock/notebook.json
test/tests/mendeleyImportTest.js

This PR extends the Mendeley importer to also import notebooks, which are only available in the new Mendeley Reference Manager. 
This is based on reverse-engineering, as Mendeley does not provide documentation for this API.
The title of the notebook is translated into an `h1` at the very top of the Zotero note. "Freetext" nodes are translated as HTML paragraphs. Annotations/citations are identified by UUID and then generated using our `serializeAnnotations` function; the actual textual content from the Mendeley is ignored.
Neither the "direct" nor "OAuth" tokens that we use for the Mendeley API enable access to this feature. Therefore, we use the credentials provided by the user to perform a complete sign-in in a hidden browser and then extract an access token that allows us to access …

Import mendeley notebooks

---

chrome/content/zotero/itemTree.jsx
test/tests/itemTreeTest.js

Do not try to re-select a previously selected item if it was filtered out from itemTree, e.g. after
it was removed from currently selected collection. Otherwise, quickSearch gets cleared in an attempt to re-select the item.
Fixes: #4616

Fix quicksearch getting cleared after an item is removed from collection

---

chrome/content/zotero/elements/contextNotesList.js
chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/elements/itemPaneSidenav.js
chrome/content/zotero/elements/noteRow.js
chrome/content/zotero/elements/notesContext.js
chrome/content/zotero/tabs.js
chrome/locale/en-US/zotero/zotero.ftl
scss/elements/_noteRow.scss
test/tests/zoteroPaneTest.js

- all sidenav buttons are focusable
- first focusable visible button will receive focus on tab from the last focusable element in the item pane
- shift-tab will return focus back to the item pane
- buttons can be navigated with up/down arrows
- minor tweaks to keypress handling in ZoteroPane to better handle opening of custom menus like locate
and buttons expecting click-specific event properties (e.g. event.details)
https://github.com/zotero/zotero/assets/36271954/16c4b7b0-63d7-4a4a-9c93-f89539ce3df1

Make sidenav buttons keyboard accessible

---

chrome/content/zotero/elements/librariesCollectionsBox.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.dtd
chrome/locale/en-US/zotero/zotero.ftl

And:
- Rework a few ZP functions to take items arrays instead of always acting on selected items
- Move string to Fluent
- Build entire Add to Collection menu programmatically
Fixes #4841

Libraries and Collections: Fix Add button in reader tabs

---

chrome/content/zotero/integration/quickFormat.xhtml

This may help with the issue of locator popup sometimes not being properly rendered per https://github.com/zotero/zotero/issues/4814#issuecomment-2477538297
Also, it allows the popup to have a proper width on windows when "Always show scrollbar" setting is on.
Addresses: #4814
Addresses: #4805

QuickFormat: potential fix to locator popup not properly rendering

---

chrome/content/zotero/xpcom/data/search.js
test/tests/searchTest.js

Fix the glitch where having anyField search condition along with any other condition would return an empty result set if joinMode="any".
This would happen due to a conflict between conditions caused by wrapping "anyField" condition set into a quickSearch block, which [enforces](https://github.com/zotero/zotero/blob/a6c178dfe81e1f44f9a8a33085b5d5fe2fb6695b/chrome/content/zotero/xpcom/data/search.js#L1814) "AND" operator between conditions.
Minor followup to: https://github.com/zotero/zotero/commit/cda0e0cf6d2f2dac04ab9855b468f22c18495ce2
Fixes: #4830

Fix "anyField" conflicting with other search conditions with joinMode=any

---

chrome/content/zotero/elements/contextNotesList.js
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/elements/itemPaneSidenav.js

- fix the issue of focus not landing on search field of the notes pane when it is opened on tab from the reader
- shift-tab from the `sidenav` when notes pane is opened will focus the search input as well, instead of the last focusable node in the pane (e.g. "X more..." button at the bottom)
- tab from a `note-row` in the list of notes will focus the `sidenav`
- shift-tab from a `note-row` will focus the header of the `collapsible-section`. I thought focusing the reader right away would be too much, since one might need to get to the `+` button to add a note, or something like that. And once you are at a section header, you can jump to the header of the previous section (if there is one) with `arrowUp`, at which point, you are at the top of the notes pane.
Per …

Context pane notes list focus handling edits

---

chrome/content/zotero/elements/itemPaneSidenav.js

Recent regression - preventing `mousedown`'s default action prevents `:active` from being applied. Move focus back to `relatedTarget` on `focusin` instead.

Fix sidenav buttons not getting `:active` state

---

chrome/content/zotero/elements/contextPane.js
test/tests/itemPaneTest.js

Fix duplicate item pane when switching to library tab before reader is loaded

---

chrome/content/zotero/platformKeys.js
chrome/content/zotero/standalone/hiddenWindow.xhtml
chrome/locale/en-US/zotero/zotero.ftl

And change shortcut to Cmd-Shift-L to avoid conflicts with various font size and zoom shortcuts.
This makes Window -> Zotero available in every non-main window that uses `platformKeys.js`, which is Scaffold, the reader, and the basic viewer right now. The second commit extends that to include note windows as well. (Those don't actually show _in_ the Window menu, though, because they're opened with `openDialog()`.)
There's no great way to hide the Window -> Zotero menuitem when the main window is open. Messing with `windowMenu` children in `popupshowing` breaks macOS's auto-population. We could probably get around it with some kind of window observer, but I think it's actually better this way: the keyboard shortcut should work consistently, regardless of whether the main window is already …

macOS: Move Window -> Zotero to platformKeys

---

chrome/content/zotero/elements/contextNotesList.js
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/elements/itemPaneSidenav.js
chrome/content/zotero/elements/notesContext.js
chrome/content/zotero/zoteroPane.js

- remember the last focused `note-row` in the `contextPane` and, if possible, refocus it on shift-tab from `sidenav`, on tab from the reader into the notes pane, or on tab into the notes list from the collapsible-section. Otherwise, focus the search input. Per: https://github.com/zotero/zotero/pull/4837#issuecomment-2478108186
- when a note is opened in the context pane, let `shift-tab` from `sidenav` place focus on the `links-box`. That way, it is not skipped during tab navigation.
- fix focus not entering `note-editor` on tab from the "Go back" button and instead wrapping around to the current tab

Context pane  notes list focus handling followup

---

chrome/content/zotero/itemTree.jsx

If a child item is modified and its parent row exists and is opened, collapse the parent row and expand it to re-render child items.
Fixes: #4791
https://github.com/user-attachments/assets/5df8ed91-d989-4a73-976e-df0dd2300acb

itemTree: handle child row modifications in notify

---

chrome/content/zotero/elements/contextNotesList.js
chrome/content/zotero/elements/itemPaneSidenav.js
chrome/content/zotero/elements/notesContext.js

- shift-tab from a note row focuses section header's twisty
- tab from reader into context pane will focus the search field. Previously focused note row will be focused on tab from a section header's twisty
- fix focus not leaving context notes pane if all sections are collapsed
- shift-tab from sidenav will again just focus the last node in the contextPane, instead of search input. That is to have consistent tab order in each direction. Earlier, in https://github.com/zotero/zotero/pull/4837#issuecomment-2478121979, I had focus land on the search field, otherwise focus would land on the last note-row (or "X more" button), which felt off and it would take a while to tab through all the note rows. Now, though, focus lands on the previously focused note (if there is one), which makes more …

Context notes pane focus fixes

---

package.json

See the documentation of the `private` field: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private
> If you set `"private": true` in your package.json, then npm will refuse to publish it.
I think we can replace the string `"private"` to `true`, which is more consistent with NPM's documentation.
> Additional information
> In 2016, the field type specified in NPM's documentation is also Boolean, not string. See: https://web.archive.org/web/20160901200545/https://docs.npmjs.com/files/package.json

chore: correct the value of the `private` field in package.json

---

app/scripts/fetch_xulrunner

Still not quite right:
Missing border/weird margins inline inputs (days in that screenshot) and misaligned cursor on all inputs. But this is an improvement!
Addresses #4888

 fx128: Remove non-native text input styles

---

app/scripts/fetch_xulrunner

`global-shared.css` ended up broken after #4890. Turns out multiline Perl regex substitutions do not work the way I thought they did! Every closing brace in the file was getting removed. That was why inputs still looked wrong. So I've added a new `remove_between` function that removes all lines between (and including) a start pattern and an end pattern, non-greedily, and used that to apply the intended fix.

fx128: Add `remove_between`, fully fix input styles

---

app/assets/mac/chrome/skin/preferences/preferences.css
app/assets/unix/skin/preferences/preferences.css
app/assets/win/skin/preferences/preferences.css
app/scripts/fetch_xulrunner
chrome/skin/default/zotero/publicationsDialog.css
chrome/skin/default/zotero/zotero.css
scss/about.scss
scss/components/_import-wizard.scss
scss/components/_textLink.scss
scss/elements/_publicationsLicenseInfo.scss

`-moz-nativehyperlinktext` ~~has been removed~~ [is theoretically still there](https://searchfox.org/mozilla-esr128/search?q=nativehyperlinktext&path=&case=false&regexp=false) but doesn't work anymore for some reason.
`-moz-hyperlinktext` still works, but `LinkText` does the same thing and [isn't proprietary](https://developer.mozilla.org/en-US/docs/Web/CSS/system-color#linktext), so I went with that.
Fixes #4889

fx128: `-moz-nativehyperlinktext` -> `LinkText`

---

chrome/content/zotero/preferences/preferences_advanced.js
chrome/content/zotero/xpcom/localAPI/server_localAPI.js
chrome/content/zotero/xpcom/server.js
test/runtests.sh
test/tests/attachmentsTest.js
test/tests/serverTest.js
test/tests/server_connectorIntegrationTest.js
test/tests/server_connectorTest.js
test/tests/server_integrationTest.js
test/tests/server_localAPITest.js

And:
- Use a different port for tests so server tests don't break when Zotero is already running
- Remove no-op `httpServer.enabled` pref updates in tests
- It's already enabled, no test disables it, and any test that did would clean up after itself
- Updating that pref has no effect without a separate call to `Zotero.Server.init()`
- Remove unused arg to `Zotero.Server.init()`
It's basically just annoying that server tests fail when I forget to close the client first, so this fixes that.

Server: Expose actual bound port

---

chrome/content/zotero/xpcom/integration.js
chrome/locale/en-US/zotero/zotero.properties

This is no longer a thing since word plugins are not Zotero extensions. If that code throws - it's because we've done something wrong and it's a bug.
I removed the associated string, but I'm not sure if we can do that and things will propagate properly to Transifex.
Closes #4916.

Remove missing-component integration error.

---

scss/linux/_titleBar.scss

Fixes: #4922
Before (note you can see where darker VS code window ends in the gap):
After:

fx128: cover transparent titlebar gap on linux

---

app/scripts/fetch_xulrunner

Fixes: #4885
After re-fetching xulrunner:

fx128: hide 'Run on sites with restrictions' from plugins page

---

scss/linux/_titleBar.scss

Followup to: #4924
Addresses: #4922
Pre-fx128, `--toolbar-field-border-color` was `ThreeDShadow`, while right now it is `--input-border-color`, which looks more prominent.
Setting border color explicitly to be `ThreeDShadow` now would make the border look a bit blurry. Transparent border looks closest to pre-fx128 look, in my opinion.
Pre-fx128:
Now:
Alternatively, if we were to set color to be `ThreeDShadow` as before (and without the `margin-bottom` added earlier):
I think `transparent` looks nicer than `ThreeDShadow` but correct me if just `ThreeDShadow` or some other color is better.

fx128: tweak titlebar border color

---

chrome/content/zotero/tabs.js

Allow Zotero_Tabs.undoClose to reopen duplicate tabs

---

chrome/content/zotero/xpcom/db.js

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1869060#c18, the backup utility was removed from the storage service and [exposed](https://searchfox.org/mozilla-esr128/source/toolkit/modules/Sqlite.sys.mjs#2024) directly on the connection itself in fx128.
Fixes: #4929

fx128: fix broken database backup

---

chrome/content/zotero/elements/tagsBox.js
test/tests/tagsboxTest.js

When `tagsBox` item is changed by clicking on an `itemTree` row, the `blur` even never fires on the currently focused tag. So whatever changes were made will be discarded. To avoid it, blur any opened tag rows (which triggers a `saveTx`) when an item is being set, same way it is [done in itemBox](https://github.com/zotero/zotero/blob/fa48e978c7001a3b3b487f738756600e312fe23d/chrome/content/zotero/elements/itemBox.js#L358).
Also, a small tweak to properly fetch the focused tag via `editable-text:focus-within` selector, since `editable-text:focus` should be always empty because the focus is on the `<input>` inside of editable-text.
Fixes: #4942

save tagsBox updates when an item is changed

---

chrome/content/zotero/integration/quickFormat.js

Do not close details panel on arrowUp when locator type menulist is focused to allow for default handling (e.g. select the next/previous option on windows).
Fixes: #4953

qf: allow default arrowUp handling on locator type dropdown

---

chrome/content/zotero/xpcom/utilities_internal.js

I encountered this error while exporting a collection in my library.
Item generated from embedded image attachment may not have attribute `tags`.

Fix export error of item.tags being undefined

---

app/scripts/fetch_xulrunner

[searchButton setter](https://searchfox.org/mozilla-esr128/source/toolkit/content/widgets/search-textbox.js#129) in `search-textbox` element adds `aria-autocomplete` to the `<input>`. It makes screen readers announce that there is an autocomplete popup and is misleading. This overrides the `searchButton` setter to remain unchanged but with the line where `aria-autocomplete` is set commented out.
Addresses: #4932
For comparison, this is the JAWS announcement before (note the incorrect "Has popup"):
https://github.com/user-attachments/assets/e1ebb692-be34-43ed-b036-297f3ec1d78b
This is the JAWS announcement after this change (note no "Has popup"):
https://github.com/user-attachments/assets/ec8d268c-d83b-4c2b-bfd6-592d62608a5a

remove wrong aria-autocomplete from search-textbox

---

app/scripts/dir_build

`uname` is used in the script elsewhere already and `arch` does not seem to be available everywhere.
In the future, it might be better to have more fine grain control on what to build but for now this should work.

Use `uname -m` instead of `arch`

---

chrome/content/zotero/elements/attachmentBox.js

fix: #4611
Since the attachment preview already has a task queue,
don't skip render calls when rendering

Fix attachments box race condition

---

chrome/content/zotero/xpcom/data/item.js
test/tests/itemTest.js

Local API: Fix 500 error when attachment has unparseable path

---

chrome/content/zotero/xpcom/localAPI/server_localAPI.js
chrome/content/zotero/xpcom/style.js

This should've been a simple fix, but something absolutely bizarre was going on with `Zotero.Styles.init()` in tests. `init()` was running multiple times in parallel, even when I moved the `if (_initializationDeferred)` block all the way to the top of the method. That led to race condition issues like `_visibleStyles` getting frozen (line 89) before being sorted (line 85). I have absolutely no idea how that's even possible with JS promises. Maybe invisible multithreading due to the server?
But replacing the deferred promise-based serialization with `Zotero.Utilities.Internal.serial()` was enough to make it behave in all cases, and it simplified the code. `_initializationDeferred` wasn't accessible from the outside so this should be a seamless change for callers.
Fixes #5030

Local API: Fix out-of-repo styles, make `Zotero.Styles.init()` behave

---

chrome/content/zotero-platform/mac/integration.css
chrome/content/zotero/integration/insertNoteDialog.xhtml
chrome/content/zotero/integration/progressBar.xhtml
chrome/content/zotero/integration/quickFormat.js
chrome/content/zotero/integration/quickFormat.xhtml
chrome/content/zotero/xpcom/integration.js
chrome/skin/default/zotero/integration.css
scss/components/_progressMeter.scss

Closes #1923 
The issue with displaying the progress bar on macOS is that when you close it (to then open a citation dialog), the main Zotero window is raised (appears in the foreground with the citation dialog focused on top of it). This is because when you close a window of an application on macOS it automatically focuses the last focused window of the app, which in our case after closing the progress bar is the Zotero window.
In the past we haven't been showing the citation dialog on macOS due to this, as it's quite jarring, especially if the Zotero window raises under the quick format dialog
This PR makes it so that Refresh, Unlink Citations and Add/Edit Bibliography show a progress bar. After Refresh and Unlink Citations is finished, Document.activate is called, which means that Word …

Macos progress bar

---

chrome/content/zotero/xpcom/data/item.js
chrome/content/zotero/zoteroPane.js
test/tests/zoteroPaneTest.js

The `this.parentItem.numFileAttachmentsWithContentType(this.attachmentContentType) <= 1` thing was a very silly attempt to work around the fact that `setAutoAttachmentTitle()` can be called before the attachment is saved, so its parent item won't consider it one of its children. But the "workaround" actually just introduced an off-by-one error and didn't fix anything.
Stored files weren't affected because `importFromFile()` saves once before updating the title, but linked files were, because `_addToDB()` (called from various places including `linkFromFile()`) doesn't save until the very end.
Also fixed a JSDoc type and added a test.
Fixes #5044

Fix faulty siblings-of-type check in `setAutoAttachmentTitle()`

---

eslint.config.mjs

Current firefox version supports all features of es2022
Fix errors with features like WeakRef

Update eslint ecmaVersion to es2022

---

chrome/content/zotero/xpcom/editorInstance.js

Define missing `cancel` method on `io` object passed from the editor instance to quickFormat dialog. Without this, Escape keypresses throws an error because `io.cancel` is undefined.
Followup to #4859
For reference, this is how the original error can be reproduced on current `main`:
https://github.com/user-attachments/assets/e0e3b0a3-72b9-4939-9c2c-95a99f48eaa2

Fix broken QF cancellation from editor instance

---

chrome/content/zotero/elements/librariesCollectionsBox.js

After navigating to a collection from "Libraries and Collections" section of an item in the trash, do not try to select that item. Deleted item will not appear in the actual collection and trying to select it will just re-select the trash.
Fixes: #5060
https://github.com/user-attachments/assets/64ab78ae-412e-4bc5-8cf4-e571df3652c0

Fix navigating to collections via "Libraries and Collections" section of trashed items

---

app/build.sh
app/scripts/fetch_xulrunner
chrome/content/zotero/browserWindowShim.js
chrome/content/zotero/reader.xhtml
chrome/content/zotero/standalone/basicViewer.xhtml
chrome/content/zotero/zoteroPane.xhtml
test/content/support.js
test/tests/feedReaderTest.js
test/tests/feedTest.js
test/tests/fulltextTest.js
test/tests/searchTest.js
test/tests/storageLocalTest.js
test/tests/translateTest.js

This removes a bunch of Mozilla files that we didn't need - mostly actors, which don't usually break things when removed, but some modules, too. We now remove the entire `browser/chrome/browser/` directory! 362.7 MB -> 354.6 MB! 🎉🎉🎉 Yes, you read that right, a full 2.23% reduction.
But the biggest improvement here is that we no longer show a broken browser window when printing. Turns out all we needed was to set `window.browserDOMWindow` to something implementing `nsIBrowserDOMWindow`. The weird part is that the methods we implement are apparently never actually called(???) - we just need to convince Firefox that a browser window of some kind is already open.
Closes #5048

Fix broken browser window on print + remove many Mozilla files

---

chrome/content/zotero/elements/attachmentBox.js
chrome/content/zotero/elements/itemBox.js

Click on a label of a focused field in itemBox or attachmentBox will refocus itemTree or the reader content, depending on the tab. That way focus is not lost.
Fixes: #5063

Click on itemBox label focus edits

---

chrome/content/zotero/xpcom/prefs.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/xpcom/syncedSettings.js
defaults/preferences/zotero.js

Enables syncing custom themes, allowing the same custom themes to be used in the web library and mobile apps.  I've also included code to migrate existing pref to a synced setting.
I don't think we should sync the actual selected theme (and this PR doesn't do that)—users might prefer different themes on different devices—but it would be nice if the same custom themes were available across devices.
Depends on https://github.com/zotero/dataserver/pull/168

Convert `customThemes` from a pref to a sync setting

---

chrome/content/zotero/elements/itemBox.js

So that whitespaces are removed even if the itemBox does not refresh.
Fixes: #5080

Trim editableText from itemBox on blur

---

chrome/content/zotero/xpcom/intl.js
defaults/preferences/zotero.js

Define preference permitting alphabetical or natural sorting of collections. If true, use natural collection sorting matching the current behavior. If false, use conventional alphabetic sorting is used.
This pull request does not implement dynamic update of the tree. If changed, the preference is applied after restart.

Sort strings naturally or alphabetically

---

app/scripts/fetch_xulrunner
scss/elements/_editableText.scss

Fix space before ellipsis in editable-text

---

chrome/content/zotero/elements/bubbleInput.js
chrome/content/zotero/integration/citationDialog.js

`IOManager` relies on everything being loaded, so it should be initialized last. Otherwise, any IO handler trying to access `currentLayout` would throw an error.
Also, swap the order of operations in bubble-input to set input width only after the first input is added. Otherwise, first input will have an arbitrary width during initial load.
Hopefully, this will address:
https://forums.zotero.org/discussion/122554/beta-new-insertion-bar-problem-with-citations-but-not-notes
For testing, I added `await Zotero.Promise.delay(5000)` to `onLoad` after `IOManager.updateBubbleInput();` and tried to type. I ended up seeing similar errors as reported and the dialog became unresponsive after. Now, I see no errors, and `IOManager` will begin processing IO whenever everything else is ready.

citation dialog: fix IO race condition on load

---

chrome/content/zotero/update/updates.js

Zotero 7.1-beta12, when closing the ‘check update’ window, I get the following error: 
I have not tested it and am not sure if the modifications make sense.
may ref: https://searchfox.org/mozilla-central/source/toolkit/mozapps/update/UpdateService.sys.mjs#46

Fix update checker _checker.stopCurrentCheck is not function

---

app/scripts/check_requirements

Currently, `check_requirements` suggests running `git lfs pull`. In most cases, this will not be sufficient, as Git LFS hooks would not be installed yet. This PR extends the suggestion to also include `git lfs install` in the instruction.
(I was just setting up Zotero build on another machine and was confused by that for a second)

Suggest running `git lfs install` in check_requirements instructions

---

chrome/content/zotero/integration/citationDialog.js

In library mode when there are no selected/open/cited items, Enter keypress from input will add the first row of itemTree into the citation only if it is the only row.
Fixes: #5098

citation dialog: Enter adds row when only 1 match

---

chrome/content/zotero/integration/citationDialog.js

After switching from list mode to library mode if the selected collection row is close to the bottom.
Fixes: #5104
For comparison with the recording in the linked issue:
https://github.com/user-attachments/assets/68f9a02f-8da9-4785-bc47-809240191a9c

citation dialog: fix collectionTree sometimes not rendering

---

chrome/content/zotero/integration/citationDialog/searchHandler.mjs

So that if there are multiple tabs opened for the same top level item, it appears only once in search results.

citation dialog: deduplicate open items

---

chrome/content/zotero/elements/editableText.js
chrome/content/zotero/elements/itemBox.js
scss/elements/_editableText.scss
scss/elements/_infoBox.scss

https://github.com/zotero/zotero/pull/5087#issuecomment-2717115891
https://github.com/user-attachments/assets/4e03bb27-b843-46e0-b27f-2ccde4228f75
There's still a little extra space after the *comma* when the field is clipped on a wide character. But after a lot of trial and error, I think this is the best we're going to get.

Make the info box ellipsis behave

---

scss/components/_citationDialog.scss

So it aligns with inputs a bit better. Positioning is tricky with native select elements but with a bit extra margins, it looks better I think.
Fixes: #5091
Before:
After:

Citation dialog: move locator label lower

---

chrome/content/zotero/integration/citationDialog.js

Instead, when the search runs, replace just the accept button with the spinner.
Fixes: #5115
https://github.com/user-attachments/assets/db1f8193-cdd1-4cf4-a328-dd126f730c0a

citation dialog: only do not hide cancel button when search runs

---

chrome/content/zotero/integration/citationDialog.js

Fix issue where clicking cancel or accept buttons would not work when the dialog itself is unfocused. Add a small delay in the focus handler of the dialog to allow cancel/accept button clicks to be handled before rerunning the search.
Fixes: #5110
https://github.com/user-attachments/assets/bafa169a-80ad-4768-b41d-c964882e88db

citation dialog: fix not handled click on cancel/accept buttons of unfocused dialog

---

chrome/content/zotero/integration/citationDialog.js

Do not explicitly move the window to the center of the screen.
Fixes: #5119
With this, the dialog also appears on an external monitor if it was last closed there for me (https://forums.zotero.org/discussion/122594/zotero-beta-about-the-new-citation-dialog-window). There was some [special handling in QF](https://github.com/zotero/zotero/blob/4915f1fadf773f855507bd801137e87770583ec6/chrome/content/zotero/integration/quickFormat.js#L273) to move the dialog into the center if it is not properly visible - but such handling is not present in any other dialog, and I have no been able to get the dialog to appear without being properly visible. So I assume it's just no longer needed.

citation dialog: persist screen position

---

chrome/content/zotero/xpcom/reader.js

This resolves an issue where, after the selected theme was deleted, it was impossible to select a newly added custom theme. This happened because the preference key for the selected theme uses consecutive IDs and wasn't cleared when the theme was deleted. As a result, the newly created theme would receive exactly the same ID. When that theme was selected, the preference observer did not trigger (because the ID did not change), leading to this bug.
The fix here is to clear the theme preference when it is deleted. The added benefit is that when this happens in dark mode, the dark theme is auto-picked instead of falling back to "Original".
Close #5070

Fix sometimes unable to select a custom theme

---

chrome/content/zotero/elements/bubbleInput.js
chrome/content/zotero/integration/citationDialog/keyboardHandler.mjs
chrome/content/zotero/integration/citationDialog/popupHandler.mjs

- restore earlier behavior of arrowDown on a bubble opening itemDetails popup
- arrowUp from inside itemDetails closes the popup (except when locator dropdown is focused)
- remove arrow navigation between rows of bubbles on arrowUp/down
- remove no longer needed edge case of arrowDown handling on the last row of bubbles
Fixes: #5118

citation dialog: restore arrowDown on bubbles opening details popup

---

chrome/content/zotero/xpcom/plugins.js

Since the bootstrap plugin framework, from time to time I ran into cases where some plugins don't start.
It turned out that the sandbox scope is not loaded at all if the plugin is
1. installed before Zotero starts
2. disabled before Zotero starts
It is amazing that no one ever reported/found this bug, which is a quite serious bug... Maybe everyone would blame the plugin developers for not having the plugin well-written.

Fix plugin scope not loaded if plugin is disabled when starting Zotero

---

chrome/content/zotero/integration/citationDialog.js

In library mode, apply highlighting to bubbles that correspond to selected items in itemTree only when the items table is focused. When the focus leaves, highlighting is removed from bubbles.
Fixes: #5138
https://github.com/user-attachments/assets/76d63f84-207b-4af2-bd09-522f0e2adc3e

citation dialog: highlight bubble of selected item row only when itemTree is focused

---

chrome/content/zotero/locateManager.xhtml
scss/components/_locateManager.scss

Simple tweak removes button justification:
With extra-long content in German:
RTL:
Closes #4825

Improve layout of the buttons in the locate manager

---

chrome/content/zotero/HiddenBrowser.jsm
chrome/content/zotero/actors/ActorManager.jsm
chrome/content/zotero/actors/DocumentIsReadyChild.jsm
chrome/content/zotero/actors/MendeleyAuthChild.jsm
chrome/content/zotero/actors/PageDataChild.jsm
chrome/content/zotero/actors/SingleFileChild.jsm
chrome/content/zotero/actors/TranslationChild.jsm
chrome/content/zotero/actors/actorUtils.mjs
test/tests/HiddenBrowserTest.js

Wait for `'complete'` so we know the image has been loaded, not just `'interactive'` (which is what `getPageData()` was implicitly doing).
And use single `documentIsReady()` implementation instead of copy-pasting.

Fix HiddenBrowser test failures

---

chrome/content/zotero/elements/bubbleInput.js
scss/elements/_bubbleInput.scss

- add dropmarker to bubbles after the text to indicate that bubbles are clickable
- remove X remove button that was there before
- no more mask over the bubble on hover, since dropmarker is just always visible
- 4px distance between the dropmarker and bubble text
Fixes: #2712

Citation dialog: add a dropmarker to bubbles

---

chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog/helpers.mjs
chrome/content/zotero/integration/citationDialog/keyboardHandler.mjs
chrome/content/zotero/integration/citationDialog/searchHandler.mjs
chrome/locale/en-US/zotero/integration.ftl
scss/components/_citationDialog.scss

- Initialize asynchronous loading of cited items via `io.getItems` when the dialog appears. The dialog is usable when the cited items are not yet loaded, they just don't appear in search results.
- Once cited items are loaded, the list of items is refreshed to include matching items and all subsequent searches will include them too.
- During the refresh immediately after cited items load, try to preserve focused/selected state of items.
- Minor refactoring of `SearchHandler` to handle refreshing of cited items separately from selected and open items. Some cleanup.
I added a `Zotero.Promise.delay(4000)` to `SearchHandler._getCitedItems()` to test out the behavior. Note the cited items appearing after a delay:
https://github.com/user-attachments/assets/664edf11-2158-4366-ad3a-a152df249e34 …

Citation dialog: interactability before cited items are loaded

---

chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog.xhtml

Do not wait for the `itemTree` to add the menubar but create it immediately and just initialize it when `itemTree` is ready.
Fixes: #5153

citation dialog: fix menubar not appearing on first open

---

chrome/content/zotero/integration/citationDialog.js

- pass ref to `itemsView.changeCollectionTreeRow` to avoid errors thrown when typing numbers (related to [tags shortcuts](https://github.com/zotero/zotero/blob/9a58be243eb6f087a6ad0b2f1c1bfc58145e7943/chrome/content/zotero/itemTree.jsx#L995))
- return string equivalents of true/false in `getExtraField`. `virtualied-table` [expects a string](https://github.com/zotero/zotero/blob/9a58be243eb6f087a6ad0b2f1c1bfc58145e7943/chrome/content/zotero/components/virtualized-table.jsx#L675) in its typing handler. Previously returned boolean value was causing an error if you tried to type when the "add to citation" `+` column was used for sorting.

Citation dialog: fixed errors thrown if you type in itemTree

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog/searchHandler.mjs

- get opened items asynchronously and load their data in case if there are items opened across multiple
libraries, and some of them are unloaded.
This fixes: #5161, which makes the dialog unresponsive upon initial load.
- enforce `io.filterLibraryIDs` in library mode, the same way it already is being applies in list mode. This is currently used to only show items from the current library when adding citations in a note.
- account for the change above in collectionTree by focusing the first library from `io.filterLibraryIDs`, if those are present, and only default to `userLibraryID` if `io.filterLibraryIDs` is empty.

citation dialog: fix unloaded items errors

---

app/scripts/fetch_xulrunner
chrome/content/zotero/elements/itemBox.js

The popup tries to size itself based on the width of the input that opened it (input's width or 100px, whatever is greater). This removes that constraint so it uses the standard popup layout algorithm. It still doesn't grow past the edge of the `info-box` for some reason (which is good).
This is the simple approach. I also have alternative code to patch `autocomplete-popup.js` so it still explicitly calculates its width, but allows a parent (e.g. the info-box row) to set itself as the anchor in place of the input. Can go with either approach.
Fixes #5140

Let autocomplete popup get wider

---

chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog/helpers.mjs
chrome/content/zotero/integration/citationDialog/searchHandler.mjs
chrome/content/zotero/preferences/preferences_cite.xhtml
chrome/content/zotero/xpcom/prefs.js
defaults/preferences/zotero.js
test/tests/citationDialogTest.js

- `last-closed` -> `last-used` for `citationDialogMode` pref value
- pref label `citationDialogLastClosedMode` -> `citationDialogLastUsedMode`
- update `Zotero.Pref`s version. While migrating, if `integration.useClassicAddCitationDialog` is true, set `integration.citationDialogLastUsedMode` to 'library' so the citation dialog opens in library mode on the first run. If `citationDialogLastClosedMode` pref exists, it is migrated to `citationDialogLastUsedMode` and cleared
- redone logic of extracting the locator to allow for better detection of locators and to not rely on long regular expressions that are hard to troubleshoot. Added tests for it.
These are the new rules for extracting locators:
- locator value can be either a set of numbers potentially with some punctuation in between OR …

Citation dialog: initial followup fixes

---

chrome/content/zotero/zoteroPane.js

Do not lowercase the entire title before capitalizing the first letter of each word to preserve abbreviations or spelling of unusual words (e.g. 3D or iPhone).
Fixes: #5165
For reference, this is the behavior of the transform menu with a few different titles:
https://github.com/user-attachments/assets/496f5568-0f23-4ac1-b441-824c4494f7f9

transform menu: preserve letter cases when capitalizing the title

---

scss/win/components/_input.scss

Everything that isn't an element selector is in a `:where()` (zero specificity) block now, so the overall specificity is that of an element selector, allowing it to be overridden by class selectors. Safer than making the whole thing zero specificity.
Fixes #4886

Windows: Reduce input style specificity to fix directory fields

---

chrome/content/zotero/zoteroPane.js

Per https://forums.zotero.org/discussion/123269/bad-practice-in-new-item-drop-down-menu.
In "New Item" menu, most recently used item types should also appear in the main list of all item types.

Include mru types in the main list of "New Item" menu

---

scss/components/_virtualized-table.scss

I couldn't find a color that didn't look kind of weird on top of the selected row background; just leaving it alone seems best.
Fixes #5196

Use normal text color for selected context row

---

chrome/content/zotero/tabs.js

This fixes the breakage in tabs menu on initial load if one of the tab is for an item from not-loaded group. Now, every component relying on tab items (e.g. tabs menu) can just assume that items are all loaded.
Fixes: #5192

Fix tabs menu breakage on initial load with an unloaded group's tab

---

chrome/content/zotero/runJS.html
chrome/content/zotero/runJS.js
chrome/locale/en-GB/zotero/zotero.ftl
chrome/locale/en-US/zotero/zotero.ftl
scss/components/_runJS.scss

Display "Completed successfully" instead of current undefined, which is a bit misleading.
Fixes: #5180
@AbeJellinek I agree that showing `undefined` has always been a bit misleading. Displaying "Completed successfully" at the very least conveys that everything ran and nothing broke.
While we are at it, I wonder if it would be worth to maybe also add a timestamp before the return value? While rerunning the code more than once, I find that it's not quite clear that rerunning actually happened, since the return value does not change. If there is a prefixed timestamp, something would look different on every run. Or would it just be confusing to have something go before the return value?

runJS: better message if nothing is returned

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTreeColumns.jsx

When column visibility is changed, we now redistribute the available space between the columns. I believe this fixes #4993.

Tweak column behaviour on visibility and order changes

---

chrome/content/zotero/advancedSearch.js
chrome/content/zotero/progressQueueDialog.jsx
chrome/content/zotero/xpcom/connector/server_connector.js
chrome/content/zotero/zoteroPane.js

Deprecate inLibraryRoot as an independent boolean param in `ZoteroPane.selectItems` to instead have a composite options param `{ inLibraryRoot, noTabSwitch }`.
Fixes: #4262
https://github.com/user-attachments/assets/2606faf1-f951-4719-be66-330307f8eb63

Do not switch to library tab while changing target collection in connector

---

chrome/content/zotero/zoteroPane.js

This is caused by the persisted splitter state value being blank from either older versions of clients or plugins. Resetting the empty values fixes this bug.
To reproduce: set the `zotero-context-splitter-stacked#state` to `"collapsed"` and `zotero-context-splitter#state` to `""` in `prefs.js` and then start Zotero. The item pane in reader tabs are blank without this fix.

Fix item pane blank

---

chrome/content/zotero/itemTree.jsx

Per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-expanded#treeitems only treeitems that contain children should have the `aria-expanded` attribute. This is instead of having `aria-expanded=false` on empty regular items or standalone attachments, which erroneously indicates to screen readers that the row has children but is collapsed.
Fixes: #5200

a11y: clear aria-expanded on empty itemTree rows

---

chrome/content/zotero/newCollectionDialog.js

Fixed non-working selection of collections in the dropdown via keyboard on Windows.
Fixes: #5202

Fixed non-working selection of collections in "New Collection" dialog via keyboard on Windows.

---

chrome/locale/en-US/zotero/zotero.properties

String read out by screen readers when the link popup appears instructing users to navigate it.
Needed for https://github.com/zotero/note-editor/pull/65
Addresses: #5199
Not sure if the message needs to be more detailed (e.g. "Use Shift-Tab to navigate it to remove/edit/open the link") or if it's better to just be concise.

add string for note-editor a11y link popup message

---

chrome/content/zotero/xpcom/intl.js
chrome/locale/en-US/zotero/note-editor.ftl
chrome/locale/en-US/zotero/zotero.ftl
chrome/locale/en-US/zotero/zotero.properties
js-build/config.js

Per https://github.com/zotero/zotero/pull/5205#issuecomment-2809055908
Needed for https://github.com/zotero/note-editor/pull/65
Addresses: https://github.com/zotero/zotero/issues/5199
This also adds a new string to announce when citation popup opens because it should be announced as well.

Move note-editor popup a11y strings to zotero.ftl

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/zoteroPane.js
scss/components/_collection-tree.scss
scss/components/_virtualized-table.scss

- when something is dragged over a collapsed collection or group, it will be expanded to reveal children so one could drop the dragged item/collection/ into them
- when drag is over, the expanded collections will collapse, except for the ancestors of the newly selected collection
- trigger collapse of expanded collections on `dragend` on the entire document (in case `dragend` fires not on the collection tree), or from `onDrop` handler, from where we will wait for selection to change before collapsing rows
Fixes: #4952
https://github.com/user-attachments/assets/6a89984f-8747-430c-a27c-f6cdbcbac203

Expand collectionTree containers on dragover

---

chrome/content/zotero/elements/itemDetails.js

To reproduce:
1. Open reader and scroll the item pane
2. Delete an annotation. The item pane scrolls to the top (which should not happen)

Keep item pane scroll position after refresh

---

app/scripts/fetch_xulrunner
chrome/content/zotero/selectItemsDialog.xhtml
chrome/locale/en-US/zotero/zotero.ftl
scss/components/_selectItemsDialog.scss

- Prevent dragging all windows via scrollbars with `fetch_xulrunner`. Can't apply styles to anonymous `<scrollbar>` elements in normal CSS, and it doesn't seem to me like we'd ever want this behavior anywhere.
- Match intended padding in Figma
- Remove space between scrollbars and the edge of the container (visible in the screenshot in https://forums.zotero.org/discussion/123401/zotero-related-window-the-scroll-bar-for-the-list-of-collections-is-unusable; I think this dates back to 7c7d8c143341b3ad6b96030e902500d0608756d7)
- Revert a past attempt at fixing the drag issue from 15ccf28fb41892df90acc3a943788b611cf99b01, which doesn't seem to have done the trick
- Add a title to the dialog (not drawn) for the Dock/taskbar/accessibility
Fixes #5206

Select Items dialog: Fix scrollbars and padding, add title

---

chrome/content/zotero/customElements.js
chrome/content/zotero/elements/annotationItemsPane.js
chrome/content/zotero/elements/annotationRow.js
chrome/content/zotero/elements/collapsibleSection.js
chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/locateMenu.js
chrome/content/zotero/standalone/standalone.js
chrome/content/zotero/xpcom/annotations.js
chrome/content/zotero/xpcom/data/items.js
chrome/content/zotero/xpcom/data/search.js
chrome/content/zotero/xpcom/data/searchConditions.js
chrome/content/zotero/xpcom/editorInstance.js
chrome/content/zotero/xpcom/quickCopy.js
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/xpcom/utilities_internal.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.ftl
scss/_zotero.scss
scss/abstracts/_variables.scss
scss/components/_item-tree.scss
scss/components/_tagSelector.scss
scss/elements/_annotationRow.scss
scss/elements/_itemMessagePane.scss
scss/elements/_itemPaneAnnotations.scss
test/tests/itemPaneTest.js
test/tests/itemTreeTest.js
test/tests/searchTest.js

- Annotations are displayed in itemTree under their file attachments on a third level. The annotation spans the entire row.
- Search matches the actual attachment instead of it's parent file.
- Can create child notes from annotations of the same item or standalone notes from annotations across different items from the context menu.

annotations showing in itemTree

---

chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/xpcom/reader.js

- Set `docShellIsActive` depending on the visibility state of the reader. Previously, we never told the browser that it was no longer visible, so the document's `visibilityState` was always `'visible'` and Firefox couldn't perform any visibility-related optimizations on inactive readers. This might have some minor performance benefits, but mostly it's just necessary to make https://github.com/zotero/reader/commit/c0a65316523b609f0dc40380a7900aa51818ce0b work in the client.
- Increase the priority of `<context-pane>`'s notifier observer. This codifies what was already happening by chance: `<context-pane>` is notified of tab switches before `Reader` is, so the tab layout is settled before the reader is notified that it's come into view.
- Update reader submodule
(Attachment preview tests …

Make hidden readers inactive, firing visibilitychange

---

chrome/content/zotero/elements/annotationRow.js
chrome/content/zotero/elements/collapsibleSection.js
scss/components/_item-tree.scss

- disable context menu on collapsible-sections of annotations in `itemPane`
- fix `arrowRight`/`arrowLeft` being able to expand/collapse annotation sections when they are focused
- set proper aria-label and aria-description on annotation cards
- fix misaligned annotation icons
Fixes: #5231
Fixes: #5234
Fixes: #5240

ItemTree annotations: miscellaneous fixes

---

chrome/content/zotero/itemTree.jsx
test/tests/itemTreeTest.js

- collapse all rows before removing them. It makes sure that annotation rows will be cleaned up properly when an annotation row is moved into another parent.
- move handling of inserting a new row when attachment is moved to be a top-level row from under a parent into the `item.isTopLevelItem()` condition. Otherwise, it never gets reached and attachment row just disappears when dragged to the top level.
Fixes: #5246
https://github.com/user-attachments/assets/cb277e7f-1330-497c-89f8-0dc57c218081

Fix leftover annotation rows and disappearing attachment rows after drag-drop

---

chrome/content/zotero/elements/attachmentBox.js
test/tests/itemPaneTest.js

To avoid re-focusing that fields for new attachment after refresh, which leads to the value of old attachment's field being transferred to the new attachment.
Fixes #5244
https://github.com/user-attachments/assets/d718043b-8ac6-4320-b73d-330e8af24069

Fix unintentional title transfer between attachments on item switch

---

chrome/content/zotero/zoteroPane.js

Per https://forums.zotero.org/discussion/123944/shift-enter-to-open-the-annotations-in-separate-windows-of-the-reader

Open annotation in new window on Shift+Enter on annotation row

---

chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/reader.js

I was going to do this with a listener in `_openTagsPopup()`, so I started by cleaning up the organization of that method, which had gotten a little out of hand. In the end I decided to do it more generically for all tabs, since this is more of a tab issue than a reader issue, but I kept the cleanup commit - why not.
Fixes #5250

Hide leftover popups when switching tabs

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/libraryTree.js

Do not update `itemTree` selection on each annotation row removal when an attachment row is collapsed.
It causes a significant delay when attachment with many annotations is collapsed if selection is on any row below the attachment. It is also redundant because the selection is updated at the end of `_closeContainer` anyway.
Fixes: #5255
This is the current behavior of attachment row collapse without the noticeable delay from recording in linked issue.
https://github.com/user-attachments/assets/b8387210-fd52-4dd6-86ac-f8998f778b3a

Improve performance of annotation rows removal

---

chrome/content/zotero/components/virtualized-table.jsx
chrome/content/zotero/itemTreeColumns.jsx
scss/components/_item-tree.scss
scss/components/_virtualized-table.scss

This PR is a follow-up to #5162 and fixes misaligned columns that sometimes appear after:
Resolves #5198

Fix table columns misaligned after resizing

---

chrome/content/zotero/elements/base.js
chrome/content/zotero/elements/tabsMenuPanel.js

As Mozilla does with theirs. This way, we can augment existing CE superclasses with our `XULElementBase` methods without duplicating code.
And check whether `super` has `connectedCallback`/`disconnectedCallback`. Fixes `TypeError: super.disconnectedCallback is not a function` on quit.

Make XULElementBase into a mixin to reduce code duplication

---

chrome/content/zotero/contextPane.js
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/elements/itemDetails.js
chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/elements/itemPaneSidenav.js
chrome/content/zotero/elements/utils/collapsiblePane.mjs
chrome/content/zotero/xpcom/reader.js
chrome/content/zotero/zoteroPane.js
chrome/content/zotero/zoteroPane.xhtml
chrome/locale/en-US/zotero/zotero.ftl
chrome/skin/default/zotero/20/universal/sidebar-bottom.svg
chrome/skin/default/zotero/20/universal/sidebar.svg
scss/components/_toolbar.scss
scss/components/_toolbarbutton.scss
scss/elements/_itemPane.scss
scss/elements/_itemPaneSidenav.scss
test/tests/itemPaneTest.js
test/tests/zoteroPaneTest.js

And:
- Make everything in `ZoteroContextPane` an instance method to reduce confusion about what `this` means
- Remove redundant `if (Zotero_Tabs.selectedIndex > 0)` check and use tab type instead of index
Needs zotero/reader#164, closes #5260

Always show item/context pane toggle

---

chrome/content/zotero/collectionTree.jsx
chrome/content/zotero/containers/tagSelectorContainer.jsx
chrome/content/zotero/elements/attachmentBox.js
chrome/content/zotero/elements/contextPane.js
chrome/content/zotero/elements/itemPane.js
chrome/content/zotero/itemTree.jsx
chrome/content/zotero/zoteroPane.js
test/tests/collectionTreeTest.js

- right-click on annotation rows in trash will display "Delete permanently" option, instead of an empty menu
- in trash, "Add Note from Annotations" button in `itemPane` header is disabled
- remove ability to add tags to annotations and other items by dragging them into tag selector from trash
- remove ability to add items to collections by dragging them into collection tree from trash
- fix attachment row being removed from trash if its child annotation row is erased
Also:
- fix `contextPane` in reader tab being editable for items in trash
- fix title being editable in `attachmentBox` for item in trash
Fixes: #5261

Fixes to annotation rows behavior in trash

---

chrome/content/zotero/integration/citationDialog.xhtml
chrome/content/zotero/integration/citationDialog/keyboardHandler.mjs
chrome/content/zotero/integration/citationDialog/popupHandler.mjs

Unhandled Enter keypress from inside of a panel will now close it. Enter on "Omit Author" checkbox or on the inactive locator label dropdown will close the item details popup.
Enter on "Keep sources sorted" checkbox of settings popup will close it for consistency.
Also, allow Cmd/Ctrl+Enter to accept the dialog even from inside of a panel.
Fixes: #5277
Enter on item details buttons at the bottom will still just perform the click, as it would be strange if Enter on a focused "Remove" button would not actually remove the item.

Citation dialog: updated Enter handling in panels

---

chrome/content/zotero/components/virtualized-table.jsx

This actually checks for a "primary" column, so if an extension hides the "title" column but provides its own "primary" column, the "title" column remains hidden.

Unhide "title" column on "Restore Column Order"

---

chrome/content/zotero/locateMenu.js

For any selected annotation items in library, the locate button will show operations for its parent item, instead of showing nothing.

Fix locate button for annotation item

---

app/scripts/fetch_xulrunner

Use discontinue: true in update_url json
"updates" that is valid for the installed plugin
to uninstall the plugin the next time it checks update

Allow plugin to uninstall itself with update_url

---

chrome/content/zotero/elements/bubbleInput.js
chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog/helpers.mjs
chrome/content/zotero/integration/citationDialog/popupHandler.mjs
chrome/content/zotero/integration/citationDialog/searchHandler.mjs
chrome/content/zotero/xpcom/editorInstance.js
test/tests/citationDialogTest.js

`CitationDataManager.items` is an array with `zoteroItem` and `citationItem` objects used to represent cited items. `zoteroItem` is an instance of `Zotero.Item`, and `citationItem` is an object with citation data (locator/suffix/prefix, cslItemData, etc.).
If an ordinary (non-cited) item from the library is added to the citation, `citationItem` [would end up](https://github.com/zotero/zotero/blob/ed24cce4a1aaa0d78a0e2ec0be6ab003d6ccb876/chrome/content/zotero/integration/citationDialog.js#L1470) having an instance of `Zotero.Item`. In that case, if a suffix/prefix/etc. is added to the `citationItem`, it would land on the instance of `Zotero.Item` and persist even if the bubble is removed and then re-added. If two bubbles for the same item are added, both of them would share those …

Citation Dialog: fix added suffix/prefix properties persisting on items

---

chrome/content/zotero/integration/citationDialog.js
chrome/content/zotero/integration/citationDialog/searchHandler.mjs
chrome/content/zotero/xpcom/integration.js
test/tests/citationDialogTest.js

https://forums.zotero.org/discussion/124211/zotero-update-bug-delay-in-citation-insertion-search
It can take a while for all the promises that `io` needs to sort to resolve. It means that if we await for sorting while building citation on initial load, it can cause a visible delay. This is somewhat of a continuation of #5127, in which `await`-ing of cited items was removed because we should not `await` for sorting to be ready as well. 
When an item is added, only run sorting if `io` is ready for it. If `io` is not ready to sort during initial load, some bubbles may be added out of order. They will be sorted as soon as `io` is ready.
This is what it looks like with an added `Zotero.Promise.delay(5000)` to [Zotero.Integration.Session.prototype.getFields](https://github.com/zotero/zotero/blob …

Citation Dialog: more optimization of initial loading

---

chrome/content/zotero/components/windowed-list.js
chrome/content/zotero/itemTree.jsx

Extend `scrollToRow` in `windowed-list.js` to allow to scroll the specified row to the top of the window
even if it is located below the current scroll position. With this, when scroll position is restored in `itemTree`, the same row remains at the top. The root of the issue happening now is that when the scroll position is restored, the row that was originally at the top would be scrolled to in a way that would place it at the bottom of the visible window.
Fixes: #5233
Before: [recording](https://www.dropbox.com/scl/fi/i3pkb99zk5zneyavkuvkv/before.mov?rlkey=0x2e8mmbqmj8dca5uo6p3zu8r&st=p2r76zvw&dl=0)
After: [recording](https://www.dropbox.com/scl/fi/gdw9fk25i52ie91xo7blb/after.mov?rlkey=9kxf50qmfvozre09nde5o8be1&st=50xo3jzl&dl=0)

Fix new annotation changing the scroll position in itemTree

---

chrome/content/zotero/itemTree.jsx
chrome/content/zotero/zoteroPane.js
test/tests/itemTreeTest.js
test/tests/zoteroPaneTest.js

Fixes: #5320
https://github.com/user-attachments/assets/c468e90c-f15b-488e-9643-52f842d3766a

Select child attachment after a file is drag-dropped onto a top-level item

---

chrome/content/zotero/xpcom/prefs.js
chrome/locale/en-US/zotero/zotero.ftl

Scholaread sets `extensions.zotero.fileHandler.pdf` in `<profile>/user.js`, not `prefs.js`, so changing the pref via the UI does nothing (`user.js` takes precedence). This PR checks `user.js` for `user_pref()` directives, and if any are found, removes them, shows an alert, and restarts.
As far as I can tell (I haven't run it), Scholaread asks the user before adding its pref, so this _shouldn't_ happen every time you start Zotero. But if it does, maybe that's more impetus for them to stop setting it in the wrong location?

Undo Scholaread changes to `user.js`

---

chrome/content/zotero/xpcom/attachments.js
test/tests/attachmentsTest.js

This PR adds support for the "pascal" text case option in the file renaming template. It's based on this request: https://forums.zotero.org/discussion/comment/480520.
I've also noticed that our "camel" case (and the new "pascal" case) does not preserve Unicode characters, so I've fixed that.

File renaming: Add pascal case. Fix unicode handling.

---

chrome/content/zotero/xpcom/server/saveSession.js
chrome/content/zotero/zoteroPane.js

And fix regression where selecting a collection in connector would always switch to the library tab, even if a reader tab is selected.
It was originally added in https://github.com/zotero/zotero/pull/5020 but was lost after https://github.com/zotero/zotero/pull/5148

Do not open hidden Zotero window on connector save

---

chrome/content/zotero/xpcom/server/saveSession.js
chrome/content/zotero/xpcom/server/server_connector.js

It does not sound quite semantically correct, since tags don't have much to do with a selected collection but it is the endpoint called to fetch the info from the client when the connector popup appears, and it already returns not just the selected collections but all collections from all editable groups, so it felt more appropriate than adding a new tags-specific endpoint. Perhaps, `/connector/getSelectedCollection` could be renamed for something more general at some point?
Addresses: #1706
Needed for tags autocomplete in the connector: https://github.com/zotero/zotero-connectors/pull/529

Return tags together with collections in /connector/getSelectedCollection

---

chrome/content/zotero/integration/citationDialog.xhtml
scss/components/_citationDialog.scss

Make sure that `<select>` element does not stretch and cutoff the popup for locales that have longer locator labels than English.
Fixes: #5350

Citation dialog: fix broken item details popup with some non-english locales

---

chrome/content/zotero/elements/itemPaneHeader.js
scss/abstracts/_mixins.scss
scss/elements/_itemMessagePane.scss
scss/elements/_itemPaneAnnotations.scss
scss/elements/_itemPaneHeader.scss
scss/elements/_noteEditor.scss

Unify very similar styles used by four different custom elements and move the shared code into a mixin.
The most noticeable improvements are:
* Buttons no longer "jump around" (see video in #5372)
* The background colour remains consistent — previously, some elements used the toolbar background, while others used the sidepane background.
@windingwind I've removed some of your styles to fix buttons "jumping around" (`button` and `.button-text` in `scss/elements/_itemPaneHeader.scss`). If you believe this breaks something, please let me know.
Before:
https://github.com/user-attachments/assets/c3f1c7f5-c6b6-4855-8d6d-00fa2a421af1
After:
https://github.com/user-attachments/assets/498a4a59-774f-47fc-80a5-d3d833223050
I've also tested on Windows, where this issue is also present (though perhaps …

Unify styles for headers of similar custom elements

---

chrome/content/zotero/xpcom/storage/storageEngine.js

Fix the issue where Zotero.Sync.Runner.sync({background: true}) cannot obtain the itemIDs

fix the  missing "yield" in line 158 of storageEngine.js

---

chrome/content/zotero/xpcom/plugins.js

When reinstalling the same plugin (upgrading or downgrading), `bootstrap` is not destroyed, resulting in the new plugin still using the old `bootstrap.js`.
`bootstrap.js` version 1
```js
function install(data, reason) {}
async function startup({ id, version, resourceURI, rootURI }, reason) {
await Zotero.initializationPromise;
/**
* Global variables for plugin code.
* The `_globalThis` is the global root variable of the plugin sandbox environment
* and all child variables assigned to it is globally accessible.
* See `src/index.ts` for details.
*/
const ctx = {
rootURI,
};
ctx._globalThis = ctx;
Services.scriptloader.loadSubScript(`${rootURI}/content/scripts/__addonRef__.js`, ctx);
// Zotero.__addonInstance__.hooks.onStartup();
Zotero.debug("Plugin started - 1");
}
async function …
```

Clean plugin cache on re-install

---

chrome/content/zotero/fileInterface.js
chrome/content/zotero/xpcom/integration.js
chrome/content/zotero/xpcom/quickCopy.js
chrome/content/zotero/xpcom/style.js

Uncached:
```
zotero(3)(+0022127): Keyboard shortcut: copySelectedItemsToClipboard
zotero(3)(+0004691): Caching Engine instance for {"locale":"en-US","format":"html","automaticJournalAbbreviations":false} on http://www.zotero.org/styles/chicago-notes-bibliography
zotero(3)(+0004567): Caching Engine instance for {"locale":"en-US","format":"text","automaticJournalAbbreviations":false} on http://www.zotero.org/styles/chicago-notes-bibliography
zotero(3)(+0000013): Copied bibliography to clipboard in 9270 ms
```
Cached:
```
zotero(3)(+0005101): Keyboard shortcut: copySelectedItemsToClipboard
zotero(3)(+0000030): Copied bibliography to clipboard in 28 ms
```
A mere 331x speedup! (For some reason subsequent Engine instantiations for the same style are especially bad - first-time instantiations, …

Cache CiteProc Engine instances, pre-cache for Quick Copy

---

chrome/content/zotero/tabs.js
chrome/content/zotero/xpcom/notifier.js
chrome/content/zotero/xpcom/prefs.js
chrome/content/zotero/xpcom/utilities_internal.js

And complain about observers that leak windows.
Can cherry-pick this to fx140. It matters more there because the event loop stops running on closed windows, meaning promises never resolve.

Unregister `Zotero_Tabs` observers when window is unloaded

---

scss/components/_search.scss

`searchfield-cancel.svg` no longer exists, use `close-12.svg` that is the same one used by search-textbox
Before:
After:

Fx140: update X icon for search cancel button

---

test/runtests.sh

Choose the build folder depending on the x86 vs arm architecture. Otherwise, if you call `runtest.sh` on arm linux, it tried to run zotero from `Zotero_linux-x86_64`.

fx140: use the correct build folder on linux in runtest.sh depending on x86 vs arm

---

test/tests/hyphenationTest.js
test/tests/preferences_syncTest.js
test/tests/readerTest.js

- close `hyphenationTest window.
- properly close `zoteroPane` window in `preferences_syncTest`. `after()` hook inside of the test would not close the window until the very end of the entire test run. Without this, during subsequent tests that open their own `zoteroPane` window, there are two instances of `zoteroPane` open at the same time.
- close open tabs in `readerTest` cleanup, since subsequent tests expect library tab to be selected.
Followup to https://github.com/zotero/zotero/pull/5444#issuecomment-3141879892

Close more leftover windows in tests

---

chrome/content/zotero/xpcom/attachments.js
chrome/content/zotero/xpcom/cookieSandbox.js
chrome/content/zotero/xpcom/utilities_internal.js

And probably some other sites with auth redirects that set cookies.
- Wrap Find Full Text requests and translation in a CookieSandbox
- Pre-fx115, our XHRs would've implicitly used global cookies. Now system XHRs [are anonymous](https://bugzilla.mozilla.org/show_bug.cgi?id=1881800) (`mozAnon`) by default, so we need to use a CookieSandbox in order to track cookies between requests. (Redirects are separate requests here because we handle them manually.)
- ProQuest-specific: When you first connect to ProQuest using a proxy/VPN, it sends you through https://www.proquest.com/intermediateredirectforezproxy, which uses a JS redirect to bring you back to the page you originally requested. We can't detect that, so just treat a 200 response from `/immediateredirectforezproxy` like a redirect back …

Fix Find Full Text failing on ProQuest

---

chrome/content/zotero/xpcom/data/items.js
test/content/support.js
test/tests/itemsTest.js

PDFs: Behavior unchanged. Attachments are always left alone if their files are missing. A master-item attachment with a missing file never has anything else merged into it, and a non-master-item attachment with a missing file is never merged into anything else. This is because we don't know if the missing PDF is a different version or has external annotations.
Snapshots: Previously, a master-item attachment with a missing file could have other attachments from non-master items merged into it. That was a bug. Now a master-item attachment with a missing file never has anything else merged into it, but we _do_ allow a non-master attachment with a missing file to be merged into a matching master attachment. In other words, we're OK deleting a missing snapshot from the non-master item, as long …

Don't merge into a missing snapshot attachment

---

chrome/content/zotero/xpcom/zotero.js
chrome/content/zotero/zoteroPane.js

I wasn't able to test it as a whole - I set up a Parallels VM running Ubuntu with the Rosetta layer for this and jumped through some hoops trying to get it to work, but the x64 binary segfaults on that system (7.x does as well).
Resolve #5448

Warn users running non-ARM version on ARM CPU on Linux

---

chrome/content/zotero/zoteroPane.js
test/tests/zoteroPaneTest.js

(An error was only thrown on macOS, because `getEvictedICloudPath()` is currently the only method that throws on an invalid path that we call when the file doesn't exist, but the test runs on both macOS and Linux in case that changes.)
Fixes #5483

Handle invalid path when launching/revealing on macOS

---

chrome/content/zotero/xpcom/data/items.js
test/tests/duplicatesTest.js

When copying over relations during merge of items that are related to one another, avoid relating the chosen main item to itself.
Fixes: #5487

Fix post-merge item having a relation to itself

---

chrome/content/zotero/xpcom/sync/syncEngine.js
test/tests/syncEngineTest.js

Fix ghost relations to erased items re-appearing after sync. The dataserver ensures that `dc:relation` relations are bidirectional. On the client side, a simple way to verify this is to remove relation from one item, save it, sync - the relation will be restored. When a related item is erased, syncing would first upload the update to the remaining related item (where the relation is removed), followed by the deletions. While handling update upload, the dataserver would return the old, should-be-removed, `dc:relation` entry for that item because it does not know that the other item is erased.
To handle this, swap the order of operations during sync: upload deletion first and then upload updates after. Then, when the dataserver handles the update of the non-erased item, there is no related …

Fix relations to erased items re-appearing after sync

---

chrome/content/zotero/zoteroPane.js

By using `getSelectedItems()` instead of `getSelectedObjects()`. The code below all assumes that `items` contains items, and we handle general (item or collection) options above, so this seems more correct.
And fix duplicate var.
Fixes #5496

Fix errors when multi-selection contains collections in trash

---

chrome/content/zotero/xpcom/feedReader.js
resource/feeds/FeedProcessor.mjs
resource/feeds/SAXXMLReader.mjs

And fully remove references to `hiddenDOMWindow`. We haven't needed to run this code in a DOM window since Z7 (it just needs `DOMParser` and `TreeWalker`, which are available in windowless contexts). This also has the very small benefit of allowing feeds to update when the main window is closed on macOS.

ESMify feed processing code

---

chrome/content/zotero/elements/itemBox.js
test/tests/itemPaneTest.js

If `itemBox` refresh happens when an input is focused and has some unsaved changes, restore the value of the input after the refresh.
Potential solution for:
https://forums.zotero.org/discussion/126273/bug-data-that-is-input-is-not-saved-and-needs-to-be-entered-again
---
I have not been able to naturally reproduce the issue from the forums post above. However, I do see the following in the debug log: `Showing editor for publisher ... Showing editor for publisher ... Hiding editor for publisher`.  One `Hiding editor for publisher` is missing. That means that if you have some changes typed in after the first `Showing editor for publisher`, on the second `Showing editor for publisher` (which is refresh and refocusing of the previously focused field), those changes are just discarded. We …

Itembox: restore unsaved input value after refresh

---

chrome/content/zotero/xpcom/zotero.js
test/tests/zoteroTest.js

And:
- Remove `rv:` replacement after fx140 upgrade
- Remove special handling for tests, since we now run tests in Zotero

Keep Zotero in the User-Agent, add Firefox

---

chrome/content/zotero/elements/zoteroSearch.js

Fix regression after 4d803fe2cdb8de7bb812f0dfeffac9b103d12cbd which caused the operator for condition to never get set.
Fixes: #5537

Fix zoteroSearch missing options for attachment type condition

---

chrome/content/zotero/integration/quickFormat.js

Account for the fact that items returned in `Zotero_Tabs.getState()` could be erased, in which case we should not try to load them.
Fixes: #5534

QuickFormat: fix breakage if unloaded tab's item is deleted

---

chrome/content/zotero/xpcom/pluginAPI/menuManager.js
chrome/content/zotero/xpcom/pluginAPI/pluginAPIBase.mjs

Fix menuManager removedkeys.join is not function on plugin shundown

---

chrome/content/zotero/elements/librariesCollectionsBox.js
chrome/content/zotero/elements/noteEditor.js

Display Libraries and Collections box in the itemPane for standalone notes and attachments.
Fixes: #5553

Display libraries and collections box for standalone notes and attachments

---

chrome/content/zotero/collectionTree.jsx

When drag-dropping items into a collection in another library, perform the addition to collection in the same transaction as creating a new item in the target library. This way, the notifier event does not fire until the item is copied to the group AND added to the collection.
When the `librariesCollectionsBox` refreshes on the `modify` event when a newly created group item is linked to the selected item, it re-loads the data of the linked item via `item.loadAllData()`. This could happen after the item is added to the collection but before this change is saved. In that case, `item._changed.collections` would be cleared, and when the item is saved, there would be no changes to collections to save. More details on this scenario: https://github.com/zotero/zotero/issues/5539#issuecomment-32942 …

Fix item sometimes not added to collection on cross-library drag-drop

---

chrome/content/zotero/merge.js

Fix "Next" button not appearing in conflict resolution dialog on linux and windows

---

chrome/content/zotero/elements/attachmentBox.js
test/tests/itemPaneTest.js

When an embedded attachment note is converted to a standalone note, relate the standalone note to the attachment and place it in the same collections as the attachment.
Before:
https://github.com/user-attachments/assets/ebe42a89-bf69-47ae-a410-3a02fe9f57e0
After:
https://github.com/user-attachments/assets/e0b979dd-7936-4222-b307-d0b7480b994b

Related note to its previous attachment after converting from embedded to standalone

---

chrome/content/zotero/elements/itemPaneHeader.js
chrome/content/zotero/xpcom/quickCopy.js
chrome/content/zotero/xpcom/translation/translators.js
chrome/content/zotero/xpcom/zotero.js

1. Don't bother pre-caching a CSL.Engine for the item pane header if it isn't initially set to `bibEntry` mode. Initializing the engine takes a couple hundred milliseconds (synchronously!) for some styles, so best to avoid when it isn't needed.
2. Fix a nasty Quick Copy `init` race condition:
`QuickCopy.init()` calls `Style#getCiteProc()`, and a side effect of citeproc-js locale initialization could cause a recursive call back to `QuickCopy.init()`, which would again call `Style#getCiteProc()` (after it had checked its cache but before it had added the new engine to it), leading to an extra, unnecessary CSL.Engine initialization on launch. Now we correctly check whether we've already been initialized, eliminating the race condition.
Separately, remove `async` keyword from `init()`. It …

Fixes for CSL.Engine pre-caching issues and race conditions
